---
sidebar: sidebar 
permalink: cli-upgrade-esxi.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 8.0 
summary: ONTAP SelectをVMware ESXi上で実行している場合は、ESXiソフトウェアを以前のサポート対象バージョンからESXi 8.0以降にアップグレードできます。アップグレードする前に、プロセスを理解し、適切なアップグレード手順を選択してください。 
---
= ONTAP Selectの VMware ESXi 8.0 以降にアップグレードします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SelectをVMware ESXi上で実行している場合は、ESXiソフトウェアを以前のサポート対象バージョンからESXi 8.0以降にアップグレードできます。アップグレードする前に、プロセスを理解し、適切なアップグレード手順を選択してください。



== VMware ESXi のアップグレードの準備

ONTAP Selectクラスタをホストしているハイパーバイザー上の ESXi ソフトウェアをアップグレードする前に、環境に適したアップグレード手順を準備して選択します。

.手順
. *VMware ESXi のアップグレード方法を理解する*
+
ESXi ソフトウェアのアップグレードは、 VMware で説明され、サポートされているプロセスです。ハイパーバイザーのアップグレードプロセスは、 ONTAP Select を使用する場合の大規模なアップグレード手順 の一部です。詳細については、VMwareのドキュメントを参照してください。

. *アップグレード手順を選択してください*
+
いくつかのアップグレード手順があります。次の基準に基づいて、該当する手順 を選択する必要があります。

+
** ONTAP Selectクラスタサイズ
+
単一ノード クラスターと複数ノード クラスターの両方がサポートされています。

** ONTAP Select Deployの使用
+
アップグレードは、デプロイ ユーティリティの有無にかかわらず可能です。

+

TIP: Deploy 管理ユーティリティを使用するアップグレード手順 を選択する必要があります。

+
Deploy管理ユーティリティを使用してESXiのアップグレードを実行する方が、より汎用的で復元力の高いオプションです。ただし、デプロイが利用できない、または使用できない場合があります。例えば、ESXi 8.0へのアップグレードは、以前のバージョンのONTAP SelectおよびDeploy管理ユーティリティではサポートされていません。

+
これらの旧バージョンを使用している場合にアップグレードを試行すると、 ONTAP Select 仮想マシンをブートできない状態のままにすることができます。この場合は、 Deploy を使用しないアップグレード手順 を選択する必要があります。を参照してください link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] を参照してください。



. *デプロイ管理ユーティリティをアップグレードする*
+
Deploy ユーティリティを使用してアップグレード手順を実行する前に、Deploy インスタンスをアップグレードする必要がある場合があります。通常は、最新バージョンのDeployにアップグレードしてください。Deployユーティリティは、使用しているONTAP Selectのバージョンをサポートしている必要があります。参照link:reference_release_notes.html["ONTAP Selectリリースノート"]詳細についてはこちらをご覧ください。

. *アップデート手順が完了したら*
+
Deploy ユーティリティを使用するアップグレード手順 を選択する場合は、すべてのノードをアップグレードしたあとに、 Deploy を使用してクラスタの更新処理を実行する必要があります。詳細については、 Deploy クラスタ設定の更新を参照してください。





== Deployを使用したシングルノードクラスタのアップグレード

Deploy 管理ユーティリティは、手順 の一部として使用して、 ONTAP Select シングルノードクラスタをホストする VMware ESXi ハイパーバイザーをアップグレードできます。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ノードをオフライン状態に移動します。
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. VMware が提供する手順を使用して、 ONTAP Select が実行されているハイパーバイザー ホストを ESXi 8.0 以降にアップグレードします。
. ノードをオンライン状態に移動します。
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. ノードが起動したら、クラスタが正常であることを確認します。
+
例：

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.完了後
Deploy 管理ユーティリティを使用してクラスタの更新処理を実行する必要があります。



== Deployを使用したマルチノードクラスタのアップグレード

Deploy 管理ユーティリティは、手順 の一部として使用して、 ONTAP Select マルチノードクラスタをホストする VMware ESXi ハイパーバイザーをアップグレードできます。

.このタスクについて
このアップグレード手順 は、クラスタ内のノードごとに 1 つずつ実行する必要があります。クラスタに 4 つ以上のノードがある場合は、各 HA ペアのノードを次の HA ペアに進む前に順番にアップグレードしてください。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ノードをオフライン状態に移動します。
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. VMware が提供する手順を使用して、 ONTAP Select が実行されているハイパーバイザー ホストを ESXi 8.0 以降にアップグレードします。
+
詳細については、「 VMware ESXi のアップグレードの準備」を参照してください。

. ノードをオンライン状態に移動します。
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. ノードが起動したら、ストレージフェイルオーバーが有効になっていてクラスタが正常に動作していることを確認します。
+
.例を表示
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.完了後
アップグレード手順 は、 ONTAP Select クラスタで使用するホストごとに実行する必要があります。すべての ESXi ホストをアップグレードしたら、 Deploy 管理ユーティリティを使用してクラスタの更新処理を実行する必要があります。



== Deployを使用しないシングルノードクラスタのアップグレード

ONTAP Select シングルノードクラスタをホストしている VMware ESXi ハイパーバイザーは、 Deploy 管理ユーティリティを使用せずにアップグレードできます。

.手順
. ONTAP のコマンドラインインターフェイスにサインインしてノードを停止します。
. VMware vSphere を使用して、 ONTAP Select 仮想マシンの電源がオフになっていることを確認します。
. VMware が提供する手順を使用して、 ONTAP Select が実行されているハイパーバイザー ホストを ESXi 8.0 以降にアップグレードします。
+
詳細については、「 VMware ESXi のアップグレードの準備」を参照してください。

. VMware vSphere を使用して vCenter にアクセスし、次の手順を実行します。
+
.. ONTAP Select 仮想マシンにフロッピードライブを追加します。
.. ONTAP Select 仮想マシンの電源をオンにします。
.. 管理者アカウントで SSH を使用して ONTAP CLI にサインインします。


. ノードが起動したら、クラスタが正常であることを確認します。
+
例：

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.完了後
Deploy 管理ユーティリティを使用してクラスタの更新処理を実行する必要があります。



== Deployを使用しないマルチノードクラスタのアップグレード

ONTAP Select マルチノードクラスタをホストする VMware ESXi ハイパーバイザーは、 Deploy 管理ユーティリティを使用せずにアップグレードできます。

.このタスクについて
このアップグレード手順 は、クラスタ内のノードごとに 1 つずつ実行する必要があります。クラスタに 4 つ以上のノードがある場合は、各 HA ペアのノードを次の HA ペアに進む前に順番にアップグレードしてください。

.手順
. ONTAP のコマンドラインインターフェイスにサインインしてノードを停止します。
. VMware vSphere を使用して、 ONTAP Select 仮想マシンの電源がオフになっていることを確認します。
. VMware が提供する手順を使用して、 ONTAP Select が実行されているハイパーバイザー ホストを ESXi 8.0 以降にアップグレードします。
. VMware vSphere を使用して vCenter にアクセスし、次の手順を実行します。
+
.. ONTAP Select 仮想マシンにフロッピードライブを追加します。
.. ONTAP Select 仮想マシンの電源をオンにします。
.. 管理者アカウントで SSH を使用して ONTAP CLI にサインインします。


. ノードが起動したら、ストレージフェイルオーバーが有効になっていてクラスタが正常に動作していることを確認します。
+
.例を表示
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.完了後
アップグレード手順 は、 ONTAP Select クラスタで使用するホストごとに実行する必要があります。
