---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: サンプルの Python スクリプトを使用すると、いくつかの異なるタスクを実行できます。スクリプトをライブ Deploy インスタンスで使用する前に、それらのスクリプトについて理解しておく必要があります。 
---
= Pythonスクリプトを理解する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サンプルの Python スクリプトを使用すると、いくつかの異なるタスクを実行できます。スクリプトをライブ Deploy インスタンスで使用する前に、それらのスクリプトについて理解しておく必要があります。



== 共通の設計特性

スクリプトは、次の一般的な特性で設計されています。

* クライアントマシンでコマンドラインインターフェイスから実行する適切に設定された任意のクライアントマシンから Python スクリプトを実行できます。詳細については、を参照してください。
* CLI 入力パラメータの受け入れ各スクリプトは、入力パラメータを使用して CLI で制御されます。
* 読み取り入力ファイル各スクリプトは、その目的に基づいて入力ファイルを読み取ります。クラスタを作成または削除する場合は、 JSON 構成ファイルを指定する必要があります。ノードライセンスを追加する場合は、有効なライセンスファイルを指定する必要があります。
* 共通サポートモジュールを使用共通サポートモジュール _deploy_requests_py_contains a single classインポートされ、各スクリプトで使用されます。




== クラスタを作成します

スクリプト cluster.py を使用して、 ONTAP Select クラスタを作成できます。JSON 入力ファイルの CLI パラメータと内容に基づいて、次のようにスクリプトを導入環境に変更できます。

[NOTE]
====
* ONTAP Select 9.10.1以降、KVMハイパーバイザーに新しいクラスタを導入することはできなくなりました。
* ONTAP Select 9.11.1以降では、既存のKVMクラスタおよびホストですべての管理機能を使用できなくなりました。ただし、Take offline機能とdelete機能は除きます。


====
* ハイパーバイザーESXiまたはKVMに導入できます（Deployリリースによって異なります）。ESXi に導入する際、ハイパーバイザーは vCenter で管理することも、スタンドアロンホストにすることもできます。
* クラスタサイズ：シングルノードクラスタまたはマルチノードクラスタを導入できます。
* 評価用ライセンスまたは本番用ライセンス：本番環境用の評価用ライセンスまたは購入ライセンスを使用してクラスタを導入できます。


スクリプトの CLI 入力パラメータは次のとおりです。

* Deploy サーバのホスト名または IP アドレス
* admin ユーザアカウントのパスワード
* JSON 構成ファイルの名前
* メッセージ出力の詳細フラグ




== ノードライセンスを追加

本番環境クラスタの導入を選択した場合は、 script_add_license.py__ を使用して各ノードのライセンスを追加する必要があります。ライセンスはクラスタの導入前または導入後に追加できます。

スクリプトの CLI 入力パラメータは次のとおりです。

* Deploy サーバのホスト名または IP アドレス
* admin ユーザアカウントのパスワード
* ライセンスファイルの名前
* ライセンスを追加するための権限を持つ ONTAP ユーザ名
* ONTAP ユーザのパスワード




== クラスタを削除します

既存の ONTAP Select クラスタは、 script_delete_cluster.py _ を使用して削除できます。

スクリプトの CLI 入力パラメータは次のとおりです。

* Deploy サーバのホスト名または IP アドレス
* admin ユーザアカウントのパスワード
* JSON 構成ファイルの名前

