---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: まず、 ONTAP Select 環境に適用される一般的なネットワークの概念を理解します。次に、シングルノードクラスタとマルチノードクラスタに対応する特徴とオプションを確認します。 
---
= ネットワーク：一般的な概念と特徴
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
まず、 ONTAP Select 環境に適用される一般的なネットワークの概念を理解します。次に、シングルノードクラスタとマルチノードクラスタに対応する特徴とオプションを確認します。



== 物理ネットワーク

物理ネットワークは、主に基盤となるレイヤ 2 スイッチングインフラを提供することで、 ONTAP Select クラスタ環境をサポートします。物理ネットワークに関連する構成には、ハイパーバイザーホストと、広範囲にスイッチ化されたネットワーク環境の両方が含まれます。



=== ホストの NIC オプション

各 ONTAP Select ハイパーバイザーホストは、 2 つまたは 4 つの物理ポートを使用して設定する必要があります。選択する構成は、次に示すいくつかの要因で決まります。

* クラスタに ONTAP Select ホストが 1 つ以上含まれているかどうか
* 使用されているハイパーバイザーのオペレーティングシステム
* 仮想スイッチの設定方法
* リンクで LACP が使用されるかどうか




=== 物理スイッチの構成

物理スイッチの構成で ONTAP Select 環境がサポートされていることを確認する必要があります。物理スイッチは、ハイパーバイザーベースの仮想スイッチと統合されます。選択する構成は、いくつかの要因で決まります。主な考慮事項は次のとおりです。

* 内部ネットワークと外部ネットワークの分離を維持するにはどうすればよいですか。
* データネットワークと管理ネットワークの分離を維持するかどうか
* レイヤ 2 VLAN はどのように設定されますか。




== 論理ネットワーク

ONTAP Select は 2 つの異なる論理ネットワークを使用し、タイプに応じてトラフィックを分離します。具体的には、トラフィックがクラスタ内のホスト間を流れ、クラスタの外部にあるストレージクライアントやその他のマシンに到達します。論理ネットワークをサポートするのは、ハイパーバイザーによって管理される仮想スイッチです。



=== 内部ネットワーク

マルチノードクラスタ環境では、個々の ONTAP Select ノードは独立した「内部」ネットワークを使用して通信します。このネットワークは公開されておらず、 ONTAP Select クラスタ内のノードの外部では使用できません。


NOTE: 内部ネットワークはマルチノードクラスタにのみ対応します。

内部ネットワークには次のような特徴があります。

* 次の ONTAP クラスタ内トラフィックの処理に使用されます。
+
** クラスタ
** High Availability Interconnect （ HA-IC ； HA インターコネクト）
** RAID 同期ミラー（ RSM ）


* VLAN に基づく単一のレイヤ 2 ネットワーク
* 静的 IP アドレスは ONTAP Select によって割り当てられます。
+
** IPv4 のみ
** DHCP は使用されません
** リンクローカルアドレス


* MTU サイズはデフォルトで 9000 バイトで、 7500~9000 の範囲内で調整できます（両端の値を含む）




=== 外部ネットワーク

外部ネットワークは、 ONTAP Select クラスタのノードと外付けストレージクライアントおよびその他のマシンの間のトラフィックを処理します。外部ネットワークはすべてのクラスタ環境に含まれており、次のような特徴があります。

* 次の ONTAP トラフィックの処理に使用されます。
+
** データ（ NFS 、 CIFS 、 iSCSI ）
** 管理（クラスタとノード。必要に応じて SVM ）
** クラスタ間（オプション）


* 必要に応じて VLAN をサポート：
+
** データポートグループ
** 管理ポートグループ


* 管理者による設定の選択内容に基づいて割り当てられる IP アドレス：
+
** IPv4 または IPv6


* MTU サイズはデフォルトで 1500 バイト（調整可能）


外部ネットワークはあらゆるサイズのクラスタに対応します。



== 仮想マシンのネットワーク環境

ハイパーバイザーホストは、いくつかのネットワーク機能を提供します。

ONTAP Select は、仮想マシンを通じて次の機能を利用できます。

仮想マシンのポート:: ONTAP Select で使用できるポートがいくつかあります。割り当てと使用は、クラスタのサイズなど、いくつかの要因に基づいて行われます。
仮想スイッチ:: vSwitch （ VMware ）または Open vSwitch （ KVM ）に関係なく、ハイパーバイザー環境内の仮想スイッチソフトウェアは、仮想マシンが公開するポートを物理イーサネット NIC ポートに結合します。それぞれの環境に応じて、各 ONTAP Select ホストに対して vSwitch を設定する必要があります。

