---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: ONTAP Select Deploy は、 ONTAP Select クラスタの導入と管理に使用する管理ユーティリティです。 
---
= ONTAP Select 導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy は、 ONTAP Select クラスタの導入と管理に使用する管理ユーティリティです。Deploy は Linux 仮想マシンとしてパッケージ化されており、 ONTAP Select クラスタを作成する前にインストールする必要があります。



== コア機能

Deploy 管理ユーティリティでは、次の主要機能が実行されます。

* ONTAP Select を導入する各ハイパーバイザーホストの詳細を記録します
* ホストを設定し、必要なライセンスをインストールします
* ONTAP Select クラスタを導入および管理する
* ONTAP Select のクラスタとホストのインベントリを維持する
* AutoSupport データを収集してネットアップに送信
* ONTAP Select ノードイメージの内部セットを保持します
* ハイパーバイザー固有のコマンド形式とプロトコルをサポートします




== Deploy ユーティリティにアクセスする方法

Deploy 管理ユーティリティへのアクセス時にはいくつかのオプションを使用できます。すべての外部インターフェイスは機能的に同じです。導入の目標と要件に最も適したアクセスオプションを選択する必要があります。いずれの場合も、有効なパスワードを持つ管理者アカウントを使用してサインインする必要があります。



=== Web グラフィカルユーザインターフェイス

デプロイユーティリティには、最新のWebブラウザからアクセスできます。WebUIは直感的で使いやすいインターフェースを提供し、ほとんどの場合、ユーティリティを使用する際の主要なインターフェースとなります。



=== コマンドラインインターフェイス

テキストベースのコマンドラインインターフェイスは、管理シェルを通じて使用できます。CLI 管理シェルには次の方法でアクセスできます。

* Secure Shell （ SSH ） Secure Shell （ SSH ）
* 仮想マシンコンソール


通常は、インストールおよび初期設定プロセスの一環として、仮想マシンのコンソールを使用します。ただし、ほとんどの場合、 SSH ではより柔軟で便利なオプションが提供されます。



=== REST Web サービス API

外部クライアントに公開される REST Web サービス API は、 Deploy ユーティリティへの接続時にもう 1 つのオプションを提供します。API には、 REST Web サービスをサポートする主流のプログラミング言語やツールを使用してアクセスできます。一般的な選択肢：

* Python
* Java
* カール


プログラミング言語またはスクリプト言語を使用すると、 ONTAP Select クラスタの導入と管理を自動化する機会が得られます。



=== ONTAP Select オンラインドキュメント Web ページ

Deploy ユーティリティでオンラインドキュメントの Web ページを表示することは、 REST Web サービス API にアクセスするもう 1 つの方法です。ただし、プログラミング言語を使用する代わりに、ブラウザから管理 API にアクセスできます。提供される機能は次のとおりです。

* REST Web サービス API の各呼び出しの詳細な概要
* 任意の API 呼び出しを手動で問題 する機能


Deploy 仮想マシンの IP またはドメイン名を使用して、オンラインドキュメントページにアクセスできます。ページを表示するには、ブラウザに次の形式の URL を入力します（お使いの Deploy VM インスタンスに対応する IP アドレスまたはドメイン名に置き換えてください）：「 \ http://<ip_address>/api/ui` 」
