---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: ONTAP Select の調査と導入の計画を開始するにあたって、まず用語や主な概念を理解しておくと役立ちます。 
---
= ONTAP Selectの用語と主要概念
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の調査と導入の計画を開始するにあたって、まず用語や主な概念を理解しておくと役立ちます。

ONTAP Select 導入:: ONTAP Select Deploy は、 ONTAP Select クラスタの導入に使用する管理ユーティリティです。Deploy ユーティリティは、専用の Linux 仮想マシンで実行されます。Deploy ユーティリティには、 Web ユーザインターフェイス、 CLI 管理シェル、および REST API を使用してアクセスできます。
カーネルベースの仮想マシン:: Kernel-Based Virtual Machine（KVM）はLinuxカーネルの仮想化機能で、ハイパーバイザープラットフォームとして機能できます。さまざまなゲストオペレーティングシステムがサポートされています。
ハイパーバイザーホストと ONTAP Select ノードです:: a_hypervisor host_ は、 ONTAP Select 仮想マシンをホストするコアハードウェアプラットフォームです。ハイパーバイザーホストに導入されてアクティブになった ONTAP Select 仮想マシンは、 _ ONTAP Select Node_. とみなされます。
ONTAP Select クラスタ:: 作成する ONTAP Select cluster_は 、 1 ノード、 2 ノード、 4 ノード、 6 ノード、または 8 ノードで構成できます。マルチノードクラスタには、必ず 1 つ以上の HA ペアが含まれます。たとえば、 4 ノードクラスタは 2 つの HA ペアで構成されます。シングルノードクラスタには HA 機能はありません。
ハイパーバイザーホスト環境の準備:: Deploy 管理ユーティリティを使用して ONTAP Select クラスタを導入する前に、ストレージ環境とネットワーク環境を含む、 ONTAP Select を実行するハイパーバイザーホストを準備する必要があります。このホストの事前設定は、現在の要件と制限事項に基づいて、 ONTAP Select 製品の外部で実行されます。
評価および本番環境への導入:: すべての ONTAP Select ノードは、 _evaluation license_or_purchased license_で 実行されます。評価用ライセンスを使用すると、本番環境に導入する前に ONTAP Select を評価できます。評価用ライセンスが自動的に生成されて適用されます。本番環境にクラスタを導入する場合は、次のいずれかを選択してライセンスを購入する必要があります。
+
--
* ライセンスモデル
* ストレージ容量
* プラットフォームライセンスの提供


--
容量階層のライセンスモデル:: 容量階層のライセンスモデルは、ONTAP Select環境用にストレージのライセンスを取得する際の元 々 のオプションです。この値は、 NetApp AFF および FAS で使用される ONTAP モデルに基づいています。ノードごとに個別のライセンスが必要です。ストレージ容量はノードにロックされ、永続的に更新されることはありません。
容量プールのライセンスモデル:: 容量プールライセンスモデルは、Deploy 2.10を使用したONTAP Select 9.5で導入されました。ストレージ容量プールごとに個別のライセンスが必要です。容量プールライセンスはLicense Managerインスタンス（Deployインスタンス）にロックされているため、購入条件に基づいて更新する必要があります。組織内の任意の数の容量プールのライセンスを取得して使用できます。ただし、容量プールはONTAP Selectノードで共有されるため、通常は容量階層のライセンスよりも少ないライセンスが必要です。
License Manager の略:: License Managerは、容量プールのライセンスをサポートするソフトウェアコンポーネントです。現時点では、 Deploy 管理ユーティリティに含まれています。LM は、管理対象の共有プールから ONTAP Select ノードにストレージをリースします。_License Lock ID_ は、各 LM インスタンスを一意に識別する数値文字列であるため、各 Deploy インスタンスを識別します。ライセンスファイルの生成には、容量プールライセンスのシリアル番号とLLIDの両方を使用する必要があります。
プラットフォームライセンスの提供:: ライセンスの購入時に ONTAP Select 仮想マシンのサイズ機能を決定するライセンスサービスは 3 種類あります。
+
--
* 標準
* Premium サービス
* Premium XL


--


詳細については、 2 つのセクション _Plan_and _License_. を参照してください。

ストレージプールとデータストアの比較:: ONTAP Select ストレージプールは、基盤となる物理ストレージを抽象化して見えなくすることを目的として設計された論理データコンテナです。ストレージプールはハイパーバイザーに依存しません。ESXi ハイパーバイザーホストに導入した ONTAP Select ストレージプールは、 vmware_datastore__ と同義です。
クラスタ MTU:: クラスタ MTU は、 ONTAP Select マルチノードクラスタで使用される内部ネットワークで使用される MTU サイズを設定できる機能です。Deploy 管理ユーティリティは、ネットワーク環境に合わせて HA ペアを設定する際に MTU サイズを調整します。値は手動で設定することもできます。
ONTAP Select vNAS:: ONTAP Select vNAS 解決策 を使用すると、 ONTAP Select ノードから外付けストレージ上の VMware データストアにアクセスできます。ONTAP Select vNAS では、ローカルの RAID コントローラが必要ありません。 RAID 機能はリモートストレージが提供します。ONTAP Select vNAS の設定方法は次のとおりです。
+
--
* VMware vSAN
* 汎用の外付けストレージアレイ


--


どちらの場合も、 ONTAP Select クラスタの作成前または既存のノードのストレージ容量の拡張前に、外付けストレージを設定する必要があります。

ESXi VMでのノードのリホスト:: ONTAP Select vNAS 解決策 （ VMware vSAN または汎用の外付けストレージアレイ）を介して利用可能な外付けストレージを使用するクラスタを導入すると、 ONTAP Select ノードをホストする ESXi 仮想マシンを、次の VMware の機能を利用して移動できます。
+
--
* vMotion
* 高可用性（ HA ）
* Distributed Resource Scheduler （ DRS ）
+
ONTAP Select Deploy ユーティリティは、クラスタで実行される次のような処理の一環として、仮想マシンの移動を検出します。

* クラスタがオンラインです
* クラスタがオフラインです
* ストレージの追加
+
仮想マシンが移動されると、 Deploy ユーティリティはその内部データベースを更新して、新しい ESXi ホストを設定します。ONTAP Select ノードで実行されるすべての操作は、仮想マシンの移動と Deploy による更新が完了するまでブロックされます。



--
KVM用Open vSwitch:: Open vSwitch（OVS）は、複数のネットワークプロトコルをサポートする仮想スイッチのソフトウェア実装です。OVSはオープンソースであり、Apache License 2.0に従って利用可能である。
メディエーターサービス:: ONTAP Select Deploy ユーティリティには、アクティブな 2 ノードクラスタ内のノードに接続するメディエーターサービスが含まれています。このサービスは各 HA ペアを監視し、障害の管理を支援します。



CAUTION: アクティブな 2 ノードクラスタが 1 つ以上ある場合は、クラスタを管理する ONTAP Select Deploy 仮想マシンが常時稼働している必要があります。Deploy 仮想マシンが停止すると、メディエーターサービスが使用できなくなり、 2 ノードクラスタの HA 機能が失われます。

MetroCluster SDS:: MetroCluster SDS は、 2 ノード ONTAP Select クラスタを導入する際に追加の設定オプションを提供する機能です。通常の 2 ノード ROBO 環境とは異なり、 MetroCluster SDS ノードはより長い距離で分離できます。この物理的な分離により、ディザスタリカバリなど、さらに多くのユースケースに対応できます。MetroCluster SDS を使用するには、 Premium ライセンス以上が必要です。また、ノード間のネットワークで最小レイテンシ要件がサポートされている必要があります。
クレデンシャルストア:: Deploy クレデンシャルストアは、セキュアなデータベース保持アカウントのクレデンシャルです。主に、新しいクラスタの作成時にハイパーバイザーホストを登録するために使用されます。詳細については、 _Plan_Section を参照してください。
ストレージ効率:: ONTAP Select では、 FAS アレイや AFF アレイとほぼ同じ Storage Efficiency オプションが提供されます。概念的には、直接接続型ストレージ（ DAS ） SSD を搭載した ONTAP Select （プレミアムライセンスを使用）は、 AFF アレイに似ています。HDD を搭載した DAS と vNAS 構成をすべて FAS アレイと同様に検討してください。この 2 つの構成の主な違いは、 DAS SSD を搭載した ONTAP Select では、インラインアグリゲートレベルの重複排除とアグリゲートレベルのバックグラウンド重複排除がサポートされる点です。残りの Storage Efficiency オプションは、両方の構成で使用できます。
+
--
vNAS のデフォルト構成では、 Single Instance Data Logging （ SIDL ）と呼ばれる書き込み最適化機能が有効になります。ONTAP Select 9.6 以降のリリースでは、バックグラウンドの ONTAP の Storage Efficiency 機能は SIDL を有効にして認定されます。詳細については、「 _Deep Dive 」セクションを参照してください。

--
クラスタの更新:: クラスタの作成後、 ONTAP またはハイパーバイザー管理ツールを使用して、 Deploy ユーティリティ以外でクラスタまたは仮想マシンの設定を変更できます。また、構成を変更する仮想マシンを移行することもできます。この変更が行われた場合、 Deploy ユーティリティは自動的には更新されず、クラスタの状態と同期していない可能性があります。クラスタの更新機能を使用して、 Deploy 構成データベースを更新できます。クラスタの更新は、 Deploy の Web ユーザインターフェイス、 CLI 管理シェル、 REST API を使用して実行できます。
ソフトウェア RAID:: DAS （直接接続型ストレージ）を使用する場合、 RAID 機能は従来、ローカルのハードウェア RAID コントローラを通じて提供されていました。ONTAP Select ノードが RAID 機能を提供する _software raid_ を使用するようにノードを設定することもできます。ソフトウェア RAID を使用する場合、ハードウェア RAID コントローラは不要になります。


[[ontap-select-image-install]]
ONTAP Select イメージのインストール:: Deploy 管理ユーティリティには、 ONTAP Selectの 1 つのバージョンのみが含まれています。含まれるバージョンは、リリース時点で利用可能な最新バージョンです。ONTAPONTAP Selectイメージインストール機能を使用すると、以前のバージョンのONTAP SelectをDeployユーティリティのインスタンスに追加できます。これにより、 ONTAP Selectクラスタの導入時に使用できるようになります。見るlink:task_cli_deploy_image_add.html["詳細については、 ONTAP Select イメージを追加してください"]。



NOTE: ONTAP Select イメージは、 Deploy のインスタンスに含まれている元のバージョンよりも前のバージョンでのみ追加してください。Deployを更新せずに新しいバージョンのONTAP Selectを追加することはできません。

ONTAP Select クラスタの導入後の管理:: ONTAP Select クラスタを導入したら、ハードウェアベースの ONTAP クラスタの場合と同様にクラスタを設定できます。たとえば、 System Manager または標準の ONTAP コマンドラインインターフェイスを使用して、 ONTAP Select クラスタを設定できます。


.関連情報
link:task_cli_deploy_image_add.html["導入するONTAP Selectイメージの追加"]
