---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Selectの大容量階層または容量プールライセンスは、プラットフォームの3つの容量レベルのいずれかで購入できます。これらのライセンスサービスによって、 ONTAP Select を導入するホストの機能が決まります。 
---
= ONTAP Selectのプラットフォームライセンスサービスの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectの大容量階層または容量プールライセンスは、Standard、Premium、PremiumのいずれかのXLレベルで購入できます。これらのライセンスサービスによって、 ONTAP Select を導入するホストの機能が決まります。



== プラットフォームライセンス製品の機能

特定のライセンスサービスでは、ハイパーバイザーホストの機能が次の2つの領域で定義および制限されます。

* インスタンスタイプ（ CPU 、メモリ）
* その他の機能


ライセンスサービスは、 Standard XL から Premium XL まで、機能の昇順で提供されます。一般的に、選択したライセンスオプションは、そのレベルおよび下位レベルすべての機能を付与します。たとえば、 Premium レベルは Premium と Standard の両方の機能を提供します。



== プラットフォームライセンスの提供

プラットフォームライセンスには3種類あります。



=== 標準

標準の機能は次のとおりです。

* スモールインスタンスタイプのみ
* ハードディスクドライブ（ HDD ）のみ
* ローカルハードウェア RAID コントローラのみ
* vNAS




=== Premium サービス

Premium サービスには次の機能があります。

* 小規模または中規模のインスタンスタイプ
* ハードディスクドライブ（HDD）またはソリッドステートドライブ（SSD）
* ローカルハードウェア RAID コントローラまたはソフトウェア RAID
* vNAS
* MetroCluster SDS




=== Premium XL

プレミアム XL は、次の機能を提供します。

* 小規模、中規模、大規模のインスタンスタイプ
* HDD、SSD、NVMeドライブ
* ローカルハードウェア RAID コントローラまたはソフトウェア RAID
* vNAS
* MetroCluster SDS



NOTE: カーネルベースの仮想マシン (KVM) では、大規模インスタンス タイプの使用はサポートされていません。



== プラットフォームライセンス製品のハードウェアサポートの比較

標準、プレミアム、およびプレミアムXLライセンス製品は、幅広いハードウェアおよびソフトウェアをサポートしています。ハードウェアおよびソフトウェアのバージョンの最新情報については、を参照してくださいlink:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]。

[role="tabbed-block"]
====
.コアアイテム
--
[cols="5"30"]
|===


2+| コアアイテムのタイプ 3+| 説明 


2+| ホストプロトコル 3+| NFS、SMB / CIFS、iSCSI、NVMe over TCP 


2+| 導入オプション 3+| シングルノード2ノードクラスタ（HAペア）4ノード、6ノード、または8ノードクラスタ 


2+| サポートされる容量（ノードあたり） 3+| 最大400TBの生データ（ESXiおよびKVM） 
|===
--
.ハードウェア
--
[cols="5"30"]
|===


2+| ハードウェアタイプ 3+| 説明 


2+| インスタンスサイズ | 小規模 | 中 | 大規模 


2+| CPUファミリー | Intel Xeon E5-26xx v3（Haswell）以降 | Intel Xeon E5-26xx v3（Haswell）以降 | Intel Xeon E5-26xx v3（Haswell）以降 


2+| ONTAP Select CPU/メモリ | 仮想CPU（vCPU）×4 / 16GBのRAM | vCPU×8 / RAM×64GB | vCPU×16 / RAM×128GB 


2+| ホストのCPU /メモリの最小要件^1^ | 6コア/ 24GBのRAM | 10コア/ 72GBのRAM | 18コア/ 136GB RAM 


2+| ネットワーク（ノードあたり） 3+| シングルノードクラスタの場合は最低2つの1GbEポート2ノードクラスタ（HAペア）の場合は最低4つの1GbEポート4ノード、6ノード、または8ノードクラスタの場合は最低2つの10GbEポート 
|===
^1^ハイパーバイザー用に2コアと8Gb RAMを想定しています。

--
.ストレージタイプ
--
次の表に、指定したストレージに必要な最小ライセンスタイプを示します。 

[cols="5"30"]
|===


2+| ストレージタイプ 3+| 説明 


2+| ライセンスタイプ | 標準 | Premium サービス | ペミウムXL 


2+| インスタンスサイズ | 小規模 | 小規模および中規模 | 小規模、中規模、大規模 


2+| ハードウェアRAIDコントローラを搭載したローカルDAS | 8~60ドライブ | 8~60ドライブ | 8~60ドライブ 


2+| HDD（SAS、NL-SAS、SATA） | 該当なし | 4~60台のドライブ | 4~60台のドライブ 


2+| SSD（SAS） | 該当なし | 4~60ドライブ（SSDのみ） | 4~60ドライブ（SSDのみ） 


2+| ソフトウェアRAIDを使用したローカルDAS | 該当なし | 該当なし | ドライブ×4~14本（NVMeのみ） 


2+| 外付けアレイ^1^ 3+| 外付けアレイでホストされているデータストアがFC、FCoE、iSCSI、およびNFS経由で接続されている（KVMではNFSはサポートされていません）。これらのデータストアは、高可用性と耐障害性を提供します。 
|===
^1^外部アレイプロトコルのサポートには、ネットワークストレージの接続性が反映されています。

--
.ソフトウェア
--
[cols="5"30"]
|===


2+| ソフトウェアタイプ 3+| 説明 


2+| ハイパーバイザーのサポート（VMware） 3+| VMware vSphere 8.0GA およびアップデート 1 ～ 3、VMware vSphere 7.0GA およびアップデート 1 ～ 3C 


2+| ハイパーバイザーのサポート（KVM） 3+| Red Hat Enterprise Linux 64 ビット (KVM) 9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7、および 8.6 Rocky Linux (KVM) 9.6 9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7、および 8.6 


2+| 管理ソフトウェア 3+| NetApp Active IQ Unified Manager管理スイートONTAP Select導入ユーティリティSnapCenter（オプション） 
|===
--
====
.関連情報
link:concept_lic_production.html["大容量階層と容量プールのライセンスタイプについて"]です。
