---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: 購入を決定する前に ONTAP Select を評価したい場合は、評価用ライセンスを使用できます。評価用ライセンスは ONTAP Select Deploy 管理ユーティリティに含まれており、評価用導入の一環として各 ONTAP Select ノードに自動的に適用されます。 
---
= 評価用ライセンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
購入を決定する前に ONTAP Select を評価したい場合は、評価用ライセンスを使用できます。評価用ライセンスは ONTAP Select Deploy 管理ユーティリティに含まれており、評価用導入の一環として各 ONTAP Select ノードに自動的に適用されます。



== ライセンスの特性

ONTAP Select 評価用ライセンスには次のような特徴があります。

* ストレージ容量を含む本番環境ライセンスは必要ありません
* ノードのシリアル番号は 20 桁で、 ONTAP Select Deploy によって自動的に生成されます
+
（ネットアップから直接取得することはありません）。

* ライセンスが提供する評価期間は、最大 90 日です
* 各ノードによって割り当てられる最大ストレージ容量は、本番環境ライセンスと同じです




== 本番環境ライセンスへのアップグレード

ONTAP Select 評価用クラスタは、本番環境ライセンスを使用するようにアップグレードできます。次の制限事項に注意してください。

* ライセンスのアップグレードを実行するには、 Deploy 管理ユーティリティを使用する必要があります
* 大容量階層ライセンスは使用できますが、容量プールのライセンスはサポートされていません
* 各ノードには、クラスタサイズに基づいて、本番環境ライセンスに必要な最小要件を満たす十分なストレージを割り当てる必要があります


を参照してください link:task_adm_licenses.html["評価用ライセンスを本番環境ライセンスに変換する"] を参照してください。
