---
sidebar: sidebar 
permalink: concept_automate_ansible.html 
keywords: ansible, automation, configuration management, ontap, ontap select, na_ots_deploy, na_ots_cluster, ansible roles, ansible playbook 
summary: Ansible のロールを使用して、 ONTAP Select の導入を自動化できます。 
---
= Ansible で ONTAP Select 環境を自動化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ansible のロールとプレイブックを使用して、 ONTAP Select の導入を自動化できます。

Ansible のロールは、標準化されたファイル構造内のタスク、テンプレート、ハンドラ、変数の論理的な集合です。これらのロールを使用して、個別に使用できる機能を促進、再利用、およびモジュール化します。ロールと、そのロールを実行するホストのリストをプレイブックに含めます。Ansible のインストール後、必要なモジュールを更新し、プレイブックを理解したら、 NetApp GitHub から ONTAP Select （ OTS ）ロールをダウンロードして、独自のプレイブックを作成して実行し、 ONTAP Select クラスタを導入することができます。



== ロール

ONTAP Select には次の 2 つのロールがあります。



=== na_ots_deploy

このロールは、 ONTAP Select Deploy のインストールファイルを vCenter または ESXi ホストにダウンロードします。次に、 Deploy VM が作成されて実行されます。

このロールで使用される入力値は次のとおりです。

* vCenter または ESXi ホストのクレデンシャル
* 次のような情報を含む Deploy VM の作成：
+
** IP アドレス
** ホスト名
** ログインします
** パスワード
** データストア
** ネットワーク


* OVA ファイルへのローカルパス
+
インストールファイルが利用可能であることを確認してから、ロールを含むプレイブックを実行してください）。




NOTE: これらの入力値を指定する最も簡単な方法は、グローバル変数ファイルを YML 形式で使用することです。この YML ファイルをプレイブックに渡します。

ロールには、 Deploy OVA ファイルをホストにインポートし、 VM を作成して実行するタスクが 1 つあります。このロールは、 NetApp Ansible GitHub からアクセスしてダウンロードできます。 link:https://github.com/netapp-automation/na_ots_deploy["na_ots_deploy"^]



=== na_ots_ クラスタ

このロールでは、 ONTAP Select Deploy API を使用して ONTAP Select クラスタを作成および導入します。Deploy VM が作成され、手動または * na_ots_deploy * ロールを使用して稼働していることを前提としています。また、 Select ホストに ONTAP Select クラスタに必要なネットワークとストレージが適切に設定されていることを前提としています。

ロールは、 vCenter または ESXi のクレデンシャルの入力値と Deploy VM のクレデンシャルを使用して、 API と、 ONTAP Select クラスタとノード VM の作成に必要なすべての関連情報にアクセスします。

ロールは次のタスクを実行します。

* （ vCenter または ESXi ）ホストのクレデンシャルを追加している
* ホスト ID の取得と登録
* 内部ネットワークの検証（マルチノードクラスタの場合）
* クラスタを作成しています
* ノードの設定
* ネットワークとストレージプールを構成しています
* クラスタを導入する


その結果、クラスタ VM が稼働し、 ONTAP Select クラスタが完全に導入された状態でロールが完了します。このロールは、 NetApp Ansible GitHub からアクセスしてダウンロードできます。 link:https://github.com/NetApp-Automation/na_ots_cluster["na_ots_ クラスタ"^]



== Playbook の例

次に、これらの 2 つの ONTAP Select ロールを呼び出すサンプルのプレイブックを示します。入力変数は YML ファイルで定義され、「 vars_files 」を介して渡されることに注意してください。詳細については、各役割の README ファイルを参照してください。

[listing]
----
—

– name: Create ONTAP Select deploy from OVA (ESXi)

vars_files:

– vars_deploy.yml                              # All Variables

– vars_deploy_pwd.yml                          # host_password & deploy_password

hosts: “{{ target_vcenter_or_esxi_host }}”     # Entry in Ansible ‘hosts’ file

gather_facts: false

connection: ‘local’

roles:

– na_ots_deploy

– name: Create ONTAP Select Cluster

vars_files:

– vars_cluster_test.yml

– vars_cluster_pwd.yml

hosts: “localhost”

gather_facts: false

roles:

– na_ots_cluster

----
上記のロールで ONTAP Select クラスタを作成して実行すると、 ONTAP の機能をさらに自動化するために使用できる豊富な ONTAP Ansible のロールを活用できます。使用可能な ONTAP ロールにはアクセスできます link:https://github.com/NetApp/ansible["こちらをご覧ください"]。要約すると、 ONTAP Select の Ansible のロールと ONTAP のロールを使用して、エンドツーエンドのワークフローを完全に自動化し、 ONTAP Select でストレージを管理できます。
