---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, capacity pools, operation details 
summary: 容量プールのライセンスモデルは容量階層モデルと異なります。ストレージ容量は個々のノードに専用で割り当てるのではなく、プールに割り当てられて複数のノードで共有されます。容量プールモデルをサポートするために、追加のコンポーネントとプロセスが作成されています。 
---
= 運用の詳細
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プールのライセンスモデルは容量階層モデルと異なります。ストレージ容量は個々のノードに専用で割り当てるのではなく、プールに割り当てられて複数のノードで共有されます。容量プールモデルをサポートするために、追加のコンポーネントとプロセスが作成されています。



=== License Manager の略

ライセンスマネージャは、 ONTAP Select Deploy 2.10 を使用して ONTAP Select 9.5 で導入されたソフトウェアコンポーネントです。LM は、 Deploy 管理ユーティリティの各インスタンス内で別々のプロセスとして実行されます。LM で提供される機能には、次のものがあります。

* 容量プールのライセンスのシリアル番号に基づいて、各ノードの一意の 20 桁のシリアル番号を生成します
* ONTAP Select ノードからの要求に基づいて、共有容量プールから容量のリースを作成します
* Deploy ユーザインターフェイスを使用してプールの使用状況をレポートします




=== リース特性

容量プールライセンスを使用するノードで各データアグリゲート用に割り当てられるストレージには、関連付けられたリースが必要です。ノードはストレージリースを要求し、容量が使用可能な場合、 License Manager はリースで応答します。各リースには、次の明示的または暗黙的な属性があります。

* ONTAP Select ノードごとに 1 つの License Manager インスタンスに関連づけられている License Manager
* 容量プール：各 ONTAP Select ノードは 1 つの容量プールに関連付けられます
* ストレージ割り当てリースでは、特定の容量値が割り当てられます
* 有効期限日時リースの期間は、ユーザの設定に応じて 1 時間から 7 日間です。




=== ライセンスロック ID

License Manager の各インスタンス、つまり、対応する Deploy ユーティリティのインスタンスは、一意の 128 ビット番号で識別されます。この番号は、プールを特定の License Manager インスタンス（実質的には Deploy インスタンス）にロックするために、 9 桁の容量プールライセンスシリアル番号と結合されます。ネットアップサポートサイトで NetApp License File （ NLF ）の生成の一環として両方の値を指定する必要があります。

次の方法で Web ユーザインターフェイスを使用して、 Deploy インスタンスのライセンスロック ID を確認できます。

* [ はじめに ] ページこのページは、 Deploy に初めてサインインすると表示されます。ページの右上にあるドロップダウンボックスをクリックして、 [ はじめに ] を選択して、ページを表示することもできます。LLID は [ ライセンスの追加 ] セクションに表示されます。
* 管理ページ上部の * 管理 * タブをクリックし、 * システム * および * 設定 * をクリックします。




=== 基本的なリース操作

ONTAP Select ノードは、データアグリゲートが作成、拡張、または変更されるたびに、有効な容量リースを特定または要求する必要があります。以前の要求から取得したリースがまだ有効である場合は、リースを使用するか、必要に応じて新しいリースを要求できます。ONTAP Select ノードで容量プールのリースを検索するには、次の手順を実行します。

. 既存のリースがノードに存在する場合は、次の条件をすべて満たしていれば使用されます。
+
** リースの期限が切れていません
** アグリゲートのストレージ要求がリース容量を超えていません


. 既存のリースが見つからない場合、ノードは License Manager から新しいリースを要求します。




=== ストレージ容量を容量プールに戻します

ストレージ容量は必要に応じて容量プールから割り当てられ、新しい要求が発生するたびにプール内の使用可能なストレージ容量が少なくなることがあります。ストレージ容量は、次のようないくつかの状況でプールに返されます。

* データアグリゲートのリースは期限切れになり、ノードでは更新されません
* データアグリゲートが削除されました



NOTE: ONTAP Select 仮想マシンが削除された場合、アクティブなリースは有効期限が切れるまで有効です。この場合、容量はプールに返されます。
