---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: ONTAP Select クラスタを導入したら、 ONTAP ソフトウェアの標準のアップグレード手順 を使用して、各ノードの ONTAP イメージを必要に応じてアップグレードできます。 
---
= ONTAP Select ノードをアップグレードします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select クラスタを導入したら、必要に応じて、クラスタ内の各ノードで ONTAP イメージをアップグレードできます。


CAUTION: Deploy 管理ユーティリティを使用して、既存の ONTAP Select ノードのアップグレードを実行することはできません。Deploy ユーティリティは、新しい ONTAP Select クラスタの作成にのみ使用できます。



== General 手順 の略

既存の ONTAP Select ノードをアップグレードするには、以下の手順を実行する必要があります。

. ネットアップサポートサイトのダウンロードページに移動します。
+
https://["ネットアップサポートのダウンロードページ"^]

. ONTAP Select Node Upgrade* をクリックします。
. 必要に応じて、すべてのプロンプトに対応した適切なアップグレードイメージを選択してダウンロードします。
. ONTAP Select ノードをアップグレードする前に、追加情報 リリースノートおよび必要な手順を確認してください。使用しているバージョンの ONTAP Select のリリースノートは、製品ライブラリのページからアクセスできます。
+
https://["ONTAP Select 製品ライブラリ"^]

. ONTAP Select アップグレードファイルを使用して、標準の ONTAP アップグレード手順で ONTAP Select ノードをアップグレードします。
+
https://["ONTAP 9 のドキュメント"^]





== ONTAP Select ノードをリバートする

最初にインストールされているバージョンより前のバージョンに ONTAP Select ノードをリバートすることはできません。例：

ONTAP Select 9.4 が最初にインストールされている:: ノードをバージョン 9.5 にアップグレードしてから、必要に応じてバージョン 9.4 にリバートできます。
ONTAP Select 9.5 が最初にインストールされています:: このバージョンは元々インストールされていたバージョンより前のバージョンであるため、バージョン 9.4 に戻すことはできません。




== VMXNET3 ネットワークドライバを使用する

Deploy 2.10 を使用した ONTAP Select 9.5 以降では、 VMware ESXi での新しいクラスタの導入に付属するデフォルトのネットワークドライバとして VMXNET3 が用意されています。既存の ONTAP Select ノードをバージョン 9.5 にアップグレードした場合、ネットワークドライバは自動的にアップグレードされません。VMXNET3 に手動でアップグレードする必要があります。アップグレードについてサポートが必要な場合は、ネットアップサポートにお問い合わせください。
