---
sidebar: sidebar 
permalink: concept_vpi_vcenter_integration.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter integration 
summary: Deploy プラグインは、 vCenter Server と緊密に統合されています。この統合により、 Deploy ユーティリティと vCenter サーバで管理されるリソース間を簡単に移動できます。この統合の例をいくつか次に示します。 
---
= プラグインと vCenter の統合を導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy プラグインは、 vCenter Server と緊密に統合されています。この統合により、 Deploy ユーティリティと vCenter サーバで管理されるリソース間を簡単に移動できます。この統合の例をいくつか次に示します。



== ONTAP Select クラスタに割り当てられた VMware リソース

ONTAP Select クラスタは、 VMware 上で 1 つ以上のノードのセットとして実行されます。各ノードは、異なる ESXi ホスト上の専用の仮想マシンです。ONTAP Select クラスタには、次の VMware リソースが関連付けられます。

* ホスト
* ONTAP VM
* データストア
* ネットワーク


特定の ONTAP Select クラスタで使用されている VMware リソースを表示するには、いくつかの方法があります。



== プラグインを使用したクラスタのVMwareリソースの表示

ONTAP Select クラスタに割り当てられている VMware リソースは、 Deploy プラグインを使用して表示できます。

.手順
. ブラウザを使用して、 vSphere HTML5 経由で vCenter Server にサインインします。
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで [* ONTAP Select Clusters] をクリックします。
. 右側のリストで目的のクラスタをクリックします。
. [ * その他のオブジェクト * ] タブをクリックし、ページの上部で目的のリソースカテゴリを選択します。
. 追加情報 を表示する特定の VMware リソースを選択します。




== ESXi仮想マシンを介したONTAP Selectクラスタの表示

ONTAP Select 仮想マシンにアクセスすると、クラスタおよび関連するクラスタリソースを表示できます。

.手順
. ブラウザを使用して、 vSphere HTML5 経由で vCenter Server にサインインします。
. 上部の * メニュー * をクリックし、 * VMS and Templates * をクリックします。
. 左側のリストから目的の仮想マシンを選択します。
. [More Objects*] タブをクリックして、 VM で実行されている ONTAP Select クラスタを表示します。
. クラスタに関連付けられている VMware リソースの集合全体を表示するには、 ONTAP Select クラスタをクリックし、 [ その他のオブジェクト *] タブをクリックします。




== ESXiホストでのシングルノードクラスタの作成

vSphere インターフェイスから ESXi ハイパーバイザーホストを選択し、 ONTAP Select シングルノードクラスタを導入できます。

.手順
. ブラウザを使用して、 vSphere HTML5 経由で vCenter Server にサインインします。
. 上部の * メニュー * をクリックし、 * ホストとクラスタ * をクリックします。
. 左側で目的のハイパーバイザーホストを右クリックし、 * ONTAP Select * を選択して、 * New ONTAP Select * をクリックします。
. の手順に従って、導入プロセスを完了します link:task_deploy_cluster.html["ONTAP Select クラスタを導入する"]。

