---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Selectの大容量階層または容量プールライセンスは、プラットフォームの3つの容量レベルのいずれかで購入できます。これらのライセンスサービスによって、 ONTAP Select を導入するホストの機能が決まります。 
---
= ONTAP Selectのプラットフォームライセンスサービスの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectの大容量階層または容量プールライセンスは、Standard、Premium、PremiumのいずれかのXLレベルで購入できます。これらのライセンスサービスによって、 ONTAP Select を導入するホストの機能が決まります。



== プラットフォームライセンス製品の機能

特定のライセンス オファリングによって、次の 2 つの領域におけるハイパーバイザー ホストの機能が決まります。

* インスタンスタイプ（ CPU 、メモリ）
* その他の機能


ライセンスサービスは、 Standard XL から Premium XL まで、機能の昇順で提供されます。一般的に、選択したライセンスオプションは、そのレベルおよび下位レベルすべての機能を付与します。たとえば、 Premium レベルは Premium と Standard の両方の機能を提供します。

次の表は、標準、プレミアム、プレミアム XL ライセンス オファリングの機能を比較したものです。

[cols="25,25,25,25,25"]
|===
2+| ライセンスはサポートされています... | 標準 | Premium サービス | Premium XL 


2+| インスタンスタイプ | 小型のみ | 小または中 | 小、中、大 


.2+| ハードディスクドライブ (HDD) は ... | ハードウェアRAID構成 | はい。 | はい。 | はい。 


| vNAS構成 | はい。 | はい。 | はい。 


.3+| ソリッド ステート ドライブ (SSD) は ... | ハードウェアRAID構成 | いいえ | はい。 | はい。 


| ソフトウェアRAID構成 | いいえ | はい。 | はい。 


| vNAS構成 | はい。 | はい。 | はい。 


.3+| NVMe ドライブは ... | ハードウェアRAID構成 | いいえ | いいえ | はい。 


| ソフトウェアRAID構成 | いいえ | いいえ | はい。 


| vNAS構成 | はい。 | はい。 | はい。 


2+| MetroCluster SDS | いいえ | はい。 | はい。 
|===

NOTE: カーネルベースの仮想マシン (KVM) は、大規模なインスタンス タイプをサポートしていません。



== プラットフォームライセンス製品のハードウェアサポートの比較

標準、プレミアム、プレミアムXLライセンスは、幅広いハードウェアとソフトウェアをサポートしています。ハードウェアとソフトウェアのバージョンに関する最新情報については、link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]をご覧ください。

[role="tabbed-block"]
====
.コアアイテム
--
[cols="5"30"]
|===


2+| コアアイテムのタイプ 3+| 説明 


2+| ホストプロトコル 3+| NFS、SMB / CIFS、iSCSI、NVMe over TCP 


2+| 導入オプション 3+| 単一ノード 2ノードクラスタ（HAペア） 4、6、8、10、または12ノードクラスタ 


2+| サポートされる容量（ノードあたり） 3+| 最大400TBの生データ（ESXiおよびKVM） 
|===
--
.ハードウェア
--
[cols="5"30"]
|===


2+| ハードウェアタイプ 3+| 説明 


2+| インスタンスサイズ | 小規模 | 中 | 大規模 


2+| CPUファミリー | Intel Xeon E5-26xx v3（Haswell）以降 | Intel Xeon E5-26xx v3（Haswell）以降 | Intel Xeon E5-26xx v3（Haswell）以降 


2+| ONTAP Select CPU/メモリ | 仮想CPU（vCPU）×4 / 16GBのRAM | vCPU×8 / RAM×64GB | vCPU×16 / RAM×128GB 


2+| ホストのCPU /メモリの最小要件^1^ | 6コア/ 24GBのRAM | 10コア/ 72GBのRAM | 18コア/ 136GB RAM 


2+| ネットワーク（ノードあたり） 3+| 単一ノード クラスタの場合は 1GbE ポートが最低 2 つ 2 ノード クラスタ (HA ペア) の場合は 1GbE ポートが最低 4 つ 4、6、8、10、または 12 ノード クラスタの場合は 10GbE ポートが最低 2 つ 
|===
^1^ ハイパーバイザーに 2 つのコアと 8 GB の RAM を想定しています。

--
.ストレージタイプ
--
次の表に、指定したストレージに必要な最小ライセンスタイプを示します。 

[cols="5"30"]
|===


2+| ストレージタイプ 3+| 説明 


2+| ライセンスタイプ | 標準 | Premium サービス | Premium XL 


2+| インスタンスサイズ | 小規模 | 小規模および中規模 | 小規模、中規模、大規模 


2+| ハードウェアRAIDコントローラを搭載したローカルDAS | 8~60ドライブ | 8~60ドライブ | 8~60ドライブ 


2+| HDD（SAS、NL-SAS、SATA） | 該当なし | 4~60台のドライブ | 4~60台のドライブ 


2+| SSD（SAS） | 該当なし | 4~60ドライブ（SSDのみ） | 4~60ドライブ（SSDのみ） 


2+| ソフトウェアRAIDを使用したローカルDAS | 該当なし | 該当する | ドライブ×4~14本（NVMeのみ） 


2+| 外付けアレイ^1^ 3+| 外付けアレイでホストされているデータストアがFC、FCoE、iSCSI、およびNFS経由で接続されている（KVMではNFSはサポートされていません）。これらのデータストアは、高可用性と耐障害性を提供します。 
|===
^1^外部アレイプロトコルのサポートには、ネットワークストレージの接続性が反映されています。

--
.ソフトウェア
--
[cols="5"30"]
|===


2+| ソフトウェアタイプ 3+| 説明 


2+| ハイパーバイザーのサポート（VMware） 3+| VMware vSphere 9.0 VMware vSphere 8.0GA およびアップデート 1 ～ 3 VMware vSphere 7.0GA およびアップデート 1 ～ 3C 


2+| ハイパーバイザーのサポート（KVM）  a| 
Red Hat Enterprise Linux 64-bit (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7、および 8.6

Rocky Linux (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7、8.6



2+| 管理ソフトウェア 3+| NetApp Active IQ Unified Manager管理スイートONTAP Select導入ユーティリティSnapCenter（オプション） 
|===
--
====
.次の手順
link:concept_lic_workflow.html["ONTAP Selectライセンスの購入について"]
