---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Capacity Tiersライセンスモデルでは、9桁のノードシリアル番号は、ノードに割り当てられているライセンスシリアル番号と同じです。ただし、容量プールのライセンスモデルを使用してノードに割り当てられるシリアル番号の形式が異なります。 
---
= ONTAP Select Capacity Poolsライセンスモデルのノードシリアル番号
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Capacity Tiersライセンスモデルでは、9桁のノードシリアル番号は、ノードに割り当てられているライセンスシリアル番号と同じです。ただし、容量プールのライセンスモデルを使用してノードに割り当てられるシリアル番号の形式が異なります。

容量プールのライセンスを使用するノードのシリアル番号の形式は次のとおりです。

「 999 ppppppppppppppppp nnnnnnnn 」と入力します


NOTE: わかりやすくするためにスペースが追加されていますが、実際のシリアル番号には含まれていません。

ノードのシリアル番号の各セクションを、左から右の次の表に示します。

[cols="15,85"]
|===
| セクション | 説明 


| '999' | ネットアップが予約した 3 桁の固定値。 


| ppppppppppppp | NetAppによって容量プールに割り当てられる9桁の変数ライセンスシリアル番号 


| nnnnnnnn | 容量プールを使用する各ノードについて、ライセンスマネージャによって生成される8桁の変数の値 
|===

NOTE: 注意：容量プールライセンスを使用するノードに関連してNetAppサポートのケースをオープンする場合、20桁のノードの完全なシリアル番号を指定することはできません。代わりに、9桁の容量プールライセンスのシリアル番号を指定する必要があります。上記のように、ノードのシリアル番号からライセンスのシリアル番号を取得できます。ノードのシリアル番号（ '999' ）の最初の 3 桁をスキップし、次の 9 桁（ ppppppppppp ）を抽出します。
