---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: ONTAP Select クラスタを作成したあと、さまざまな管理タスクを実行して導入をサポートできます。注意が必要な一般的な考慮事項がいくつかあります。 
---
= ONTAP Select の管理を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select クラスタを作成したあと、さまざまな管理タスクを実行して導入をサポートできます。注意が必要な一般的な考慮事項がいくつかあります。

通常、 Deploy の Web インターフェイスを使用して実行できる手順は、 3 つのカテゴリのいずれかに分類されます。

.ONTAP Select クラスタを導入する
シングルノードクラスタまたはマルチノードクラスタを導入できます。を参照してください link:task_deploy_cluster.html["ONTAP Select クラスタを導入する"] を参照してください。

.既存の ONTAP Select クラスタを含む手順 を実行します
管理手順は、 _Security_And _Clusters_といった さまざまなカテゴリに分類されています。

.Deploy ユーティリティで手順 を実行します
Deploy に固有の手順がいくつかあります（管理者のパスワードの変更など）。



== ONTAP Selectの管理

ONTAP Select のサポートの一環として、さまざまな管理手順が用意されています。また、 Deploy 管理ユーティリティに固有の手順があります。これらの手順のうち、最も重要なものを以下に示します。通常は、 Deploy の Web ユーザインターフェイスを使用します。


NOTE: また可能です link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["コマンドラインインターフェイスを使用する"] ONTAP Selectを管理します。



== ONTAPの追加設定の実行

ONTAP Select クラスタを導入したら、ハードウェアベースの ONTAP システムの場合と同様にクラスタを設定および管理できます。たとえば、ONTAPシステムマネージャまたはONTAP CLIを使用してONTAP Selectクラスタを設定できます。

.ネットアップクライアントソフトウェア
サポート対象である次のネットアップクライアントソフトウェアを使用して ONTAP Select に接続できます。

* ONTAP システムマネージャ
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation のサポートを利用できます
* SnapCenter
* Virtual Storage Console for VMware vSphere


サポートされているクライアントソフトウェアのバージョンを確認するには、 link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。クライアントソフトウェアが ONTAP 9 をサポートしている場合は、同じバージョンが ONTAP Select でもサポートされます。


NOTE: SnapCenter と対応するプラグインを使用するには、サーバベースのライセンスが必要です。SnapCenter プラグインのストレージシステム単位のライセンスは、現在 ONTAP Select ではサポートされていません。

リストに含まれていないその他のネットアップクライアントソフトウェアは、 ONTAP Select ではサポートされていません。

.使用可能な設定オプション
クラスタの設定時にはいくつかのオプションを使用できます。次に例を示します。

* ネットワーク設定を作成します
* アグリゲートのレイアウト
* データStorage VM（SVM）の作成


.ストレージ容量を含む購入ライセンス
ONTAP Select クラスタの導入の一環として、ストレージ容量を含むライセンスファイルをインストールしない場合は、購入ライセンスを使用して実行するクラスタの猶予期間が終了する前に、ライセンスファイルを入手してインストールする必要があります。

.ミラーされたアグリゲート
Deploy 管理ユーティリティで作成されたデータスペアディスクは、使用可能なデータストアスペース（ Pool0 および Pool1 など）から各 ONTAP Select ノードに作成されます。マルチノードクラスタにデータの高可用性を実装するには、これらのスペアを使用してミラーされたアグリゲートを作成する必要があります。
