---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: Capacity Tiersライセンスモデルでは、9桁のノードシリアル番号は、ノードに割り当てられているライセンスシリアル番号と同じです。ただし、容量プールのライセンスモデルを使用してノードに割り当てられるシリアル番号の形式が異なります。 
---
= ONTAP Select Capacity Poolsライセンスモデルのノードシリアル番号
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Capacity Tiersライセンスモデルでは、9桁のノードシリアル番号は、ノードに割り当てられているライセンスシリアル番号と同じです。ただし、容量プールのライセンスモデルを使用してノードに割り当てられるシリアル番号の形式が異なります。

容量プールのライセンスを使用するノードのシリアル番号の形式は次のとおりです。

「 999 ppppppppppppppppp nnnnnnnn 」と入力します


NOTE: わかりやすくするためにスペースが追加されていますが、実際のシリアル番号には含まれていません。

次の表では、ノード シリアル番号の各セクションを左から右に説明します。

[cols="15,85"]
|===
| セクション | 説明 


| '999' | ネットアップが予約した 3 桁の固定値。 


| ppppppppppppp | NetAppによって容量プールに割り当てられる9桁の変数ライセンスシリアル番号 


| nnnnnnnn | 容量プールを使用する各ノードについて、ライセンスマネージャによって生成される8桁の変数の値 
|===

CAUTION: NetApp サポートに容量プールライセンスを使用するノードに関するケースを開く場合は、9桁の容量プールライセンスのシリアル番号を提供する必要があります。20桁のノード シリアル番号全体を提供することはできません。ノード シリアル番号の最初の3桁（「999」）をスキップし、次の9桁（ppppppppp）を抽出することで、ノード シリアル番号からライセンス シリアル番号を導き出すことができます。
