---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 容量プールのライセンスモデルは、容量階層モデルとは異なります。ストレージ容量は個々のノードに専用で割り当てるのではなく、プールに割り当てられて複数のノードで共有されます。容量プールモデルをサポートするために、追加のコンポーネントとプロセスが作成されました。 
---
= ONTAP Select Capacity Poolsライセンスモデルの処理の詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プールのライセンスモデルは、容量階層モデルとは異なります。ストレージ容量は個々のノードに専用で割り当てるのではなく、プールに割り当てられて複数のノードで共有されます。容量プールモデルをサポートするために、追加のコンポーネントとプロセスが作成されました。



== License Manager の略

License Managerは、Deploy管理ユーティリティの各インスタンス内で個別のプロセスとして実行されます。LM で提供される機能には、次のものがあります。

* 容量プールライセンスのシリアル番号に基づいて、各ノードに一意の20桁のシリアル番号を生成する
* ONTAP Selectノードからの要求に基づいて、共有容量プールから容量のリースを作成
* Deploy ユーザインターフェイスを使用してプールの使用状況をレポートします




== リース特性

容量プールライセンスを使用するノードのすべてのデータアグリゲートに割り当てられるストレージには、リースを関連付ける必要があります。ノードはストレージリースを要求し、容量が使用可能な場合、 License Manager はリースで応答します。各リースには、次の明示的または暗黙的な属性があります。

* License Manager の略
+
すべてのONTAP Selectノードは1つのLicense Managerインスタンスに関連付けられています

* Capacity Pool
+
すべての ONTAP Select ノードは 1 つのキャパシティ プールに関連付けられています

* ストレージ割り当て
+
リースでは特定の容量値が割り当てられます

* 有効期限日時
+
リースの期間は、ユーザー設定に応じて 1 時間から 7 日間になります。





== ライセンスロック ID

License Manager の各インスタンス、つまり、対応する Deploy ユーティリティのインスタンスは、一意の 128 ビット番号で識別されます。この番号と9桁の容量プールライセンスのシリアル番号を組み合わせて、特定のLicense Managerインスタンス（実質的にはDeployインスタンス）にプールをロックします。NetApp Support Siteで NetApp License File （ NLF ）の生成の一環として両方の値を指定する必要があります。

次の方法で Web ユーザインターフェイスを使用して、 Deploy インスタンスのライセンスロック ID を確認できます。

* スタートガイド ページ
+
Deploy に初めてサインインすると、このページが表示されます。ページ右上のドロップダウンボックスを開き、*Getting Started* を選択してこのページを表示することもできます。LLID は「ライセンスの追加」セクションに表示されます。

+
ページ上部の *Administration* タブを選択し、*Systems* と *Settings* を選択します。





== 基本的なリース操作

ONTAP Selectノードは、データ アグリゲートが作成、拡張、または変更されるたびに、有効な容量リースを検索または要求する必要があります。以前の要求で取得した有効なリースを使用することも、必要に応じて新しいリースを要求することもできます。ONTAP Selectノードは、容量プールリースを検索するために、以下の手順を実行します：

. 既存のリースがノードに存在する場合は、次の条件をすべて満たしていれば使用されます。
+
** リースの期限が切れていません
** アグリゲートのストレージ要求がリース容量を超えていません


. 既存のリースが見つからない場合、ノードは License Manager から新しいリースを要求します。




== ストレージ容量を容量プールに戻します。

ストレージ容量は必要に応じて容量プールから割り当てられ、新しい要求を行うたびにプール内の使用可能なストレージを減らすことができます。ストレージ容量は、次のようないくつかの状況でプールに返されます。

* データアグリゲートのリースは期限切れになり、ノードでは更新されません
* データアグリゲートが削除されました



NOTE: ONTAP Select 仮想マシンが削除された場合、アクティブなリースは有効期限が切れるまで有効です。この場合、容量はプールに返されます。
