---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: Representational State Transfer （ REST ）は、分散 Web アプリケーションの作成に使用される形式です。Web サービス API の設計においては、サーバベースのリソースを公開してその状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準が使用されており、 ONTAP Select クラスタの導入と管理のための柔軟な基盤が提供されます。 
---
= 基盤としての REST Web サービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Representational State Transfer （ REST ）は、分散 Web アプリケーションの作成に使用される形式です。Web サービス API の設計においては、サーバベースのリソースを公開してその状態を管理するための一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準が使用されており、 ONTAP Select クラスタの導入と管理のための柔軟な基盤が提供されます。



== アーキテクチャと従来の制約

残りは、博士号の Roy Fielding によって正式にまとめられました https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["失策"] 2000 年に UC アーバインにて。アーキテクチャスタイルは、一連の制約によって定義されます。これらの制約は、全体的に Web ベースのアプリケーションと基盤となるプロトコルを改善します。制約は、ステートレス通信プロトコルを使用するクライアント / サーバアーキテクチャに基づいて、 RESTful Web サービスアプリケーションを確立するものです。



== リソースと状態の表示

リソースは、 Web ベースシステムの基本コンポーネントです。REST Web サービスアプリケーションを作成する場合、設計の早い段階で次の作業を行います。

* すべてのシステムが使用するシステムまたはサーバベースのリソースを識別し、リソースを維持します。リソースには、ファイル、ビジネストランザクション、プロセス、管理エンティティなどがあります。REST Web サービスに基づいてアプリケーションを設計する際に行う最初の作業の 1 つは、リソースを識別することです。
* リソースの状態の定義と関連する状態処理リソースは、常に有限数の状態のいずれかになります。状態、および状態の変化に影響する関連操作を明確に定義する必要があります。


クライアントとサーバの間でメッセージを交換しながら、一般的な CRUD （ Create 、 Read 、 Update 、 Delete ）モデルに従ってリソースにアクセスしてその状態を変更します。



== URI エンドポイント

すべての REST リソースは、明確に定義されたアドレス指定方式を使用して定義および使用可能にする必要があります。リソースが置かれているエンドポイントは、 Uniform Resource Identifier （ URI ）で識別されます。URI は、ネットワーク内の各リソースに一意の名前を作成するための一般的なフレームワークです。Uniform Resource Locator （ URL ）は、リソースを識別してアクセスするために Web サービスで使用される URI の一種です。リソースは通常、ファイルディレクトリに似た階層構造で公開されます。



== HTTP メッセージ

Hypertext Transfer Protocol （ HTTP ）は、 Web サービスのクライアントとサーバがリソースに関する要求と応答のメッセージを交換する際に使用するプロトコルです。Web サービスアプリケーションの設計の一環として、 HTTP 動詞（ GET や POST など）はリソースおよび対応する状態管理アクションにマッピングされます。

HTTP はステートレスです。したがって、関連する一連の要求と応答を 1 つのトランザクションで関連付けるには、要求 / 応答のデータフローで伝送される HTTP ヘッダーに追加情報 を含める必要があります。



== JSON 形式

クライアントとサーバの間で情報を構造化して転送する方法は複数ありますが、最も広く使用されている方法（ Deploy REST API で使用）は JavaScript Object Notation （ JSON ）です。JSON は、単純なデータ構造をプレーンテキストで表すための業界標準であり、リソースについての状態情報の転送に使用されます。
