---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 内部および外部の ONTAP Select ネットワークの特性。 
---
= ONTAP Selectの内部ネットワークと外部ネットワーク
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の内部ネットワークと外部ネットワークの特性。



== ONTAP Select の内部ネットワーク

内部ONTAP Selectネットワークは、製品のマルチノード版にのみ存在し、ONTAP Selectクラスタにクラスタ通信、HAインターコネクト、および同期レプリケーションサービスを提供します。このネットワークには、次のポートとインターフェイスが含まれます：

* * e0c 、 e0d 。 * クラスタネットワーク LIF をホストしています
* * e0e 。 * RSM LIF をホストしています
* * e0f 。 * HA インターコネクト LIF をホストします


このネットワークのスループットとレイテンシは、 ONTAP Select クラスタのパフォーマンスと耐障害性を決定する上で非常に重要です。クラスタのセキュリティを確保し、システムインターフェイスを他のネットワークトラフィックから分離するには、ネットワークの分離が必要です。そのため、このネットワークは ONTAP Select クラスタ専用にする必要があります。


NOTE: Select の内部ネットワークは、アプリケーショントラフィックや管理トラフィックなど、 Select のクラスタトラフィック以外のトラフィックに使用することはできません。ONTAP の内部 VLAN には、他の VM やホストを配置できません。

内部ネットワークを経由するネットワークパケットは、専用の VLAN タグ付きレイヤ 2 ネットワークで処理される必要があります。そのためには、次のいずれかの作業を行います。

* VLAN タグ付きポートグループを内部仮想 NIC （ e0c~e0f ）（ VST モード）に割り当てる
* アップストリームのスイッチが提供する、他のどのトラフィックにも使用されないネイティブ VLAN を使用する（ VLAN ID なしのポートグループ、つまり EST モードを割り当て）


いずれの場合も、内部ネットワークトラフィックに対する VLAN タギングは ONTAP Select VM の外部で実行されます。


NOTE: ESXi標準および分散vSwitchesのみがサポートされています。その他の仮想スイッチまたはESXiホスト間の直接接続はサポートされていません。内部ネットワークは完全にオープンである必要があります。NATまたはファイアウォールはサポートされていません。

ONTAP Selectクラスタ内では、ポートグループと呼ばれる仮想レイヤ2ネットワークオブジェクトを使用して、内部トラフィックと外部トラフィックが分離されます。これらのポート グループの vSwitch への正しい割り当ては、特にクラスタ、HA 相互接続、およびミラー レプリケーション サービスを提供する内部ネットワークにとって非常に重要です。これらのネットワークポートへのネットワーク帯域幅が不十分だと、パフォーマンスが低下し、クラスタノードの安定性にも影響する可能性があります。したがって、4 ノード、6 ノード、8 ノード、10 ノード、および 12 ノードのクラスタでは、内部ONTAP Selectネットワークで 10 Gb 接続を使用する必要があります。1 Gb NIC はサポートされていません。ただし、 ONTAP Selectクラスタへの受信データのフローを制限しても、クラスタの信頼性の高い動作には影響しないため、外部ネットワークとのトレードオフが可能です。

2 ノードクラスタでは、 4 ノードクラスタに必要な 2 つの 10Gb ポートの代わりに、 4 つの 1Gb ポートまたは 1 つの 10Gb ポートを使用できます。サーバに 4 つの 10Gb NIC カードを装着できない環境では、内部ネットワーク用に 10Gb NIC カードを 2 つ、外部 ONTAP ネットワーク用に 1Gb NIC を 2 つ使用できます。



=== 内部ネットワークの検証とトラブルシューティング

マルチノード クラスター内の内部ネットワークは、ネットワーク接続チェッカー機能を使用して検証できます。この関数は、 `network connectivity-check start`コマンドを実行するDeploy CLIから呼び出すことができます。

次のコマンドを実行してテストの出力を表示します。

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
このツールは、マルチノード Select クラスタ内の内部ネットワークのトラブルシューティングにのみ役立ちます。このツールは、シングルノード クラスタ（vNAS 構成を含む）、ONTAP Deploy から ONTAP Select への接続、またはクライアント側の接続の問題のトラブルシューティングには使用しないでください。

クラスタ作成ウィザード（ONTAP Deploy UIの一部）には、マルチノード クラスターの作成中に使用できるオプションの手順として内部ネットワーク チェッカーが含まれています。マルチノード クラスターでは内部ネットワークが重要な役割を果たすため、このステップをクラスター作成ワークフローの一部にすると、クラスター作成操作の成功率が向上します。

ONTAP Deploy 2.10 以降では、内部ネットワークで使用される MTU サイズを 7 、 500~9 、 000 に設定できます。また、ネットワーク接続チェッカーを使用して、 MTU サイズを 7 、 500~9 、 000 の範囲でテストすることもできます。デフォルトの MTU 値は、仮想ネットワークスイッチの値に設定されます。VXLAN などのネットワークオーバーレイが環境に存在する場合は、このデフォルト値をより小さい値に置き換える必要があります。



== ONTAP Select 外部ネットワーク

ONTAP Select外部ネットワークは、クラスタによるすべてのアウトバウンド通信を担当するため、シングルノード構成とマルチノード構成の両方に存在します。このネットワークには内部ネットワークのような厳密に定義されたスループット要件はありませんが、管理者はクライアントとONTAP VM間のネットワーク ボトルネックを作らないように注意する必要があります。パフォーマンスの問題がONTAP Selectの問題として誤って特徴付けられる可能性があるためです。


NOTE: 内部トラフィックと同様に、外部トラフィックは vSwitch レイヤ（ VST ）および外部スイッチレイヤ（ EST ）でタグ付けできます。また、 VGT と呼ばれるプロセスで、 ONTAP Select VM 自体が外部トラフィックにタグ付けすることもできます。を参照してください link:concept_nw_data_mgmt_separation.html["データトラフィックと管理トラフィックの分離"] を参照してください。

次の表に、 ONTAP Select の内部ネットワークと外部ネットワークの主な違いを示します。

* 内部ネットワークと外部ネットワークのクイックリファレンス *

[cols="3*"]
|===
| 説明 | 内部ネットワーク | 外部ネットワーク 


| ネットワークサービス | クラスタ HA / IC RAID SyncMirror （ RSM ） | データ管理クラスタ間（ SnapMirror と SnapVault ） 


| ネットワークの分離 | 必須 | 任意。 


| フレームサイズ（ MTU ） | 7 、 500~9 、 000 | 1 、 500 （デフォルト） 9 、 000 （サポート対象） 


| IP アドレスの割り当て | 自動で生成 | ユーザ定義 


| DHCP サポート | いいえ | いいえ 
|===


=== NIC チーミング

高いパフォーマンスとフォールトトレランスに必要な帯域幅と耐障害性を内部ネットワークと外部ネットワークに確保するために、物理ネットワークアダプタのチーミングを推奨します。単一の 10Gb リンクを使用する 2 ノードクラスタ構成がサポートされます。ただし、ネットアップでは、 ONTAP Select クラスタの内部ネットワークと外部ネットワークの両方で NIC チーミングを使用することをベストプラクティスとして推奨しています。



=== MAC アドレスの生成

すべての ONTAP Select ネットワークポートに割り当てられた MAC アドレスは、付属の導入ユーティリティによって自動的に生成されます。このユーティリティは、ネットアップ固有のプラットフォーム専用 OUI （ Organizationally Unique Identifier ）を使用して、 FAS システムとの競合がないことを確認します。その後のノードの導入時に同じアドレスが誤って割り当てられないように、このアドレスのコピーが ONTAP Select インストール VM （ ONTAP Deploy ）の内部データベースに保存されます。ネットワークポートに割り当てられた MAC アドレスを管理者が変更することはできません。
