---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: Deploy vCenter プラグインのインストールと管理には、いくつかの作業が必要です。 
---
= 作業を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy vCenter プラグインのインストールと管理には、いくつかの作業が必要です。



== Deploy の Web ユーザインターフェイスと CLI のどちらを使用するかの判断

ほとんどの場合、 Deploy の Web ユーザインターフェイスは vCenter プラグインを管理する際の最も便利なオプションです。これは、このガイドで説明するオプションです。ただし、 Deploy のコマンドラインインターフェイスを使用してプラグインを管理することもできます。詳細については、 Deploy CLI プロンプトで次のコマンドを入力します。

* 「プラグインを配備しますか ? （サブコマンドには、 install 、 remove 、 show 、および update があります）。
* 「 deploy plugin-packages show 」を参照してください




== すべての管理タスクに共通する準備

管理タスクに関係なく、いくつかの手順を実行する必要があります。一般的な準備作業は次のとおりです。

* 『 Deploy vCenter Plug-in の概要』のセクションをお読みください。
* ONTAP Select Deploy 管理ユーティリティがインストールおよび実行されていることを確認します。詳細については、『 Installation and Cluster Deployment Guide for VMware 』を参照してください。
* アカウントのクレデンシャルを取得します。
+
** 管理者アカウントを導入
** vCenter Server アカウント


* Deploy ユーティリティが vCenter サーバでポート 443 へのネットワークアクセスを許可するようにしてください。


管理タスクによっては、追加の準備が必要になる場合があります。



== vCenter Server アカウントの準備

Deploy プラグインをインストールして使用する前に、必要な権限を持つ vCenter アカウントを作成する必要があります。必要な権限をすべて含むアカウントを 1 つ作成することも、 1 つの権限で複数のアカウントを作成することもできます。次の例では、 vCenter 権限を 3 つの個別のロールに分散し、 3 つのアカウントに割り当てることができます。



==== プラグインへのエンドユーザアクセスを検証しています

vSphere を使用したプラグインへのアクセスを検証するには、アカウントが必要です。このアカウントには、次の vCenter 権限が必要です。 sessions.validate.sessionvCenter でアカウントを作成したら、 Deploy 管理ユーティリティに対して定義する必要があります。Deploy の Web ユーザインターフェイスで、の管理タブをクリックし、クレデンシャルを入力して、 vCenter サーバの場所とクレデンシャルを指定します。

このアカウントは、次の方法で使用されます。

* 指定した vCenter Server がプラグインの登録ダイアログウィンドウのインストールターゲットとして使用できるようになります。
* このアカウントは、 Deploy でプラグインのインストール後に vSphere ユーザがプラグインにアクセスする要求を検証するために使用されます。




==== プラグインの管理

Deploy の Web ユーザインターフェイスでは、プラグインをインストールしてアップグレードまたは削除できます。これらの管理操作のいずれかを実行するたびに、ポップアップウィンドウに vCenter アカウントを入力するように求められます。各管理操作は、個別の vCenter 権限で制御されます。

プラグインをインストール、アップグレード、および削除するには、次の権限を割り当てる必要があります。

* 内線番号
+
** 拡張機能を登録します
** 拡張機能を更新します
** 拡張機能を登録解除します




3 つの権限をすべて設定して 1 つのロールとアカウントを作成することも、必要に応じて複数のアカウントに分割して権限を割り当てることもできます。



==== プラグインへのアクセス

エンドユーザは vSphere からプラグインにアクセスできます。プラグインを使用するアカウントには、次の権限を割り当てる必要があります。

* ネットアップ
+
** ONTAP Select 導入
+
*** 管理者





