---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Select では、 FAS アレイや AFF アレイとほぼ同じ Storage Efficiency オプションが提供されます。 
---
= Storage Efficiency のサポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select では、 FAS アレイや AFF アレイとほぼ同じ Storage Efficiency オプションが提供されます。

オールフラッシュVSANまたは汎用フラッシュアレイを使用するONTAP Select 仮想NAS（vNAS）環境は、SSD以外の直接接続ストレージ（DAS）を使用するONTAP Select のベストプラクティスに従う必要があります。

SSDドライブ搭載のDASストレージとプレミアムライセンスがあれば、新しいインストールでAFFに似たパーソナリティが自動的に有効になります。

AFF に似たパーソナリティがある場合、次のインライン SE 機能がインストール時に自動的に有効になります。

* インラインゼロパターン検出
* ボリュームインライン重複排除
* ボリュームバックグラウンド重複排除
* アダプティブインライン圧縮
* インラインデータコンパクション
* アグリゲートインライン重複排除
* アグリゲートバックグラウンド重複排除


ONTAP Select でデフォルトのすべての Storage Efficiency ポリシーが有効になっていることを確認するには、新しく作成したボリュームで次のコマンドを実行します。

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: 9.6以降からONTAP Select をアップグレードする場合は、Premiumライセンスを持つDAS SSDストレージにONTAP Select をインストールする必要があります。また、ONTAP Deployを使用したクラスタの初回インストール時に、Storage Efficiencyを有効にする*チェックボックスをオンにする必要があります。以前の条件が満たされていない場合に AFF に似たパーソナリティのポスト ONTAP アップグレードを有効にするには、ブート引数を手動で作成し、ノードをリブートする必要があります。詳細については、テクニカルサポートにお問い合わせください。

.ONTAP Select のStorage Efficiency設定
次の表に、メディアタイプとソフトウェアライセンスに応じた、使用可能なStorage Efficiencyオプション、デフォルトで有効、またはデフォルトで無効だが推奨されているStorage Efficiencyオプションを示します。次の表に、環境 ONTAP Select 9.6以降のリリースの情報を示します。以前のリリースについては、の「ONTAP Select Storage Efficiencyのサポート」セクションを参照してください https://www.netapp.com/media/10662-tr4517.pdf["TR-4517"^]。

[cols="4"]
|===
| ONTAP Select の機能 | DAS SSD（プレミアムまたはプレミアムXL ^1 ^） | DAS HDD（すべてのライセンス） | vNAS（すべてのライセンス） 


| インラインゼロ検出 | ○（デフォルト） | ○：ボリューム単位でユーザが有効化 | ○：ボリューム単位でユーザが有効化 


| ボリュームインライン重複排除 | ○（デフォルト） | 使用できません | サポート対象外 


| 32K のインライン圧縮（二次圧縮） | ○：ボリューム単位でユーザが有効化 | ○：ボリューム単位でユーザが有効化 | サポート対象外 


| 8K のインライン圧縮（アダプティブ圧縮） | ○（デフォルト） | ○：ボリューム単位でユーザが有効化 | サポート対象外 


| バックグラウンド圧縮 | サポート対象外 | ○：ボリューム単位でユーザが有効化 | ○：ボリューム単位でユーザが有効化 


| 圧縮スキャナ | はい。 | はい。 | ○：ボリューム単位でユーザが有効化 


| インラインデータコンパクション | ○（デフォルト） | ○：ボリューム単位でユーザが有効化 | サポート対象外 


| コンパクションスキャナ | はい。 | はい。 | サポート対象外 


| アグリゲートインライン重複排除 | ○（デフォルト） | 該当なし | サポート対象外 


| ボリュームバックグラウンド重複排除 | ○（デフォルト） | ○：ボリューム単位でユーザが有効化 | ○：ボリューム単位でユーザが有効化 


| アグリゲートバックグラウンド重複排除 | ○（デフォルト） | 該当なし | サポート対象外 
|===
[size]#^1ONTAP Select 9.6では、新しいライセンス（Premium XL）と新しいVMサイズ（大規模）がサポートされます。ただし、大規模な VM は、ソフトウェア RAID を使用する DAS 構成でのみサポートされます。ハードウェアRAIDとvNAS構成は、9.6リリースの大規模なONTAP Select VMではサポートされません。#

.DAS SSD 構成のアップグレード動作に関する注意事項
ONTAP Select 9.6以降にアップグレードしたら、しばらく待ちます `system node upgrade-revert show` 既存のボリュームのStorage Efficiencyの値を確認する前に、アップグレードが完了したことを示すコマンド。

ONTAP Select 9.6以降にアップグレードされたシステムでは、既存のアグリゲートまたは新たに作成されたアグリゲートに作成された新しいボリュームの動作は、新規の環境で作成されたボリュームと同じです。ONTAP Select コードのアップグレードを実行する既存のボリュームには、新たに作成したボリュームとほとんど同じ Storage Efficiency ポリシーが適用されますが、いくつかのバリエーションがあります。

シナリオ 1:: アップグレード前に、ボリュームのStorage Efficiencyポリシーが有効になっていない場合：
+
--
* 「 space guarantee = volume 」のボリュームでは、インラインデータコンパクション、アグリゲートインライン重複排除、およびアグリゲートバックグラウンド重複排除は有効になりません。これらのオプションは、アップグレード後に有効にできます。
* 'space guarantee =none' のボリュームでは ' バックグラウンド圧縮が有効になっていませんこのオプションは、アップグレード後に有効にできます。
* 既存のボリュームの Storage Efficiency ポリシーは、アップグレード後に auto に設定されます。


--
シナリオ 2:: アップグレード前に、ボリュームのStorage Efficiencyがすでに有効になっている場合：
+
--
* アップグレード後に 'space guarantee = volume が指定されたボリュームに違いはありません
* 'space guarantee =none' のボリュームでは、アグリゲートバックグラウンド重複排除がオンになっています。
* 「 storage policy inline-only 」が指定されたボリュームのポリシーは auto に設定されています。
* ユーザ定義のストレージ効率化ポリシーが設定されたボリュームは、「スペースギャランティ = none 」が設定されたボリュームを除き、ポリシーに変更はありません。このボリュームでは、アグリゲートバックグラウンド重複排除が有効になっています


--


.DAS HDD 構成のアップグレード動作に関する注意事項
アップグレード前に有効にしたStorage Efficiency機能は、ONTAP Select 9.6以降にアップグレードしたあとも保持されます。アップグレード前に Storage Efficiency が有効になっていなかった場合は、アップグレード後も Storage Efficiency は有効になりません。
