---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: 購入を決定する前に ONTAP Select を評価したい場合は、評価用ライセンスを使用できます。評価用ライセンスは ONTAP Select Deploy 管理ユーティリティに含まれており、評価用導入の一環として各 ONTAP Select ノードに自動的に適用されます。 
---
= ONTAP Select環境用の評価ライセンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectは、評価用ライセンスまたは購入ライセンスを使用して導入できます。選択するライセンスは、ONTAP Selectクラスタ内の各ノード、つまりクラスタ全体に適用する必要があります。購入を決定する前に ONTAP Select を評価したい場合は、評価用ライセンスを使用できます。評価用ライセンスは ONTAP Select Deploy 管理ユーティリティに含まれており、評価用導入の一環として各 ONTAP Select ノードに自動的に適用されます。

[NOTE]
====
ONTAP Select Deploy管理ユーティリティをダウンロードするには、次のものが必要です。

* NetAppサポートサイトの登録アカウント。アカウントをお持ちでない場合は、を参照してください https://mysupport.netapp.com/site/user/registration["ユーザ登録"^]。
* 評価用ライセンスがあるONTAP Select環境の場合は、に移動し https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["エンドユーザライセンス契約に同意します。"^]ます。


====
評価用クラスタを導入してサポートする場合は、いくつかの考慮事項があります。

* クラスタは評価目的でのみ使用できます。本番環境では、評価用ライセンスのあるクラスタを使用しないでください。
* 各ホストを設定するときは、ONTAP Select Deploy管理ユーティリティを次のように使用する必要があります。
+
** シリアル番号を指定しない
** 評価用ライセンスを使用するように構成






== ライセンスの特性

ONTAP Select 評価用ライセンスには次のような特徴があります。

* ストレージ容量を含む本番環境ライセンスは不要
* ノードのシリアル番号は 20 桁で、 ONTAP Select Deploy によって自動的に生成されます
+
（NetAppから直接取得するわけではありません）

* ライセンスが提供する評価期間は、最大 90 日です
* 各ノードによって割り当てられる最大ストレージ容量は、本番環境ライセンスと同じです




== 本番環境ライセンスへのアップグレード

ONTAP Select 評価用クラスタは、本番環境ライセンスを使用するようにアップグレードできます。次の制限事項に注意してください。

* ライセンスのアップグレードを実行するには、 Deploy 管理ユーティリティを使用する必要があります
* 大容量階層ライセンスは使用できますが、容量プールライセンスはサポートされません。
* 各ノードには、クラスタサイズに基づいて、本番環境ライセンスに必要な最小要件を満たす十分なストレージを割り当てる必要があります


を参照してください link:task_adm_licenses.html["評価用ライセンスを本番環境ライセンスに変換する"] を参照してください。

.関連情報
link:deploy-evaluation-ontap-select-ovf-template.html["ONTAP Selectクラスタの90日間の評価用インスタンスを導入"]
