---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, capacity pools, restrictions 
summary: 容量プールライセンスモデルを使用する場合の制限事項を次に示します。 
---
= 容量プールのライセンスに関する導入の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プールライセンスモデルを使用する場合の制限事項を次に示します。

.クラスタごとに統一されたライセンスモデル
1 つの ONTAP Select クラスタ内のすべてのノードで、同じライセンスモデル、つまり容量階層または容量プールを使用する必要があります。1 つのクラスタ内で複数のノードのライセンスタイプを混在させることはできません。

.クラスタ内のすべてのノードが同じ License Manager インスタンスを使用します
ONTAP Select クラスタ内の容量プールライセンスを持つすべてのノードは、同じ License Manager インスタンスを使用する必要があります。各 Deploy インスタンスには 1 つの License Manager インスタンスが存在するため、この制限は、クラスタ内のすべてのノードを同じ Deploy インスタンスで管理する必要があるという既存の要件を再定義したものです。

.ノードごとに 1 つの容量プール
各ノードは、 1 つの容量プールからのみストレージをリースできます。1 つのノードで複数のプールを使用することはできません。

.HA ペアのノードに同じプール
単一の HA ペアの両方のノードは、同じ容量プールからストレージをリースする必要があります。ただし、同じクラスタ内の異なる HA ペアは、同じ License Manager で管理されている異なるプールからストレージをリースできます。

.ストレージライセンスの期間
ネットアップからストレージライセンスを取得するときは、ライセンス期間を選択する必要があります。たとえば、ライセンスは 1 年間有効です。

.データアグリゲートのリース期間
ONTAP Select ノードがデータアグリゲートのストレージリースを要求すると、 License Manager は容量プールの設定に基づいて、特定の期間のリースを提供します。各プールのリース期間は、 1 時間から 7 日の間で設定できます。デフォルトのリース期間は 24 時間です。

.Deploy に割り当てられた静的 IP アドレス
容量プールのライセンスを使用する場合は、 Deploy 管理ユーティリティに静的 IP アドレスを割り当てる必要があります。
