---
sidebar: sidebar 
permalink: concept_vpi_overview.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, overview, functionality 
summary: ONTAP Select Deploy 用の VMware vCenter プラグインは、 VMware 環境で作業する ONTAP Select 管理者向けに設計されています。標準の Deploy ユーザインターフェイスの代わりに使用できます。 
---
= Deploy vCenter プラグインの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 用の VMware vCenter プラグインは、 VMware 環境で作業する ONTAP Select 管理者向けに設計されています。標準の Deploy ユーザインターフェイスの代わりに使用できます。



== Deploy に同梱

Deploy vCenter プラグインは、 Deploy 管理ユーティリティに付属しています。Deploy のユーザインターフェイスを使用してプラグインを vCenter Server にインストールしたら、 vSphere Web インターフェイスからプラグインにアクセスできます。



== VMware との統合

多くの企業にとって、 VMware vCenter は、仮想化されたデータセンターとクラウドリソースを管理するための中央プラットフォームです。Deploy プラグインは vCenter と緊密に統合されているため、管理者は ONTAP Select ドメインと vCenter ドメインをすばやく移動して、さまざまなリソース間の関係を活用できます。



== Deploy vCenter プラグインが提供する機能

Deploy vCenter プラグインをインストールしたあと、「グローバルインベントリリスト」ペインの vSphere で 2 つの主要オプションを使用できます。



=== ONTAP Select クラスタ

ONTAP Select クラスタオプションは、標準の Deploy Web ユーザインターフェイスの * クラスタ * タブとほぼ同じです。次の表に、このストレージシステムに搭載されている機能を示します。

[cols="30,70"]
|===
| 実行する処理 | 方法 


| ONTAP Select クラスタを導入する | 新規 ONTAP Select をクリックします。 


| クラスタの詳細を表示します | クラスタを選択し、概要をクリックして、詳細をクリックします。 


| クラスタのイベントメッセージを表示します | クラスタを選択し、概要をクリックして、イベントをクリックします。 


| クラスタをオンラインまたはオフラインにするか、クラスタを削除します | クラスタを選択し、 Actions （アクション）をクリックして、目的のアクションをクリックします。 


| System Manager を起動します | クラスタを選択し、概要をクリックして詳細をクリックし、 System Manager の起動をクリックします。 


| クラスタで使用されている ESXi ホストを表示する | クラスタを選択し、 [ その他のオブジェクト ] をクリックして、 [ ホスト ] をクリックします。詳細およびその他の操作を表示するには、ホストを選択してください。 


| クラスタで使用されている ONTAP VM を表示します | クラスタを選択し、 More Objects をクリックして、 ONTAP VMs をクリックします。詳細やその他の操作を確認するには、 VM を選択してください。 


| クラスタで使用されているデータストアを表示します | クラスタを選択し、 [ その他のオブジェクト ] をクリックして、 [ データストア ] をクリックします。データストアを選択すると、詳細やその他の操作が表示されます。 


| クラスタで使用されているネットワークを表示する | クラスタを選択して [ その他のオブジェクト ] をクリックし、 [ ネットワーク ] をクリックします。ネットワークを選択すると、詳細やその他の操作が表示されます。 
|===


=== ONTAP Select 導入

ONTAP Select Deploy オプションは、標準の Deploy Web ユーザインターフェイスの「 * Hypervisor Hosts * 」タブと「 * Administration * 」タブに相当します。次の表で説明するように、ページ上部の 3 つのタブを使用して機能を実行できます。

[cols="15,85"]
|===
| タブをクリックする | 説明 


| まとめ | ホスト名や IP アドレスなど、 Deploy インスタンスの特性について説明します。 


| ホスト | ONTAP Select Deploy に登録されている ESXi ホストに関する情報が表示されます。ホストを追加または削除できます。 


| 管理 | Deploy ユーティリティを使用して管理タスクを実行できます。この機能は、 ONTAP Select Deploy の標準のユーザインターフェイスに相当します。ただし、プラグインで * Credentials * オプションと * Plugins * オプションが使用できない点が異なります。 
|===


== vCenterプラグインとDeployの標準ユーザインターフェイスの比較

vSphere 経由で vCenter プラグインに付属する機能は、標準の Deploy ユーザインターフェイスに相当します。ただし、プラグインには付属していない機能がいくつかあり、 Deploy のユーザインターフェイスでのみ使用できます。



=== vCenterプラグインの管理

vCenter プラグインを使用して vCenter プラグインをインストール、更新、削除、または確認することはできません。これらの管理タスクは、ネイティブの Deploy ユーザインターフェイスを使用して実行する必要があります。



=== vCenterクレデンシャルの管理

vCenter プラグインをインストールする前に、標準の Deploy ユーザインターフェイスを使用して、 Deploy に必要な vCenter クレデンシャルを追加する必要があります。



=== ONTAP Select クラスタは、同じ vCenter サーバで制御されている必要があります

ONTAP Select クラスタの導入とサポートは、プラグインがインストールされている単一の vCenter サーバでのみ実行できます。このプラグインを使用して、スタンドアロンの ESXi または KVM ホストで実行されている他の vCenter サーバまたはクラスタで管理されている ONTAP Select クラスタにアクセスすることはできません。
