---
sidebar: sidebar 
permalink: concept_api_before_browser.html 
keywords: rest api, deploy rest api, rest, access browser, before you begin 
summary: Deploy のオンラインドキュメントページを使用する前に、いくつかの点に注意する必要があります。 
---
= ブラウザから API にアクセスする前に
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy のオンラインドキュメントページを使用する前に、いくつかの点に注意する必要があります。



=== 導入計画

特定の導入タスクまたは管理タスクを実行する際に問題 API 呼び出しを行う場合は、導入計画を作成することを検討してください。これらのプランは正式なプランでも非公式なプランでもあり、通常は目標と使用する API 呼び出しが含まれています。詳細については、 Deploy REST API を使用したワークフロープロセスを参照してください。



=== JSON の例とパラメータの定義

各 API 呼び出しについて、ドキュメントページで一貫した形式で説明しています。このコンテンツには、実装メモ、クエリパラメータ、および HTTP ステータスコードが含まれます。また、 API の要求と応答で使用される JSON に関する詳細を次のように表示することもできます。

* 値の例 API 呼び出しで _example value_on をクリックすると、呼び出しの典型的な JSON 構造が表示されます。この例は必要に応じて変更でき、要求の入力として使用できます。
* モデル (Model) - モデル (_Model_) をクリックすると 'JSON パラメータの完全なリストが表示され ' 各パラメータの概要 が表示されます




=== API 呼び出しを実行する際の注意事項

Deploy のドキュメントページを使用して実行する API 処理は、すべてライブ処理です。構成ファイルやその他のデータを誤って作成、更新、削除しないように、注意してください。
