---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: ONTAP Select クラスタを作成したあと、さまざまな管理タスクを実行して導入をサポートできます。注意が必要な一般的な考慮事項がいくつかあります。 
---
= ONTAP Select の管理を開始する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select クラスタを作成したあと、さまざまな管理タスクを実行して導入をサポートできます。注意が必要な一般的な考慮事項がいくつかあります。



== 作業を開始する前に

通常、 Deploy の Web インターフェイスを使用して実行できる手順は、 3 つのカテゴリのいずれかに分類されます。

.ONTAP Select クラスタを導入する
シングルノードクラスタまたはマルチノードクラスタを導入できます。を参照してください link:task_deploy_cluster.html["ONTAP Select クラスタの導入"] を参照してください。

.既存の ONTAP Select クラスタを含む手順 を実行します
管理手順は、 _Security_And _Clusters_といった さまざまなカテゴリに分類されています。

.Deploy ユーティリティで手順 を実行します
Deploy に固有の手順がいくつかあります（管理者のパスワードの変更など）。



== ONTAP Select の管理

ONTAP Select のサポートの一環として、さまざまな管理手順が用意されています。また、 Deploy 管理ユーティリティに固有の手順があります。これらの手順のうち、最も重要なものを以下に示します。通常は、 Deploy の Web ユーザインターフェイスを使用します。管理プロセスは、 1 つのステップバイステップタスクまたは複数のタスクのシーケンスで構成できます。


NOTE: コマンドラインインターフェイスを使用して ONTAP Select を管理することもできます。詳細については、「 CLI_ の使用」を参照してください。



== 追加の ONTAP 設定を実行しています

ONTAP Select クラスタを導入したら、ハードウェアベースの ONTAP システムの場合と同様にクラスタを設定および管理できます。たとえば、 OnCommand システムマネージャまたは ONTAP CLI を使用して、 ONTAP Select クラスタを設定できます。

.ネットアップクライアントソフトウェア
サポート対象である次のネットアップクライアントソフトウェアを使用して ONTAP Select に接続できます。

* OnCommand システムマネージャ
* OnCommand Unified Manager の略
* OnCommand パフォーマンスマネージャ
* OnCommand Insight
* OnCommand Workflow Automation のサポートを利用できます
* SnapCenter
* Virtual Storage Console for VMware vSphere


クライアントソフトウェアのサポート対象のバージョンを特定するには、 _NetApp Interoperability Matrix Tool _ を参照してください。クライアントソフトウェアが ONTAP 9 をサポートしている場合は、同じバージョンが ONTAP Select でもサポートされます。


NOTE: SnapCenter と対応するプラグインを使用するには、サーバベースのライセンスが必要です。SnapCenter プラグインのストレージシステム単位のライセンスは、現在 ONTAP Select ではサポートされていません。

リストに含まれていないその他のネットアップクライアントソフトウェアは、 ONTAP Select ではサポートされていません。

.使用可能な設定オプション
クラスタの設定時にはいくつかのオプションを使用できます。次に例を示します。

* ネットワーク設定を作成します
* アグリゲートのレイアウト
* データ Storage Virtual Machine （ SVM ）の作成


.ストレージ容量を含む購入ライセンス
ONTAP Select クラスタの導入の一環として、ストレージ容量を含むライセンスファイルをインストールしない場合は、購入ライセンスを使用して実行するクラスタの猶予期間が終了する前に、ライセンスファイルを入手してインストールする必要があります。

.ミラーされたアグリゲート
Deploy 管理ユーティリティで作成されたデータスペアディスクは、使用可能なデータストアスペース（ Pool0 および Pool1 など）から各 ONTAP Select ノードに作成されます。マルチノードクラスタにデータの高可用性を実装するには、これらのスペアを使用してミラーされたアグリゲートを作成する必要があります。
