---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, Capacity Pools, restrictions 
summary: 容量プールライセンスモデルの使用時に適用される制限事項を次に示します。 
---
= ONTAP Select Capacity Poolsのライセンスに関する導入の制限事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プールライセンスモデルの使用時に適用される制限事項を次に示します。

.クラスタごとに統一されたライセンスモデル
単一のONTAP Selectクラスタ内のすべてのノードで、同じライセンスモデル（容量階層または容量プール）を使用する必要があります。1 つのクラスタ内で複数のノードのライセンスタイプを混在させることはできません。

.クラスタ内のすべてのノードが同じ License Manager インスタンスを使用します
ONTAP Selectクラスタ内の容量プールライセンスを持つすべてのノードで、同じライセンスマネージャインスタンスを使用する必要があります。各 Deploy インスタンスには 1 つの License Manager インスタンスが存在するため、この制限は、クラスタ内のすべてのノードを同じ Deploy インスタンスで管理する必要があるという既存の要件を再定義したものです。

.ノードあたり1つの容量プール
各ノードは、1つの容量プールからストレージをリースできます。1 つのノードで複数のプールを使用することはできません。

.HA ペアのノードに同じプール
単一のHAペアの両方のノードで、同じ容量プールからストレージをリースする必要があります。ただし、同じクラスタ内の異なる HA ペアは、同じ License Manager で管理されている異なるプールからストレージをリースできます。

.ストレージライセンスの期間
ネットアップからストレージライセンスを取得するときは、ライセンス期間を選択する必要があります。たとえば、ライセンスは 1 年間有効です。

.データアグリゲートのリース期間
ONTAP Selectノードがデータアグリゲートのストレージリースを要求すると、ライセンスマネージャは容量プールの構成に基づいて一定期間リースを提供します。各プールのリース期間は、 1 時間から 7 日の間で設定できます。デフォルトのリース期間は 24 時間です。

.Deploy に割り当てられた静的 IP アドレス
容量プールのライセンスを使用する場合は、Deploy管理ユーティリティに静的IPアドレスを割り当てる必要があります。
