---
sidebar: sidebar 
permalink: concept_vpi_planning.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, planning 
summary: Deploy vCenter プラグインをインストールして使用する前に、プラグインを確実に実行するための準備を行う必要があります。 
---
= vCenter Deployプラグインの使用を計画する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy vCenter プラグインをインストールして使用する前に、プラグインを確実に実行するための準備を行う必要があります。



== ソフトウェア要件

次の表に示すいくつかのソフトウェア要件について考慮する必要があります。

[cols="35,65"]
|===
| ソフトウェア | サポートされているバージョン 


| ONTAP Select Deploy ユーティリティ | 2.11.2 以降 


| VMware vSphere の場合 | 6.5 GA 以降 


| VMware vSphere のユーザインターフェイス | HTML5 （ Flash ベースバージョンはサポートされません） 


| ESXi | 6.5U2 以降 
|===


== クラスタサイズの制限

次の表に示すように、クラスタサイズに関するいくつかの制限事項について考慮する必要があります。

[cols="35,65"]
|===
| 項目 | サポートされる最大数 


| ONTAP Select Deploy クラスタ | 100 


| ノード（仮想マシン） | 1000 


| ホスト | 800 
|===


== vCenter ユーザアカウント用の RBAC 権限

プラグインの管理とアクセスには、複数の vCenter 権限が必要です。これらの権限は、次の 3 つのカテゴリのアクションに対応しています。

* Deploy を使用したプラグインの管理：
+
** をインストールします
** アップグレード
** 取り外します


* vSphere Client を使用してプラグインにアクセスします
* vSphere を使用したプラグインへのユーザアクセスを検証しています


を参照してください link:concept_vpi_manage_before.html#preparing-the-vcenter-server-accounts["vCenter Server アカウントの準備"] を参照してください。



== AutoSupport の制限事項

Deploy vCenter プラグインは、 Deploy 管理ユーティリティ（プラグインの URL を含む）で最小限の使用情報を提供します。ただし、 AutoSupport には、 AutoSupport ビューアで表示できるインストール済みプラグインの表が含まれています。


NOTE: Deploy プラグインを使用して、 vSphere Web Client から AutoSupport パッケージをダウンロードすることはできません。AutoSupport パッケージをダウンロードするには、標準の Deploy インターフェイスを使用する必要があります。



== その他の制限事項

Deploy vCenter プラグインのインストールおよび使用にあたっては、さらにいくつかの制限事項を考慮する必要があります。

* vCenter プラグインの各インスタンスでサポートされる vCenter Server は 1 台だけです。
* リンクモードで設定されている vCenter Server はサポートされません。
* vSphere の Deploy プラグイン GUI には、同じ vCenter サーバで管理される ONTAP Select 仮想マシンを含むクラスタのみが表示されます。スタンドアロンの ESXi ホストおよび KVM ホストで実行される ONTAP Select クラスタは含まれません。

