---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: ONTAP Select は、ハイパーバイザーの仮想化を通じて提供される特有の柔軟性に基づき、さまざまなタイプのアプリケーションに適しています。 
---
= ビジネスニーズと使用シナリオ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select は、ハイパーバイザーの仮想化を通じて提供される特有の柔軟性に基づき、さまざまなタイプのアプリケーションに適しています。



== 導入

大まかには、ハイパーバイザーホストサーバ上のワークロードに応じて、 2 つの異なる方法で ONTAP Select を導入できます。



=== 専用の導入サービス

専用の導入モデルでは、 ONTAP Select の単一インスタンスをホストサーバで実行します。他の重要な処理は同じハイパーバイザーホストでは実行されません。



=== コロケーション導入

コロケーション導入モデルでは、 ONTAP Select が他のワークロードとホストを共有します。具体的には、追加の仮想マシンが用意されており、通常は各仮想マシンがコンピューティングアプリケーションを実行します。これらのコンピューティングワークロードは、 ONTAP Select クラスタに対してローカルです。このモデルは、アプリケーションと導入の特殊な要件をサポートします。専用の導入モデルと同様に、各 ONTAP Select 仮想マシンは個別の専用ハイパーバイザーホストで実行する必要があります。



== ストレージ

ONTAP Select は、ビジネスニーズに応じてプライマリストレージまたはセカンダリストレージとして使用できます。



=== プライマリストレージ

状況によっては、 ONTAP Select をプライマリストレージプラットフォームとして導入することもできます。これらのタイプの実装は、アプリケーションのワークロードの特性とビジネス目標によって異なります。



=== ディザスタリカバリとセカンダリストレージ

ONTAP Select を使用して、プライマリストレージ機能を強化する追加のストレージを実装できます。追加のストレージは、組織の災害復旧作業やデータバックアップ計画をサポートするために使用できます。



== 開発とテスト

組織内にさまざまなアプリケーションを導入する際に、アプリケーションの開発およびテストのプロセス全体の不可欠な要素として ONTAP Select を使用できます。たとえば、テストの入出力データを格納するために一時ストレージが必要な場合があります。このようなタイプの導入にかかる時間は、アプリケーションの特性と要件によって異なります。
