---
sidebar: sidebar 
permalink: index.html 
summary: ONTAP Select のドキュメントポータルへようこそ。 
---
= ONTAP Select のドキュメント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ONTAP Select は、 VMware ESXi ハイパーバイザーを実行するさまざまなコモディティハードウェアサーバに導入可能な Software-Defined Storage アプライアンスです。柔軟性と拡張性に優れたプライベートクラウドインフラの構築に必要な即応性を提供します。



== 最新情報をご確認ください

* link:reference_new_ots.html["このリリースの新機能"]



NOTE: ONTAP Select 9.10.1 以降、 KVM ハイパーバイザーに新しいクラスタを導入することはできなくなりました。ONTAP Select 9.11.1以降のリリースでは、既存のKVMクラスタおよびホストですべての管理機能を使用できなくなりました。ただし、Take offline機能とdelete機能は除きます。



== 製品ドキュメントをナビゲートする

ONTAP Select 9.12.1は、VMware ESXiに導入できます。このサイトには、VMware ESXiで実行されているONTAP Select 9.12.1、9.11.1、9.10.1、9.9.6.1、9.8、および9.7およびハイパーバイザーに依存しないドキュメント（REST APIなど）が含まれています。

ここでは、の以前のリリースでサポートされている KVM バージョンのリリースノートと製品のドキュメントを示します https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62293["ONTAP Select 製品ライブラリ"^]。



== 詳細情報を入手して、ピアに接続してください

* link:reference_additional_info.html["ヘルプを参照したり、詳細情報を参照したりするには"]

