---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select は、ほとんどのONTAP 機能を完全にサポートしています。ONTAP の機能の多くには、クラスタの導入時に各ノードで自動的にライセンスが付与されます。ただし、一部の機能には個別のライセンスが必要です。 
---
= ONTAP SelectでのONTAP機能のサポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select はほとんどのONTAP機能をサポートしています。クラスタを導入すると、多くのONTAP機能のライセンスが各ノードに自動的に付与されます。ただし、一部の機能には別途ライセンスが必要です。


NOTE: ハードウェア固有の依存関係を持つONTAP 機能は、一般にONTAP Select ではサポートされていません。



== ONTAP の機能はデフォルトで自動的に有効になります

ONTAP Selectでは、次のONTAP機能がサポートされており、デフォルトでライセンスが付与されています。

* Autonomous Ransomware Protection（ARP）（手動更新）
* CIFS
* 重複排除機能と圧縮機能
* FlexCache
* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption （規制対象外の国のみ）
* NFS
* NVMe over TCP
* ONTAP のマルチテナンシー機能
* ONTAP S3
* S3 SnapMirror
* SnapMirror
* SnapMirrorクラウド
* SnapRestore
* SnapVault
* Storage VMディザスタリカバリ（SVM DR）
+

NOTE: ONTAP Selectでは、ソースとデスティネーションの両方としてSVM DRがサポートされ、最大16の関係が確立されます。SVM DRのサポートは、ソースONTAPのバージョン+2の使用に限定されます。たとえば、ONTAP Select 9.12.1ソースは、デスティネーションONTAPバージョン9.12.1、9.13.1、または9.14.1に接続できます。





== 個別にライセンスされるONTAP の機能

デフォルトで有効になっていない次のようなONTAP機能については、別途ライセンスを取得する必要があります。

* FabricPool
* MetroCluster SDS （ ONTAP Select プレミアムライセンスサービス）


[NOTE]
====
* ONTAP Select 9.16.1以前では、 SnapLock Select Enterprise（改ざん防止スナップショットロックを含む）は、link:https://mysupport.netapp.com/site/["NetApp Support Site"^] 。
* SnapLock Compliance はONTAP Selectではサポートされていません。
* StorageGRIDを使用する場合は、FabricPoolライセンスは必要ありません。


====
.関連情報
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["ONTAP Select と ONTAP 9 の比較"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAP のマスターライセンスキー"^]

