---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select は、ほとんどのONTAP 機能を完全にサポートしています。ONTAP の機能の多くには、クラスタの導入時に各ノードで自動的にライセンスが付与されます。ただし、一部の機能には個別のライセンスが必要です。 
---
= ONTAP の機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select は、ほとんどのONTAP 機能を完全にサポートしています。ONTAP の機能の多くには、クラスタの導入時に各ノードで自動的にライセンスが付与されます。ただし、一部の機能には個別のライセンスが必要です。


NOTE: ハードウェア固有の依存関係を持つONTAP 機能は、一般にONTAP Select ではサポートされていません。



== ONTAP の機能はデフォルトで自動的に有効になります

ONTAP Select には次の機能が含まれており、デフォルトでライセンスが付与されています。

* CIFS
* 重複排除機能と圧縮機能
* FlexCache
* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption （規制対象外の国のみ）
* NFS
* NVMe over TCP
* ONTAP のマルチテナンシー機能
* SnapMirror
* SnapRestore
* SnapVault
* Storage VMディザスタリカバリ（SVM DR）
+

NOTE: ONTAP Select 9.12.1以降では、ソースとデスティネーションの両方としてSVM DRがサポートされるようになりました。関係の最大数は16です。SVM DRのサポートは、ソースONTAPのバージョン+2の使用に限定されます。たとえば、ONTAP Select 9.12.1ソースは、デスティネーションONTAPバージョン9.12.1、9.13.1、または9.14.1に接続できます。





== 個別にライセンスされるONTAP の機能

ONTAP 機能がデフォルトで有効になっていない場合は、次のライセンスを別途取得する必要があります。

* Data Availability Service の略
* FabricPool
* MetroCluster SDS （ ONTAP Select プレミアムライセンスサービス）
* ONTAP S3（コストゼロ）
* SnapLock Enterprise（ONTAP SelectではSnapLockコンプライアンスはサポートされていません）
+
** 改ざん防止Snapshotコピー


* SyncMirror （コストゼロ）



NOTE: StorageGRID Webscale を使用するときに FabricPool ライセンスは必要ありません。

.関連情報
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["ONTAP Select と ONTAP 9 の比較"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAP のマスターライセンスキー"^]

