---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: ONTAP Selectに関するよくある質問への回答を見つけます。 
---
= ONTAP Selectに関するFAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select に関するよくある質問とその回答を確認できます。

[NOTE]
====
ONTAP Select 9.14.1以降では、KVMハイパーバイザーのサポートが再開されました。これまでのONTAP Select 9.10.1では、KVMハイパーバイザーへの新しいクラスタの導入がサポートされなくなり、ONTAP Select 9.11.1では、オフラインへの切り替えや削除を除く既存のKVMクラスタとホストの管理がサポートされなくなりました。

====


== 全般

一般的な質問と回答がいくつかあります。

.ONTAP Select DeployとONTAP Select の違いは何ですか。
ONTAP Select Deployは、ONTAP Select クラスタの作成に使用するユーティリティです。現時点では、本番環境クラスタの作成に使用できるのはONTAP Select Deployのみです。また、ONTAP Select Deployを使用して評価用のSelectクラスタを作成し、クライアントが本番環境の実際の手順をテストして文書化できるようにすることもできます。また、ONTAP Select Deployは、評価時に消費されるスペースに十分な容量を持つ適切な大容量階層ライセンスを使用して、評価用クラスタを本番環境のクラスタに変換することもできます。

ONTAP Select Deployは、ONTAP Select のイメージが格納された仮想マシンです。クラスタのインストール時に、ONTAP Select Deployはいくつかのチェックを実施して、ONTAP Select の最小要件が満たされていることを確認します。ONTAP Select Deploy VMとSelectクラスタは別々にアップグレードできます。

.ONTAP Select でパフォーマンス問題 のトラブルシューティングを行うにはどうすればよいですか。
FAS の ONTAP と同様に、 Perfstat ユーティリティを使用してパフォーマンスデータを収集する必要があります。コマンドの例を次に示します。

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.ONTAP Select DeployのSwagger APIページにアクセスする方法を教えてください。
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: API v3 リリースは、以前のバージョンの API と後方互換性がありません。新しいAPI手順を https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["Field Portal"^]。

.ONTAP Select VM は、 VMware またはその他のサードパーティのスナップショットを使用してバックアップできますか。
いいえONTAP Select VM は、 VMware ベースの Snapshot から除外される独立した永続的ドライブを使用します。ONTAP Selectのバックアップ方法としてサポートされているのは、SnapMirrorまたはSnapVaultのみです。

.この FAQ に記載されていない質問について、どこで明確にしていますか。
連絡先 link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"]。



== ライセンス、インストール、アップグレード、およびリバート

ライセンス、インストール、アップグレード、および復元に関するいくつかの質問と回答があります。

.ONTAP Select とONTAP Select Deployは別 々 にアップグレードできますか。
はい。ONTAP Select Deployユーティリティは、ONTAP Select クラスタとは別にアップグレードできます。同様に、SelectクラスタもONTAP Select Deployユーティリティとは別にアップグレードできます。

.FAS クラスタと同じ手順 を使用して ONTAP Select をアップグレードできますか。
はい。 Select クラスタのアップグレード手順 は FAS クラスタのアップグレードと同じですが、 ONTAP Select アップグレードバイナリは FAS のアップグレードバイナリの ONTAP とは別のダウンロードです。

.FAS クラスタと同じ手順 を使用して ONTAP Select をリバートできますか。
はい、 ONTAP Select クラスタのリバート手順 は、 FAS クラスタのリバート手順 とほぼ同じです。ただし、いくつかの違いがあります。

* リバートできるのは、アップグレードされた ONTAP Select インスタンスのみで、元のインストールバージョンのみです。ONTAP Select が以前のリリースをサポートしていても、新しいインストールは古いコードリリースに戻すことはできません。
* ソフトウェアRAIDを使用するONTAP Select（KVM）およびONTAP Select（ESX）では、ソフトウェアRAIDをサポートしていない以前のバージョンに戻すことはできません。さらに、ESXi上のONTAP Select 9.5以降の新規インストールでは、VMXNET3ネットワークドライバーと、可能な場合はvNMVEドライバーが使用されます。これらの新規インストールは、以前のバージョンのONTAP Selectに戻すことはできません。
* ONTAP Select VM も Large インスタンスにアップグレードされている場合 (Premium XL ライセンスを使用)、Large インスタンス機能は以前のバージョンでは使用できないため、9.6 より前のバージョンに戻すことはサポートされません。


.ONTAP MetroCluster SDS には、 Premium ライセンス以上が必要ですか？
はい。

.ONTAP Selectクラスタのネットワーク設定はインストール後に変更できますか。
次のONTAP Selectクラスタ プロパティへの変更は、UI、CLI、または REST API を通じて利用可能なクラスタ更新操作を使用してONTAP Select Deploy によって認識されます。

* ネットワークの設定（ IP アドレス、 DNS 、 NTP 、ネットマスク、ゲートウェイ）
* ONTAP Select クラスタ、ノード名、およびバージョン


次の ONTAP Select VM の変更も認識されます。

* ONTAP Select VM の名前と状態の変更（オンラインやオフラインなど）
* ホストのネットワーク名とストレージプール名が変更された


ONTAP Select Deploy 2.6にアップグレードすると、導入済みだが元の構成からは変更されていないONTAP Select クラスタに対して、これらの変更をサポートできるようになります。つまり、上記のONTAP Select クラスタプロパティがSystem ManagerまたはvCenterを使用して変更された場合、ONTAP Select Deploy 2.6にアップグレードしても、これらの不整合は修正されません。ONTAP Select Deployによって一意のメタデータが各ONTAP Select VMに追加されるようにするには、ONTAP Select プロパティの変更を最初にロールバックする必要があります。

.ONTAP Select Deployのネットワーク設定はインストール後に変更できますか。
Deployインスタンスを環境で実行した後にネットワークの詳細を変更することはサポートされていません。詳細については、ナレッジベースの記事をご覧ください。 link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/Modifying_DNS_configuration_of_ONTAP_Deploy_instance["ONTAP DeployインスタンスのDNS構成の変更"^] 。

.DeployはどのようにしてONTAP Selectライセンスが更新されたことを検出しますか。
方法はすべてのライセンスで同じですが、詳細は容量階層ライセンスと容量プールライセンスのどちらであるかによって異なります。

* ONTAP Select Deployは、NetAppから更新されたライセンスファイルを購入することで、ライセンスとサポート契約が更新されたかどうかを検出します。ライセンスファイル（.nlf）には容量、開始日、終了日が含まれており、 link:https://mysupport.netapp.com/site/["NetApp Support Site"^]をクリックし、Deployサーバで更新します。
+

NOTE: NLFをDeployサーバにロードするには、* Add *および* Update *機能を使用します。*追加*新しいライセンスをサーバに追加し、*更新*は、容量、ノードライセンス（Standard、Premium、Premium XL）、サポートの開始日と終了日（Capacity Tierライセンス）、サブスクリプションの開始日と終了日（Capacity Poolライセンス）などの情報で既存のファイルを更新します。

+

CAUTION: ライセンスファイルは変更しないでください。これにより、セキュリティキーが無効になり、ライセンスが無効になります。

* A *大容量階層ライセンス*は、ONTAP Selectノードのシリアル番号に関連付けられたノード単位の永続的ライセンスです。別のサポート契約で販売されます。ライセンスは永続的ですが、ONTAP SelectのアップグレードにアクセスしてNetAppテクニカルサポートの支援を受けるには、サポート契約を更新する必要があります。容量やノードサイズなどのライセンスパラメータを変更するには、現在のサポート契約も必要です。
+
容量階層ライセンスの更新、パラメータの変更、サポート契約の更新を購入するには、発注時にノードのシリアル番号が必要です。大容量階層ノードのシリアル番号は9桁で、先頭は「32」です。

+
購入が完了し、ライセンスファイルが生成されると、* Update *機能を使用してDeployサーバにアップロードされます。

* 容量プールライセンス*は、特定の容量プールとノードサイズ（Standard、Premium、Premium XL）を使用して1つ以上のクラスタを導入する権利を得るためのサブスクリプションです。サブスクリプションには、指定された期間のライセンスとサポートを使用する権利が含まれます。ライセンスを使用する権利とサポート契約には、開始日と終了日が指定されています。


.Deployは、ノードがライセンスまたはサポート契約を更新したかどうかをどのように検出しますか。
更新されたライセンスファイルの購入、生成、アップロードは、Deployが更新されたライセンスとサポート契約を検出する方法です。

大容量階層のサポート契約の終了日が過ぎている場合、ノードは稼働し続けることはできますが、ONTAPの更新をダウンロードしてインストールすることはできません。また、最初にサポート契約を最新の状態にしないと、NetAppのテクニカルサポートに支援を依頼することもできません。

容量プールサブスクリプションが期限切れになると、最初に警告が表示されますが、30日後にシステムをシャットダウンすると、更新されたサブスクリプションがDeployサーバにインストールされるまでリブートされません。



== ストレージ

ストレージに関するいくつかの質問と回答があります。

.単一のONTAP Select Deployインスタンスで、ESXiとKVMの両方にクラスタを作成できますか。
はい。ONTAP Select DeployはKVMまたはESXにインストールできます。両方のインストール環境で、どちらのハイパーバイザーにもONTAP Select クラスタを作成できます。

.ESX 上の ONTAP Select には vCenter が必要ですか。
ESXiホストが適切にライセンスされている場合、ESXiホストをvCenter Serverで管理する必要はありません。ただし、ホストがvCenter serverで管理されている場合は、ONTAP Select DeployをそのvCenter Serverを使用するように設定する必要があります。つまり、ESXiホストがvCenter Serverによって積極的に管理されている場合、ONTAP Select Deployでスタンドアロンとして設定することはできません。ONTAP Select Deploy VMは、vMotionやVMware HAイベントによるESXiホスト間のすべてのONTAP Select VMの移行を追跡するために、vCenterに依存していることに注意してください。

.ソフトウェア RAID とは
ONTAP Select では、ハードウェアRAIDコントローラなしでサーバを使用できます。この場合、RAID機能はソフトウェアで実装されます。ソフトウェアRAIDを使用する場合は、SSDとNVMeの両方のドライブがサポートされます。ONTAP Select ブートディスクおよびコアディスクは、引き続き仮想化されたパーティション（ストレージプールまたはデータストア）内に配置する必要があります。ONTAP Select は、 RD2 （ルート / データ / データパーティショニング）を使用して SSD をパーティショニングします。したがって、 ONTAP Select ルートパーティションは、データアグリゲートに使用される物理スピンドルと同じ上にあります。ただし、ルートアグリゲートおよびブートディスクとコア仮想ディスクは容量ライセンスには含まれません。

AFF / FAS で使用できるすべての RAID 方式を ONTAP Select でも使用できます。これには、 RAID 4 、 RAID DP 、および RAID-TEC が含まれます。SSD の最小数は、選択した RAID 構成のタイプによって異なります。ベストプラクティスとして、少なくとも 1 つのスペアが必要です。スペアディスクとパリティディスクは容量ライセンスには含まれません。

.ソフトウェア RAID とハードウェア RAID 構成の違いは何ですか。
ソフトウェア RAID は、 ONTAP ソフトウェアスタックのレイヤです。ソフトウェア RAID では、物理ドライブが ONTAP Select VM 内でパーティショニングされ、 raw ディスクとして使用できるため、管理性が向上します。一方、ハードウェア RAID では、通常は 1 つの大きな LUN を使用でき、その LUN を ONTAP Select で使用して VMDISK を作成できます。ソフトウェア RAID はオプションとして使用でき、ハードウェア RAID の代わりに使用できます。

ソフトウェア RAID の要件には、次のものがあります。

* ESXiおよびKVMでサポートされます
+
** ONTAP Select 9.14.1以降では、KVMハイパーバイザーのサポートが再開されました。これまでは、ONTAP Select 9.10.1でKVMハイパーバイザーのサポートが廃止されていました。


* サポートされる物理ディスクのサイズ： 200GB~32TB
* DAS 構成でのみサポートされます
* SSDまたはNVMeでサポートされます
* Premium または Premium XL ONTAP Select ライセンスが必要です
* ハードウェア RAID コントローラがないか無効になっているか、 SAS HBA モードで動作している必要があります
* システムディスクのコアダンプ、ブート / NVRAM 、メディエーターなどに、専用の LUN に基づく LVM ストレージプールまたはデータストアを使用する必要があります。


.ONTAP Select for KVM では複数の NIC ボンドをサポートしていますか。
KVM にインストールするときは、単一のボンドと単一のブリッジを使用する必要があります。物理ポートが 2 つまたは 4 つあるホストでは、すべてのポートを同じボンドに含める必要があります。

.ハイパーバイザーホスト内の障害が発生した物理ディスクまたは NIC について、 ONTAP Select で報告またはアラートを生成する方法を教えてください。ONTAP Select はハイパーバイザーからこの情報を取得しますか、それともハイパーバイザーレベルで監視を設定する必要がありますか？
ハードウェア RAID コントローラを使用する場合、 ONTAP Select は、基盤となるサーバの問題をほとんど認識しません。ベストプラクティスに従ってサーバを設定する場合は、ある程度の冗長性が必要です。ドライブ障害に備えて RAID 5/6 を使用することを推奨します。ソフトウェア RAID 構成の場合、 ONTAP はディスク障害に関するアラートを発行し、スペアドライブがある場合は、ドライブのリビルドを開始します。

ネットワークレイヤでの単一点障害を回避するために、 2 つ以上の物理 NIC を使用する必要があります。ネットアップでは、データポートグループ、管理ポートグループには NIC チーミングとボンディングを設定し、チームまたはボンドに 2 つ以上のアップリンクを使用することを推奨します。このような構成により、アップリンクに障害が発生した場合に、仮想スイッチは、障害が発生したアップリンクから NIC チーム内の正常なアップリンクにトラフィックを移動します。推奨されるネットワーク構成の詳細については、を参照してください link:reference_plan_best_practices.html#networking["ベストプラクティスのまとめ：ネットワーク"]。

2ノードまたは4ノードクラスタの場合、その他のエラーはすべてONTAP HAによって処理されます。ハイパーバイザー サーバを交換し、 ONTAP Selectクラスタを新しいサーバで再構成する必要がある場合は、「 ONTAP Selectノードを回復できますか?」を参照してください。

.ONTAP Selectノードを回復できますか?
ONTAP Select VM またはホストが完全に失われた場合や、単一ノード クラスタが誤って削除された場合など、 ONTAP Selectノードをリカバリする必要がある場合は、 NetAppテクニカル サポートにお問い合わせください。詳細については、ナレッジベースの記事をご覧ください。 link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-KBs/ONTAP_Select_node_VM_recovery_in_case_of_disaster["災害時のONTAP SelectノードVMリカバリ"^] 。

.ONTAP Select でサポートされるデータストアの最大サイズはいくつですか。
VSAN を含むすべての構成で、 ONTAP Select ノードあたり 400TB のストレージがサポートされます。

サポートされる最大サイズを超えるデータストアにインストールする場合は、製品のセットアップ時に容量の上限を使用する必要があります。

.ONTAP Select ノードの容量はどのようにして拡張できますか。
ONTAP Select Deployには、ONTAP Select ノードでの容量拡張処理をサポートするストレージ追加ワークフローが含まれています。管理下でストレージを拡張するには、同じデータストアのスペースを使用するか（使用可能なスペースが残っている場合）、別のデータストアのスペースを追加します。ローカルデータストアとリモートデータストアを同じアグリゲートに混在させることはできません。

ストレージの追加はソフトウェア RAID もサポートします。ただし、ソフトウェア RAID の場合は、 ONTAP Select VM に物理ドライブを追加する必要があります。この場合のストレージ追加は、 FAS または AFF アレイの管理と似ています。ソフトウェア RAID を使用して ONTAP Select ノードにストレージを追加する場合は、 RAID グループのサイズとドライブサイズを考慮する必要があります。

.ONTAP Select は、 VSAN または外付けアレイタイプのデータストアをサポートしますか。
ONTAP Select DeployおよびONTAP Select for ESXiは、ストレージプールにvSANまたは外部アレイタイプのデータストアを使用するONTAP Selectシングルノード クラスタの構成をサポートします。

ONTAP Select DeployおよびONTAP Select for KVMでは、外部アレイで共有論理ストレージプールタイプを使用するONTAP Select シングルノードクラスタの設定がサポートされます。ストレージプールのベースには iSCSI と FC / FCoE があります。それ以外のタイプのストレージプールはサポートされません。

共有ストレージ上のマルチノード HA クラスターがサポートされています。

.ONTAP SelectはvSANまたは一部のHCIスタックを含むその他の共有外部ストレージ上のマルチノードクラスタをサポートしていますか？
外部ストレージを使用するマルチノード クラスタ（マルチノード vNAS）は、ESXi と KVM の両方でサポートされています。同じクラスタ内でのハイパーバイザーの混在はサポートされていません。共有ストレージ上の HA アーキテクチャでは、HA ペアの各ノードにパートナー データのミラー コピーが存在することが依然として前提となります。ただし、マルチノード クラスタには、VMware HA または KVM Live Motion に依存するシングルノード クラスタとは対照的に、ONTAP の無停止運用という利点があります。

ONTAP Select Deployは同じホスト上の複数のONTAP Select VMをサポートしますが、クラスタ作成時にそれらのインスタンスが同じONTAP Selectクラスタの一部になることはできません。ESXi環境の場合、NetAppはVMアンチアフィニティルールを作成して、VMware HAが同じONTAP Selectクラスタの複数のONTAP Select VMを単一のESXiホストに移行しないようにすることを推奨します。さらに、ONTAP Select Deployが管理者（ユーザーが開始した）vMotionまたはONTAP Select VMのライブマイグレーションによって、2つのONTAP Selectノードが同じ物理ホスト上に配置されるなどのベストプラクティス違反が発生したことを検出した場合、ONTAP Select DeployはDeploy UIとログにアラートを投稿します。ONTAP Select DeployがONTAP Select VMの場所を認識する唯一の方法は、クラスタ更新操作の結果としてであり、これはONTAP Select Deploy管理者が開始する必要がある手動操作です。ONTAP Select Deployにはプロアクティブな監視を可能にする機能はなく、アラートはDeploy UIまたはログを通じてのみ表示されます。つまり、このアラートは集中監視インフラストラクチャに転送できません。

.ONTAP Select は、 VMware の NSX VXLAN をサポートしていますか。
NSX-V VXLAN ポート グループがサポートされています。ONTAP MetroCluster SDSを含むマルチノードHAの場合は、VXLANオーバーヘッドに対応するために、内部ネットワークMTUを7500~8900（9000ではなく）に設定してください。内部ネットワークMTUは、クラスタ導入時にONTAP Select Deployで設定できます。

.ONTAP Select は KVM のライブマイグレーションをサポートしていますか。
外部アレイストレージプールで実行される ONTAP Select VM は、 virsh ライブマイグレーションをサポートします。

.VSAN AF に ONTAP Select Premium が必要ですか。
いいえ。外付けアレイ構成と VSAN 構成のどちらがオールフラッシュであるかに関係なく、すべてのバージョンがサポートされます。

.サポートされている VSAN FTT / FTM 設定はどれか？
Select VM は VSAN データストアのストレージポリシーを継承し、 FTT / FTM の設定に制限はありません。ただし、 FTT / FTM の設定によっては、 ONTAP Select VM のサイズがセットアップ時に設定した容量よりも大幅に大きくなる可能性があることに注意してください。ONTAP Select は、セットアップ時に作成される eager-zeroed-thick VMDK を使用します。同じ共有データストアを使用する他の VM への影響を回避するためには、 Select の容量と FTT / FTM の設定から導き出された実際の Select VM のサイズに対応できる十分な空き容量をデータストアに確保することが重要です。

.複数の ONTAP Select ノードが異なる Select クラスタに属している場合、それらのノードを同じホストで実行することはできますか。
vNAS 構成では、同じホスト上の複数の ONTAP Select ノードを vNAS 構成でのみ設定できます。ただし、それらのノードが同じ ONTAP Select クラスタに含まれていない必要があります。この方法は DAS 構成ではサポートされていません。同じ物理ホスト上の複数の ONTAP Select ノードが RAID コントローラへのアクセスで競合するためです。

.10GEポートを1つだけ搭載したホストでONTAP Selectを実行できますか?また、ESXiとKVMの両方で使用できますか?
単一の10GEポートを使用して外部ネットワークに接続できます。ただし、NetAppでは、制約のある小型フォームファクタ環境でのみ使用することを推奨しています。これはESXiとKVMの両方でサポートされています。

.KVM でライブマイグレーションを実行するには、どのような追加プロセスを実行する必要がありますか。
CLVM および Pacemaker （ PC ）コンポーネントは、ライブマイグレーションに参加する各ホストにインストールして実行する必要があります。これは、各ホストで同じボリュームグループにアクセスするために必要です。



== vCenter

VMware vCenterに関するいくつかの質問と回答があります。

.ONTAP Select DeployはどのようにしてvCenterと通信し、どのファイアウォールポートを開く必要がありますか？
ONTAP Select DeployはVMware VIX APIを使用してvCenter、ESXiホスト、またはその両方と通信します。VMwareのドキュメントには、vCenter ServerまたはESXiホストへの初期接続は、TCPポート443でHTTPS/SOAPを使用して行われると記載されています。これは、TLS/SSL経由のセキュアなHTTP用のポートです。次に、TCPポート902のソケットでESXiホストへの接続が開かれます。この接続を介して送信されるデータはSSLで暗号化されます。さらに、ONTAP Select Deployは `PING`コマンドを実行して、指定したIPアドレスで応答するESXiホストがあることを確認します。

ONTAP Select Deployは、次のようにONTAP Select ノードおよびクラスタ管理IPアドレスと通信できる必要もあります。

* Ping
* SSH （ポート 22 ）
* SSL （ポート 443 ）


2ノードクラスタの場合、ONTAP Select Deployはクラスタのメールボックスをホストします。各ONTAP Select ノードは、iSCSI（ポート3260）を使用してONTAP Select Deployにアクセスできる必要があります。

マルチノード クラスタの場合、内部ネットワークは完全にオープンである必要があります（NATまたはファイアウォールなし）。

.ONTAP Select DeployでONTAP Select クラスタを作成するために必要なvCenterの権限はどれですか？
必要な vCenter 権限の一覧については、以下を参照してください。 link:reference_plan_ots_vcenter.html["VMware vCenter サーバ"]。



== HA およびクラスタ

HAペアとクラスタに関するいくつかの質問と回答があります。

.4 ノード、 6 ノード、または 8 ノードのクラスタと 2 ノードの ONTAP Select クラスタの違いは何ですか。
ONTAP Select Deploy VMが主にクラスタの作成に使用される4ノード、6ノード、および8ノードクラスタとは異なり、2ノードクラスタは、HAクォーラム用にONTAP Select Deploy VMを継続的に利用します。ONTAP Select Deploy VMが使用できない場合、フェイルオーバーサービスは無効になります。

.MetroCluster SDS とは
MetroCluster SDS は、ネットアップの MetroCluster ビジネス継続性ソリューションのカテゴリに分類される、低コストの同期レプリケーションオプションです。FASハイブリッド フラッシュ、 AFF、 NetApp Private Storage for Cloud で使用できるNetApp MetroClusterとは異なり、 ONTAP Selectでのみ使用できます。

.MetroCluster SDS と NetApp MetroCluster の違いは何ですか。
MetroCluster SDS は、同期レプリケーション解決策 を提供し、ネットアップの MetroCluster ソリューションに該当します。ただし、主な違いは、サポートされる距離（約 10km と 300km ）と接続タイプ（ FC と IP ではなく IP ネットワークのみがサポート）です。

.2 ノード ONTAP Select クラスタと 2 ノード ONTAP MetroCluster SDS の違いは何ですか。
2 ノードクラスタとは、同じデータセンター内にある 2 つのノードが相互に 300m 以内の範囲にあるクラスタです。一般に、両方のノードには、スイッチ間リンクで接続された同じネットワークスイッチまたは一連のネットワークスイッチへのアップリンクがあります。

2 ノード MetroCluster SDS は、ノードが物理的に分離され（異なる部屋、異なる建物、または異なるデータセンター）、各ノードのアップリンク接続が別々のネットワークスイッチに接続されているクラスタとして定義されます。MetroCluster SDS には専用のハードウェアは必要ありませんが、環境ではレイテンシ（ 5 ミリ秒 RTT と 5 ミリ秒ジッター）と物理距離（ 10km ）の観点から一連の最小要件をサポートする必要があります。

MetroCluster SDS はプレミアム機能であり、 Premium または Premium XL ライセンスが必要です。Premium ライセンスは、中小規模の VM のほか、 HDD および SSD メディアの作成をサポートします。これらの構成はすべてサポートされます。

.ONTAP MetroCluster SDS にはローカルストレージ（ DAS ）が必要ですか。
ONTAP MetroCluster SDS は、あらゆるタイプのストレージ構成（ DAS と vNAS ）をサポートします。

.ONTAP MetroCluster SDS はソフトウェア RAID をサポートしていますか。
はい。ソフトウェア RAID は、 KVM と ESX の両方の SSD メディアでサポートされています。

.ONTAP MetroCluster SDS は、 SSD と回転式メディアの両方をサポートしていますか。
はい。 Premium ライセンスが必要ですが、このライセンスでは、中小規模の VM 、 SSD と回転式メディアの両方がサポートされます。

.ONTAP MetroCluster SDS では、 4 ノード以上のクラスタサイズはサポートされますか。
いいえ。メディエーターを持つ 2 ノードクラスタのみを MetroCluster SDS として設定できます。

.ONTAP MetroCluster SDS の要件は何ですか。
要件は次のとおりです。

* 3つのデータセンター（ONTAP Select Deployメディエーター用に1つ、ノードごとに1つ）。
* 5 ミリ秒 RTT と 5 ミリ秒ジッタ。 ONTAP Select ノード間の最大合計 10 ミリ秒と最大物理距離 10 ミリ秒です。
* ONTAP Select Deployメディエーターと各ONTAP Select ノードの間で125ミリ秒RTT、最小帯域幅5Mbps
* Premium または Premium XL ライセンス。


.ONTAP Select は vMotion または VMware HA をサポートしていますか。
VSAN データストアまたは外付けアレイデータストア（ vNAS 環境）上で実行される ONTAP Select VM は、 vMotion 、 DRS 、 VMware HA 機能をサポートします。

.ONTAP Select は Storage vMotion をサポートしていますか。
ストレージvMotionは、シングルノードおよびマルチノードのONTAP SelectクラスタとONTAP Select Deploy VMを含むすべての構成でサポートされています。ストレージvMotionは、ONTAP SelectまたはONTAP Select Deploy VMを異なるVMFSバージョン間（たとえば、VMFS 5からVMFS 6）で移行するために使用できますが、この使用例に限定されるわけではありません。ベストプラクティスは、ストレージvMotion操作を開始する前にVMをシャットダウンすることです。ONTAP Select Deployは、ストレージvMotion操作が完了した後に次の操作を実行する必要があります：

[listing]
----
cluster refresh
----

NOTE: 異なるタイプのデータストア間のストレージvMotion操作はサポートされていません。つまり、NFSタイプのデータストアとVMFSデータストア間のストレージvMotion操作はサポートされていません。一般的に、外部データストアとDASデータストア間のストレージvMotion操作はサポートされていません。

.ONTAP SelectノードとESXiホスト間のHAトラフィックは、異なるvSwitchおよび/または分離された物理ポート、および/またはESXiホスト間のポイントツーポイントIPケーブルを使用して実行できますか？
これらの構成はサポートされていません。ONTAP Select では、クライアントトラフィックを伝送する物理ネットワークアップリンクのステータスは確認できません。したがって、 ONTAP Select は、 HA ハートビートを使用して、 VM がクライアントとそのピアに対して同時にアクセス可能であることを確認します。物理的な接続が失われると、 HA ハートビートを受信できなくなると、もう一方のノードへの自動フェイルオーバーが実行されます。これは望ましい動作です。

HA トラフィックを別の物理インフラに分離することで、 Select VM はピアと通信できますが、クライアントとは通信できません。これにより、自動 HA プロセスが無効になるため、手動フェイルオーバーが開始されるまではデータを使用できなくなります。



== メディエーターサービス

メディエーターサービスに関するいくつかの質問と回答があります。

.メディエーターサービスとは何ですか？
2ノードクラスタでは、ONTAP Select Deploy VMでHAクォーラムが継続的に利用されます。2ノードのHAクォーラムネゴシエーションに参加するONTAP Select Deploy VMには、メディエーターVMというラベルが付けられます。

.メディエーターサービスはリモートで実行できますか。
はい。2ノードHAペアのメディエーターとして機能するONTAP Select Deployは、500ms RTTのWANレイテンシをサポートします。最小帯域幅は5Mbpsです。

.メディエーターサービスで使用されるプロトコル
メディエータートラフィックはiSCSIで、ONTAP Select ノードの管理IPアドレスから始まり、ONTAP Select DeployのIPアドレスで終端します。2 ノードクラスタを使用している場合、 ONTAP Select ノード管理 IP アドレスに IPv6 を使用することはできません。

.1 つのメディエーターサービスを複数の 2 ノード HA クラスタに使用できますか。
はい。各ONTAP Select Deploy VMは、最大100個の2ノードONTAP Select クラスタの共通のメディエーターサービスとして機能できます。

.導入後にメディエーターサービスの場所を変更することはできますか。
はい。別のONTAP Select Deploy VMを使用してメディエーターサービスをホストすることができます。

.ONTAP Select では、メディエーターを使用するかどうかに関係なく、拡張されたクラスタをサポートしていますか。
ストレッチ HA 導入モデルでは、メディエーターを備えた 2 ノードクラスタのみがサポートされます。
