---
sidebar: sidebar 
permalink: reference_plan_ots_networking.html 
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall 
summary: ONTAP Select を導入する前に、ハイパーバイザーのネットワークを正しく設定する必要があります。 
---
= ネットワークに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select を導入する前に、ハイパーバイザーのネットワークを正しく設定する必要があります。



== 仮想スイッチのオプション

各 ONTAP Select ホストで、外部ネットワークと内部ネットワーク（マルチノードクラスタの場合のみ）をサポートするように仮想スイッチを設定する必要があります。マルチノードクラスタの導入の一環として、内部クラスタネットワーク上のネットワーク接続をテストしてください。


NOTE: ハイパーバイザーホストで vSwitch を設定する方法と、高速インターフェイス機能の詳細については、を参照してください link:concept_nw_concepts_chars.html["ネットワーキングの詳細"] セクション。



== VMXNET3へのアップグレード

Deploy 2.10 を使用した ONTAP Select 9.5 以降では、 VMware ESXi での新しいクラスタの導入に付属するデフォルトのネットワークドライバとして VMXNET3 が用意されています。古いONTAP Selectノードをバージョン9.5以降にアップグレードしても、ドライバは自動的にアップグレードされません。



== クラスタ MTU

マルチノードクラスタの ONTAP Select ノードの接続には、別の内部ネットワークが使用されます。通常、このネットワークの MTU サイズは 9000 です。ただし、 ONTAP Select ノードを接続するネットワークの MTU サイズが大きすぎる場合もあります。小さいフレームに対応するために、内部ネットワーク上の ONTAP Select で使用される MTU サイズは 7500~9000 バイトの範囲で指定できます。

MTU サイズは、クラスタ作成ページの「 Cluster Details 」セクションに表示されます。この値は、 Deploy 管理ユーティリティで次のように決定されます。

. 初期デフォルト値は 9000 です。
. HA ペアのホストとネットワークを追加すると、ネットワーク内の vSwitch の構成に基づいて、必要に応じて MTU 値が減ります。
. すべての HA ペアを追加してクラスタを作成できる状態になると、クラスタの最終的なクラスタ MTU 値が設定されます。



NOTE: ネットワークの設計に基づいて、必要に応じてクラスタの MTU 値を手動で設定できます。



== 標準 vSwitch 搭載の 2NIC ホスト

2NIC 構成で ONTAP Select のパフォーマンスを向上させるには、 2 つのポートグループを使用して内部と外部のネットワークトラフィックを分離する必要があります。この推奨構成では、次のような特定の構成が環境 に推奨

* ONTAP Select マルチノードクラスタ
* NIC 2 枚（ NIC 1 および NIC 2 ）
* 標準 vSwitch


この環境では、次のように 2 つのポートグループを使用してトラフィックを設定する必要があります。

.ポートグループ 1
* 内部ネットワーク（クラスタ、 RSM 、 HA-IC トラフィック）
* NIC1 がアクティブである
* NIC2 がスタンバイ状態です


.ポートグループ 2
* 外部ネットワーク（データトラフィックと管理トラフィック）
* NIC1 はスタンバイである
* NIC2 がアクティブです


を参照してください link:concept_nw_concepts_chars.html["ネットワーキングの詳細"] 2NICの導入の詳細については、セクションを参照してください。



== 標準 vSwitch 搭載の 4NIC ホスト

4 つの NIC 構成で ONTAP Select のパフォーマンスを向上させるには、 4 つのポートグループを使用して内部と外部のネットワークトラフィックを分離する必要があります。この推奨構成では、次のような特定の構成が環境 に推奨

* ONTAP Select マルチノードクラスタ
* NIC × 4 （ NIC1 、 NIC2 、 NIC3 、 NIC4 ）
* 標準 vSwitch


この環境では、次のように 4 つのポートグループを使用してトラフィックを設定する必要があります。

.ポートグループ 1
* 内部ネットワーク（クラスタ、 RSM トラフィック）
* NIC1 がアクティブである
* NIC2 、 NIC3 、 NIC4 スタンバイ


.ポートグループ 2
* 内部ネットワーク（クラスタ、 HA-IC トラフィック）
* NIC3 がアクティブです
* NIC1 、 NIC2 、 NIC4 スタンバイ


.ポートグループ 3
* 外部ネットワーク（データトラフィックと管理トラフィック）
* NIC2 がアクティブです
* NIC1 、 NIC3 、 NIC4 スタンバイ


.ポートグループ 4
* 外部ネットワーク（データトラフィック）
* NIC4 はアクティブです
* NIC1 、 NIC2 、 NIC3 、スタンバイ状態


を参照してください link:concept_nw_concepts_chars.html["ネットワーキングの詳細"] 4 NICの導入の詳細については、セクションを参照してください。



== ネットワークトラフィックの要件

ONTAP Select 環境のさまざまな参加者間でネットワークトラフィックが流れるように、ファイアウォールが適切に設定されていることを確認する必要があります。

.参加者
ONTAP Select 環境の一部としてネットワークトラフィックを交換する複数の参加者またはエンティティがあります。これらの情報が導入され、ネットワークトラフィック要件の要約概要 で使用されます。

* Deploy ONTAP Select 管理ユーティリティを導入する
* vSphere / ESXi ホスト。クラスタ環境でのホストの管理方法に応じて、 vSphere サーバまたは ESXi ホストのどちらかを使用します
* ハイパーバイザーサーバの ESXi ハイパーバイザーホスト
* OTS ノード： ONTAP Select ノード
* OTS クラスタ ONTAP Select クラスタです
* Admin WS ローカル管理ワークステーション


.ネットワークトラフィック要件の要約
次の表に、 ONTAP Select 環境のネットワークトラフィック要件を示します。

[cols="20,45,35"]
|===
| プロトコル / ポート | 方向（ Direction ） | 説明 


| TLS （ 443 ） | vCenter Server （管理対象）または ESXi （管理対象外）に導入 | VMware VIX API 


| 902 | vCenter Server （管理対象）または ESXi （管理対象外）に導入 | VMware VIX API 


| ICMP | ハイパーバイザーサーバに導入します | Ping 


| ICMP | 各 OTS ノードに展開します | Ping 


| SSH （ 22 ） | 管理 WS を各 OTS ノードに割り当てます | 管理 


| TLS （ 443 ） | OTS ノードおよびクラスタに展開します | ONTAP にアクセスします 


| TLS （ 443 ） | 展開する各 OTS ノード | Deploy にアクセスします 


| iSCSI （ 3260 ） | 展開する各 OTS ノード | メディエーター / メールボックスディスク 
|===