---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: ONTAP Select の導入を計画する際に考慮する必要のある一般的な要件がいくつかあります。 
---
= 一般的な要件と計画に関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の導入を計画する際に考慮する必要のある一般的な要件がいくつかあります。



== クラスタのサイズと関連する考慮事項

クラスタサイズに関連するいくつかの計画の問題について考慮する必要があります。

クラスタ内のノードの数:: ONTAP Select クラスタは、 1 ノード、 2 ノード、 4 ノード、 6 ノード、または 8 ノードで構成されます。クラスタのサイズは、アプリケーションの要件に基づいて決定する必要があります。たとえば、 HA 機能がエンタープライズ導入で必要な場合は、マルチノードクラスタを使用してください。
専用の導入とコロケーション導入:: アプリケーションタイプに基づいて、専用モデルとコロケーションモデルのどちらに従って導入を行うかを決定する必要があります。ワークロードの多様性と緊密な統合が原因で、コロケーションモデルの方が複雑になる可能性があります。




== ハイパーバイザーホスト

ハイパーバイザーホストに関連するいくつかの計画の問題について考慮する必要があります。


CAUTION: ネットアップサポートからの指示がないかぎり、 ONTAP Select 仮想マシンの構成を直接変更しないでください。仮想マシンの設定と変更は、 Deploy 管理ユーティリティからのみ実行してください。ネットアップサポートの支援なしで Deploy ユーティリティ以外の ONTAP Select 仮想マシンに変更を加えると、原因 でその仮想マシンが失敗し、使用できなくなる可能性があります。

ハイパーバイザーに依存しない:: ONTAP Select と ONTAP Select Deploy 管理ユーティリティは、どちらもハイパーバイザーに依存しません。両方に対して次のハイパーバイザーがサポートされています。
+
--
* VMware ESXi
* Kernel-based Virtual Machine （ KVM ）


--



NOTE: ONTAP Select 9.10.1以降では、新しいクラスタの導入時のKVMハイパーバイザーのサポートが廃止されました。以前にサポートされていたリリースでも KVM を使用できます。

サポート対象のプラットフォームの詳細については、ハイパーバイザー固有の計画情報とリリースノートを参照してください。

ONTAP Select ノードと管理ユーティリティ用のハイパーバイザー:: Deploy 管理ユーティリティと ONTAP Select ノードは、どちらも仮想マシンとして実行されます。Deploy ユーティリティ用に選択したハイパーバイザーは、 ONTAP Select ノード用に選択したハイパーバイザーに依存しません。この 2 つをペアリングすると、完全な柔軟性が得られます。
+
--
* VMware ESXi で実行される Deploy ユーティリティは、 VMware ESXi または KVM で ONTAP Select クラスタを作成および管理できます
* KVM で実行される Deploy ユーティリティは、 VMware ESXi または KVM で ONTAP Select クラスタを作成および管理できます


--
ホストごとに 1 つ以上の ONTAP Select ノードインスタンス:: 各 ONTAP Select ノードは専用の仮想マシンとして実行されます。同じハイパーバイザーホストに複数のノードを作成できますが、次の制限事項があります。
+
--
* 1 つの ONTAP Select クラスタの複数のノードを同じホストで実行することはできません。特定のホスト上のすべてのノードは、異なる ONTAP Select クラスタに属している必要があります。
* 外付けストレージを使用する必要があります。
* ソフトウェア RAID を使用する場合、ホストに導入できる ONTAP Select ノードは 1 つだけです。


--
クラスタ内のノードに対するハイパーバイザーの整合性:: ONTAP Select クラスタ内のすべてのホストが、同じバージョンおよびリリースのハイパーバイザーソフトウェアで実行されている必要があります。
各ホストの物理ポートの数:: 各ホストで 1 つ、 2 つ、または 4 つの物理ポートを使用するように設定する必要があります。ネットワークポートを柔軟に設定することもできますが、可能な場合は次の推奨事項に従う必要があります。
+
--
* シングルノードクラスタのホストには 2 つの物理ポートが必要です。
* マルチノードクラスタの各ホストには 4 つの物理ポートが必要です


--
ONTAP Select と ONTAP ハードウェアベースのクラスタの統合:: ONTAP Select ノードをハードウェアベースの ONTAP クラスタに直接追加することはできません。ただし、必要に応じて、 ONTAP Select クラスタとハードウェアベースの ONTAP クラスタの間にクラスタピア関係を確立できます。




== ストレージ

ホストストレージに関連するいくつかの計画の問題について考慮する必要があります。

RAID タイプ:: ESXi で直接接続型ストレージ（ DAS ）を使用する場合は、ローカルのハードウェア RAID コントローラを使用するか、 ONTAP Select に付属のソフトウェア RAID 機能を使用するかを決める必要があります。ソフトウェア RAID を使用する場合は、を参照してください link:reference_plan_ots_storage.html["ストレージと RAID に関する考慮事項"] を参照してください。
ローカルストレージ:: RAID コントローラが管理するローカルストレージを使用する場合は、次のことを決定する必要があります。
+
--
* 1 つ以上の RAID グループを使用するかどうか
* 1 つ以上の LUN を使用するかどうか


--
外付けストレージ:: ONTAP Select vNAS 解決策 を使用する場合は、リモートデータストアの配置場所とそのデータストアへのアクセス方法を決定する必要があります。ONTAP Select vNAS は次の構成をサポートします。
+
--
* VMware vSAN
* 汎用の外付けストレージアレイ


--
必要なストレージの見積り:: ONTAP Select ノードに必要なストレージ容量を決定する必要があります。この情報は、ストレージ容量を含む購入ライセンスを取得する際に必要になります。詳細については、「ストレージ容量の制限」を参照してください。



NOTE: ONTAP Select ストレージ容量は、 ONTAP Select 仮想マシンに接続されているデータディスクの合計許容サイズに対応します。

本番環境のライセンスモデル:: 本番環境に導入する ONTAP Select クラスタごとに、容量階層または容量プールのライセンスモデルを選択する必要があります。詳細については、「 _License__ 」セクションを参照してください。


.関連情報
* link:reference_plan_ots_storage.html["ストレージと RAID に関する考慮事項"]

