---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: ONTAP Select ホストストレージに関連するいくつかの計画の問題について考慮する必要があります。 
---
= ONTAP SelectストレージとRAIDに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select ホストストレージに関連するいくつかの計画の問題について考慮する必要があります。


NOTE: 外部ストレージのサポート情報については、を参照してください。 link:reference_plan_ots_vnas.html["ONTAP Select vNAS の要件"]。



== ハードウェア RAID コントローラの要件

ONTAP Select を導入するハイパーバイザーホスト上の RAID コントローラがいくつかの要件を満たしている必要があります。


NOTE: ONTAP Selectを実行するホストでは、ハードウェアRAIDコントローラまたはONTAP Selectで提供されるソフトウェアRAID機能を使用する場合、ローカルの物理ドライブが必要です。ONTAP Select vNAS 解決策 を使用して外付けストレージにアクセスする場合、ローカルの RAID コントローラとソフトウェア RAID 機能は使用されません。

RAID コントローラの最小要件は次のとおりです。

* 12Gbps のスループット
* 512MB の内蔵バッテリバックアップ式キャッシュまたはフラッシュ（スーパーキャパシタ）キャッシュ
* ライトバックモードで設定：
+
** フェイルバックモードを「ライトスルー」にする（サポートされている場合）
** 「常に先読み」ポリシーを有効にする（サポートされている場合）


* RAID コントローラの背後にあるすべてのローカルディスクを単一の RAID グループとして設定する必要があります。必要に応じて、複数の RAID コントローラを使用できます。
+
** RAID グループのローカルドライブキャッシュを無効にします。このキャッシュは、データの整合性を維持するために必要です。


* 次のガイドラインに基づいて LUN を設定する必要があります。
+
** RAIDグループサイズがLUNの最大サイズである64TBを超える場合は、同じサイズのLUNを複数設定し、RAIDグループ内の使用可能なストレージをすべて消費します。
** RAIDグループサイズがLUNの最大サイズである64TBよりも小さい場合は、RAIDグループ内の使用可能なストレージをすべて消費する1つのLUNを設定する必要があります。






== ソフトウェア RAID の要件

ハイパーバイザーにONTAP Selectクラスタを導入する場合は、ローカルのハードウェアRAIDコントローラの代わりにONTAP Selectが提供するソフトウェアRAID機能を利用できます。ソフトウェア RAID を使用してクラスタを導入する前に、いくつかの要件と制限事項に注意する必要があります。



=== 一般的な要件

ソフトウェアRAIDの導入環境は、次のコア要件を満たしている必要があります。

* VMware ESXi 8.0 GA (ビルド 20513097) 以降
* ONTAP Select プレミアムライセンス以上
* ローカル SSD ドライブのみ
* システムディスクをルートアグリゲートおよびデータアグリゲートから分離します
* ホストにハードウェア RAID コントローラがありません



NOTE: ハードウェア RAID コントローラがある場合は、を参照してください link:concept_stor_concepts_chars.html["ストレージの詳細を見る"] 追加の設定要件については、セクションを参照してください



=== ESXi固有の要件

* VMware ESXi 8.0 GA (ビルド 20513097) 以降
* VMware VMotion 、 HA 、および DRS はサポートされません
* ONTAP Select 9.4以前からアップグレードされたノードではソフトウェアRAIDを使用できません。その場合は、ソフトウェアRAIDを導入するための新しいノードを作成する必要があります。




=== KVM固有の要件

また、特定のソフトウェアパッケージ設定要件もあります。参照link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linuxサーバーの準備"]詳細については、手順を参照してください。

KVMに対するメディアの期待:: 使用するSSDフラッシュストレージデバイスは、次の追加要件を満たしている必要があります。
+
--
* SSDデバイスは、次の方法で正確かつ永続的に自身をLinuxホストに報告する必要があります。
+
** # cat /sys/block /<device>/ queue / rotational
+
これらのコマンドで報告される値は「0」である必要があります。



* デバイスがHBAに接続されているか、場合によってはJBODモードで動作するように設定されたRAIDコントローラに接続されていることが想定されます。RAIDコントローラを使用する場合は、RAID機能をオーバーレイせずに、デバイス機能をホストに渡す必要があります。JBODモードでRAIDコントローラを使用する場合は、RAIDのマニュアルを参照するか、必要に応じてベンダーに問い合わせて、デバイスの回転速度が「0」であることを確認してください。
* 次の2つの独立したストレージコンポーネントがあります。
+
** 仮想マシンストレージ
+
これは、ONTAP Select仮想マシンのホストに使用されるシステムデータを含むLVMプール（ストレージプール）です。LVMプールには耐久性に優れたフラッシュデバイスを使用する必要があり、SAS、SATA、NVMeのいずれかを使用できます。パフォーマンスを向上させるためには、NVMeデバイスを使用することを推奨します。

** データディスク
+
データ管理に使用するSASまたはSATA SSDドライブのセットです。SSDデバイスは、エンタープライズクラスで耐久性に優れている必要があります。NVMeインターフェイスはサポートされていません。



* すべてのデバイスは512BPSでフォーマットする必要があります。


--




=== ONTAP Select ノード構成

各 ONTAP Select ノードおよびハイパーバイザーホストを次のように設定して、ルートアグリゲートとデータアグリゲートからシステムディスクを分離する必要があります。

* システムストレージプールの作成 ONTAP Select システムデータ用のストレージプールを作成する必要があります。ONTAP Select ノードの設定の一環として、ストレージプールを接続する必要があります。
* 必要な物理ディスクの接続ハイパーバイザーホストに必要な SSD ディスクが接続されていて、 ONTAP Select 仮想マシンで使用できる必要があります。これらのドライブには、ルートアグリゲートとデータアグリゲートが格納されます。ONTAP Select ノードの設定の一環として、ストレージディスクを接続する必要があります。




== ストレージ容量の制限

ONTAP Select の導入を計画する際には、ストレージの割り当てと使用に関する制限事項を把握しておく必要があります。

次に、最も重要なストレージの制限事項を示します。詳細については、も参照してくださいlink:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]。


TIP: ONTAP Select では、ストレージの割り当てと使用に関していくつかの制限が適用されます。ONTAP Select クラスタを導入したりライセンスを購入したりする前に、これらの制限事項を確認しておく必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["使用許諾"] 詳細については、を参照してください。



=== 物理ストレージ容量の計算

ONTAP Select ストレージ容量は、仮想データおよび ONTAP Select 仮想マシンに接続されているルートディスクの合計許容サイズに対応します。容量を割り当てる際はこの点を考慮してください。



=== シングルノードクラスタの最小ストレージ容量

シングルノードクラスタ内のノードに割り当てられるストレージプールの最小サイズは次のとおりです。

* 評価： 500GB
* 本番： 1.0 TB


本番環境の最小割り当ては、ユーザデータ用に 1TB 、さまざまな ONTAP Select 内部プロセス用に 266GB の容量が必要なオーバーヘッドとみなされます。



=== マルチノードクラスタの最小ストレージ容量

マルチノードクラスタの各ノードに割り当てられるストレージプールの最小サイズは次のとおりです。

* 評価： 1.9 TB
* 本番： 2.0 TB


本番環境の最小割り当ては、ユーザデータ用に 2TB と、さまざまな ONTAP Select 内部プロセスで使用される約 266GB です。これは必要なオーバーヘッドとみなされます。

[NOTE]
====
HA ペア内の各ノードのストレージ容量は同じであることが必要です。

HAペアのストレージ容量を見積もるときは、すべてのアグリゲート（ルートとデータ）がミラーされていることを考慮する必要があります。その結果、アグリゲートの各プレックスが同じ量のストレージを消費します。

たとえば、2TBのアグリゲートを作成すると、2つのプレックスインスタンス（plex0の場合は2TB、plex1の場合は2TB）、またはライセンスで許可されている合計ストレージ容量の4TBに2TBが割り当てられます。

====


=== ストレージ容量と複数のストレージプール

ローカルの直接接続型ストレージ、 VMware vSAN 、または外付けストレージアレイを使用する場合は、各 ONTAP Select ノードで最大 400TB のストレージを使用するように設定できます。ただし、直接接続型ストレージまたは外付けストレージアレイを使用する場合、 1 つのストレージプールの最大サイズは 64TB です。したがって、このような状況で 64 TB を超えるストレージを使用する場合は、次のように複数のストレージプールを割り当てる必要があります。

* クラスタの作成プロセスで初期ストレージプールを割り当てます
* 1 つ以上のストレージプールを追加して、ノードのストレージを増やします



NOTE: バッファが 2% 残っているため、各ストレージプールでは使用されず、容量ライセンスは必要ありません。容量上限を指定しないかぎり、このストレージは ONTAP Select で使用されません。容量上限を指定すると、指定した量が 2% のバッファゾーンに収まる場合を除き、その容量のストレージが使用されます。バッファは、ストレージプール内のすべてのスペースを割り当てようとしたときに発生する一時的なエラーを防ぐために必要です。



=== ストレージ容量と VMware vSAN

VMware vSAN を使用する場合、データストアは 64TB を超える場合があります。ただし、最初に割り当てることができるのは、 ONTAP Select クラスタの作成時のみです。クラスタが作成されたら、既存の VSAN データストアから追加のストレージを割り当てることができます。ONTAP Select で使用できる VSAN データストアの容量は、 VM ストレージポリシーセットによって決まります。



=== ベストプラクティス

ハイパーバイザーのコアハードウェアに関する次の推奨事項を考慮してください。

* 1つのONTAP Selectアグリゲート内のドライブはすべて同じタイプにする必要があります。たとえば、 HDD ドライブと SSD ドライブを同じアグリゲート内に混在させることはできません。




== プラットフォームライセンスに基づく追加のディスクドライブ要件

選択するドライブは、プラットフォームのライセンスサービスによって制限されます。


NOTE: ディスクドライブの要件は、ソフトウェア RAID だけでなく、ローカルの RAID コントローラとドライブを使用する場合にも適用されます。これらの要件は、 ONTAP Select vNAS 解決策 経由でアクセスする外付けストレージには適用されません。

.標準
* 内部 HDD （ NL-SAS 、 SATA 、 10K SAS ） × 8~60


.Premium サービス
* 内部 HDD （ NL-SAS 、 SATA 、 10K SAS ） × 8~60
* 4~60 本の内蔵 SSD を搭載


.Premium XL
* 内部 HDD （ NL-SAS 、 SATA 、 10K SAS ） × 8~60
* 4~60 本の内蔵 SSD を搭載
* 4~14 個の内蔵 NVMe



NOTE: ローカル DAS ドライブを使用するソフトウェア RAID は、 Premium ライセンス（ SSD のみ）と Premium XL ライセンス（ SSD または NVMe ）でサポートされます。



== NVMe ドライブにはソフトウェア RAID を使用

NVMe SSD ドライブを使用するようにソフトウェア RAID を設定できます。環境が次の要件を満たしている必要があります。

* サポートされているDeploy管理ユーティリティを備えたONTAP Select
* Premium XL プラットフォームライセンス製品または 90 日間の評価ライセンス
* VMware ESXi バージョン 8.0 以降
* 仕様 1.0 以降に準拠する NVMe デバイス


NVMe ドライブを使用する前に、ドライブを手動で設定する必要があります。を参照してください link:task_chk_nvme_configure.html["NVMeドライブを使用するようにホストを設定"] を参照してください。
