---
sidebar: sidebar 
permalink: reference_vpi_troubleshooting.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, troubleshooting 
summary: Deploy vCenter プラグインのサポートの一環として、使用可能なトラブルシューティング手法と一般的なエラーを理解しておく必要があります。 
---
= トラブルシューティング
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy vCenter プラグインのサポートの一環として、使用可能なトラブルシューティング手法と一般的なエラーを理解しておく必要があります。



== インストール、アンインストール、および更新のエラーです

インストール、アンインストール、または更新の手順 の実行中にエラーが発生した場合、手順 （ Web ユーザインターフェイスまたは CLI ）の開始に使用される Deploy インターフェイスで表示されるエラーメッセージが API から返されます。

一般的なエラーには次のものがあります。

* 無効なクレデンシャル（ユーザ名またはパスワード）
* インストール対象として指定されたプラグインが無効であるか、存在しません
* vCenter サーバがオフラインであるか到達不能です


追加情報 でエラーが発生した場合は、次のログを確認します。

* 導入サーバーログ
* vCenter Server のログです




== vCenter のプラグインエラー

vCenter とのセッションでエラーが発生すると、エラーメッセージが表示されます。一般的なエラーには次のものがあります。

* Deploy サーバの SSL 証明書がブラウザで受け入れられなかったため、 vCenter に組み込みコンテンツを Deploy サーバからロードできませんでした。
* Deploy サーバが、 Deploy vCenter プラグインへのアクセスを試みる vCenter ユーザのセッション ID を承認できません。セッションがタイムアウトします。
* Deploy vCenter プラグインにアクセスするための十分な権限がありません。
* Deploy サーバがオフラインであるか到達不能である。


追加情報 のエラーについては、次のログを参照してください。

* vCenter Server のログです
* 導入サーバーログ

