---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: ONTAP Select Deploy 管理ユーティリティのインストールを計画する際に考慮する必要のある一般的な要件がいくつかあります。 
---
= ONTAP Select Deploy の一般的な要件と計画
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 管理ユーティリティのインストールを計画する際に考慮する必要のある一般的な要件がいくつかあります。



== Deploy ユーティリティと ONTAP Select クラスタのペアリング

Deploy ユーティリティのインスタンスを ONTAP Select クラスタにペアリングする際に使用するいくつかのオプションがあります。


NOTE: すべての導入シナリオでは、単一の ONTAP Select クラスタとクラスタ内のノードを、 Deploy 管理ユーティリティの 1 つのインスタンスだけで管理できます。Deploy ユーティリティの 2 つ以上の異なるインスタンスによって 1 つのクラスタを管理することはできません。



===== ONTAP Select クラスタごとにユーティリティの 1 つのインスタンス

Deploy ユーティリティの専用のインスタンスを使用して、各 ONTAP Select クラスタを導入および管理できます。この 1 対 1 の構成では、ユーティリティとクラスタの各ペアリングが明確に分離されます。この構成では、小規模な障害ドメインで高度な分離が実現されます。



===== 複数の ONTAP Select クラスタにユーティリティの 1 つのインスタンスを使用する

Deploy ユーティリティの単一インスタンスを使用して、複数の ONTAP Select クラスタを組織で導入および管理できます。この 1 対多の構成では、すべての処理データと設定データが Deploy ユーティリティの同じインスタンスによって管理されます。


NOTE: Deploy ユーティリティの 1 つのインスタンスで、最大 400 個の ONTAP Select ノードまたは 100 個のクラスタを管理できます。



== クレデンシャルストアを使用した認証

ONTAP Select Deploy クレデンシャルストアは、アカウント情報を保持するデータベースです。Deploy は、クラスタの作成と管理の一環として、アカウントのクレデンシャルを使用してホスト認証を実行します。ONTAP Select の導入計画の一環として、クレデンシャルストアがどのように使用されるかを理解しておく必要があります。


NOTE: アカウント情報は、 AES 暗号化アルゴリズムと SHA-256 ハッシュアルゴリズムを使用し、データベースに安全に保存されます。



===== クレデンシャルのタイプ

次のタイプのクレデンシャルがサポートされます。

* ONTAP Select ノードを VMware ESXi に直接導入する際にハイパーバイザーホストを認証するために使用するホスト
* ホストが VMware vCenter で管理されている場合、 ESXi への ONTAP Select ノードの導入時に vCenter サーバの認証に使用する vCenter




===== にアクセスします

クレデンシャルストアは、ハイパーバイザーホストの追加など、 Deploy を使用する通常の管理タスクの実行時に内部的にアクセスされます。Deploy の Web ユーザインターフェイスと CLI を使用して、クレデンシャルストアを直接管理することもできます。
