---
sidebar: sidebar 
permalink: reference_plan_best_practices.html 
keywords: plan, planning, best practices, recommendations 
summary: ONTAP Select の導入を計画する際に考慮する必要があるベストプラクティスがあります。 
---
= ベストプラクティスのまとめ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の導入を計画する際に考慮する必要があるベストプラクティスがあります。



== ストレージ

ストレージに関する次のベストプラクティスを考慮してください。



=== オールフラッシュアレイまたは汎用フラッシュアレイ

オールフラッシュ VSAN または汎用フラッシュアレイを使用する ONTAP Select 仮想 NAS （ vNAS ）環境は、 SSD 以外の DAS ストレージを使用する ONTAP Select のベストプラクティスに従う必要があります。



=== ハイパーバイザーコアハードウェア

単一の ONTAP Select アグリゲート内のすべてのドライブを同じタイプにする必要があります。たとえば、 HDD ドライブと SSD ドライブを同じアグリゲート内に混在させることはできません。



=== RAID コントローラ

サーバ RAID コントローラは、ライトバックモードで動作するように設定する必要があります。書き込みワークロードのパフォーマンスに問題が見られる場合は、コントローラの設定を調べて、ライトスルーまたはライトアラウンドが有効になっていないことを確認してください。

物理サーバに搭載された単一の RAID コントローラがすべてのローカル接続ディスクを管理している場合は、サーバ OS 専用の LUN を 1 つ作成し、 ONTAP Select 用に 1 つ以上の LUN を作成することを推奨します。このベストプラクティスにより、ブートディスクが破損した場合でも、管理者は ONTAP Select に影響を与えることなく OS LUN を再作成できます。

RAID コントローラキャッシュは、 NVRAM パーティション宛ての変更だけでなく、受信ブロックのすべての変更を保存するために使用されます。したがって、 RAID コントローラを選択する場合は、使用可能なキャッシュが最も大きいコントローラを選択してください。キャッシュが大きいほどディスクフラッシュの回数が減るため、 ONTAP Select VM とハイパーバイザーのパフォーマンス、およびサーバに配置されているすべてのコンピューティグ VM のパフォーマンスも向上します。



=== RAIDグループ

最適な RAID グループサイズは 8~12 ドライブです。RAID グループあたりの最大ドライブ数は 24 本です。

ONTAP Select ノードあたりサポートされる NVMe ドライブの最大数は 14 本です。

スペアディスクはオプションですが、推奨されます。また、 RAID グループごとに 1 つのスペアを使用することも推奨します。ただし、すべての RAID グループに対してグローバルスペアを使用できます。たとえば、 8~12 本のドライブで構成する 3 つの RAID グループごとに 2 つのスペアを使用できます。

ONTAP Select グループ内の LUN 数を増やしても、パフォーマンスが向上することはありません。複数の LUN を使用するのは、 SATA / NL-SAS 構成のベストプラクティスに従うため、またはハイパーバイザーのファイルシステムに関する制限に対応するためです。



=== VMware ESXi ホスト

ネットアップでは、システムディスクをホストするデータストアには ESX 6.5 U2 以降と NVMe ディスクを使用することを推奨しています。この構成は、 NVRAM パーティションに最適なパフォーマンスを提供します。


NOTE: ESX 6.5 U2 以降にインストールする場合、 ONTAP Select は、システムディスクが SSD にあるか NVME ディスクにあるかに関係なく、 vNVME ドライバを使用します。これにより、 VM のハードウェアレベルが 13 に設定され、 ESX 6.5 以降と互換性があります。

ONTAP Select ネットワークと外付けストレージ（ iSCSI または NFS を使用する場合は、 VMware vSAN と汎用のストレージアレイのトラフィック）に専用のネットワークポート、帯域幅、および vSwitch の構成を定義します。

ストレージ利用率を制限するように容量オプションを設定します（ ONTAP Select では、外部 vNAS データストアの全容量は使用できません）。

可能な場合は、すべての汎用の外付けストレージアレイで、使用可能な冗長性機能と HA 機能を使用してください。



=== VMware Storage vMotion の略

ONTAP Select ノードで VMware Storage vMotion を使用するかどうかを決定する際の検討事項は、新しいホストでの使用可能な容量だけではありません。基盤となるストレージタイプ、ホスト構成、ネットワーク機能が、元のホストと同じワークロードに対応できる必要があります。



== ネットワーキング

ネットワークに関する次のベストプラクティスを考慮してください。



=== MAC アドレスが重複しています

複数の Deploy インスタンスが重複する MAC アドレスを割り当てないようにするには、 1 つのレイヤ 2 ネットワークにつき 1 つの Deploy インスタンスを使用して、 ONTAP Select クラスタまたはノードを作成または管理する必要があります。



=== EMS メッセージです

2 ノード ONTAP Select クラスタでは、ストレージフェイルオーバーが無効であることを示す EMS メッセージが表示されていないかを注意深く監視する必要があります。このメッセージはメディエーターサービスへの接続が失われたことを示すため、ただちに解決が必要です。



=== 負荷分散

内部と外部の ONTAP Select ネットワークの両方でロードバランシングを最適化するには、ロードバランシングポリシー「 Route Based on Originating Virtual Port 」を使用します。



=== 複数のレイヤ 2 ネットワーク

データトラフィックが複数のレイヤ 2 ネットワークにまたがっており、 VLAN ポートの使用が必要である場合、または複数の IPspace を使用している場合は、 VGT を使用する必要があります。



=== 物理スイッチの構成

VMware では、 ESXi ホストに接続されたスイッチポートで STP を Portfast に設定することを推奨しています。スイッチポートで STP を Portfast に設定しないと、アップリンクで障害が発生した場合に ONTAP Select が対応できないおそれがあります。LACP を使用する場合は、 LACP タイマーを高速（ 1 秒）に設定する必要があります。ロードバランシングポリシーは、ポートグループでは「 Route Based on IP Hash 」、 LAG では「 Source and Destination IP Address and TCP/UDP Port and VLAN 」に設定する必要があります。



== 高可用性

高可用性を実現するために、次のベストプラクティスを考慮してください。



=== バックアップを導入

Deploy の設定データは、クラスタの作成後も含めて定期的にバックアップすることを推奨します。バックアップにはメディエーターの設定データが含まれるため、 2 ノードクラスタではバックアップが特に重要です。

クラスタを作成または導入したら、 ONTAP Select Deploy の設定データをバックアップする必要があります。



=== ミラーされたアグリゲート

プライマリアグリゲートの最新の（ RPO ゼロの）コピーを提供するためには、ミラーされたアグリゲートが必要ですが、プライマリアグリゲートの空きスペースが不足しないように注意してください。プライマリアグリゲートのスペースが不足すると、原因 ONTAPによってストレージギブバックのベースラインとして使用される共通のSnapshotコピーが削除される可能性があります。これは、クライアントの書き込みに対応するための設計どおりの動作です。ただし、フェイルバック時に共通の Snapshot コピーがないと、 ONTAP Select ノードがミラーアグリゲートから完全なベースラインを作成しなければなりません。シェアードナッシング環境では、この処理にかなりの時間がかかることがあります。


NOTE: ストレージのパフォーマンスと可用性を最適化するために、ミラーアグリゲートでは少なくとも20%の空きスペースを確保することを推奨します。ミラーされていないアグリゲートでは10%が推奨されますが、追加の10%のスペースはファイルシステムで増分変更に対応するために使用できます。増分変更を行うと、ONTAPのcopy-on-write Snapshotベースのアーキテクチャにより、ミラーされたアグリゲートのスペース使用率が向上します。これらのベストプラクティスに従わないと、パフォーマンスに悪影響を及ぼす可能性があります。



=== NIC のアグリゲーション、チーミング、およびフェイルオーバー

ONTAP Select では、 2 ノードクラスタ用に 1 つの 10Gb リンクがサポートされます。ただし、 ONTAP Select クラスタの内部ネットワークと外部ネットワークの両方で、 NIC アグリゲーションまたは NIC チーミングを使用してハードウェアの冗長性を確保することを推奨します。

NIC に複数の ASIC （特定用途向け集積回路）が搭載されている場合は、内部ネットワークと外部ネットワークに対して NIC チーミングによってネットワークの構成要素を構築する際に、各 ASIC から 1 つずつネットワークポートを選択します。

ESX と物理スイッチの両方で、 LACP モードをアクティブにすることを推奨します。さらに、物理スイッチ、ポート、ポートチャネルインターフェイス、および VMNIC で、 LACP タイマーを高速（ 1 秒）に設定する必要があります。

LACP が有効な分散 vSwitch を使用する場合は、ロードバランシングポリシーを、ポートグループでは「 Route Based on IP Hash 」、 LAG では「 Source and Destination IP Address 」、「 TCP/UDP Port 」、および「 VLAN 」に設定することを推奨します。



=== 2 ノードストレッチ HA （ MetroCluster SDS ）のベストプラクティス

MetroCluster SDS を作成する前に、 ONTAP Deploy の接続チェッカーを使用して、 2 つのデータセンター間のネットワーク遅延が許容範囲内に収まることを確認します。

Virtual Guest Tagging （ VGT ；仮想ゲストタギング）と 2 ノードクラスタを使用する場合は、さらに注意が必要です。2 ノードクラスタ構成では、ノード管理 IP アドレスを使用して、 ONTAP が完全に使用可能になる前にメディエーターへの初期接続を確立します。したがって、ノード管理 LIF （ポート e0a ）にマッピングされたポートグループでは、外部スイッチタギング（ EST ）と仮想スイッチタギング（ VST ）のみがサポートされます。さらに、管理トラフィックとデータトラフィックの両方が同じポートグループを使用している場合、 2 ノードクラスタ全体でサポートされるのは、 EST と VST だけです。
