---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: HA を使用して 2 ノードクラスタを導入する場合は、他のクラスタノード構成と同じ計画と構成を使用します。ただし、 2 ノードクラスタを作成する場合に注意しなければならない相違点がいくつかあります。 
---
= HA 構成の ONTAP Select 2 ノードクラスタ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HA を使用して 2 ノードクラスタを導入する場合は、他のクラスタノード構成と同じ計画と構成を使用します。ただし、 2 ノードクラスタを作成する場合に注意しなければならない相違点がいくつかあります。

.ターゲットとなる環境
2 ノードクラスタは 1 つの HA ペアで構成されており、リモートオフィス / ブランチオフィス環境向けに設計されています。


NOTE: 主にリモートオフィス / ブランチオフィス環境向けに設計されていますが、必要に応じてデータセンターに 2 ノードクラスタを導入することもできます。

.ライセンス
任意の VMware vSphere ライセンスを使用して、 2 ノードクラスタを導入できます。ただし、 VMware ROBO Standard と Advanced のライセンスはリモートオフィス / ブランチオフィス環境に適しています。

.メディエーターサービス
クラスタが 2 つのノードで構成されている場合は、ノードに障害が発生したり、通信が失われたりすると、必要なクォーラムを確保できません。このようなスプリットブレイン状態を解決するために、 ONTAP Select Deploy ユーティリティの各インスタンスにはメディエーターサービスが用意されています。このサービスは、アクティブな 2 ノードクラスタ内の各ノードに接続して HA ペアを監視し、障害の管理を支援します。メディエーターサービスは、各 2 ノードクラスタに関連付けられている専用の iSCSI ターゲットで HA の状態情報を管理します。


CAUTION: アクティブな2ノードクラスタが1つ以上ある場合、クラスタを管理するONTAP Select Deploy仮想マシンは常に実行されている必要があります。DeployONTAP Select Deploy 仮想マシンが停止または障害が発生した場合、メディエーター サービスは利用できなくなり、2 ノード クラスタの HA 機能が失われます。

.クラスタとメディエーターサービスの場所
2 ノード クラスタは通常、リモート オフィスまたはブランチ オフィスに導入されるため、企業のデータ センターや管理サポートを提供するONTAP Select Deploy ユーティリティから離れた場所に設置できます。この構成では、 ONTAP Select Deploy ユーティリティとクラスタ間の管理トラフィックは WAN 経由で流れます。制限事項の詳細については、リリースノートをご覧ください。

.デプロイ構成データをバックアップする
ベストプラクティスとしては、link:task_cli_clusters.html["ONTAP Select Deploy構成データをバックアップする"]クラスターの作成後も含め、定期的に実行します。これは、バックアップにメディエーター構成データが含まれるため、2ノードクラスターでは特に重要になります。

.Deploy に割り当てられた静的 IP アドレス
ONTAP Select Deploy 管理ユーティリティに静的 IP アドレスを割り当てる必要があります。この要件は、1 つ以上のONTAP Select 2 ノード クラスタを管理するすべてのONTAP Select Deploy インスタンスに適用されます。
