---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: HA を使用して 2 ノードクラスタを導入する場合は、他のクラスタノード構成と同じ計画と構成を使用します。ただし、 2 ノードクラスタを作成する場合に注意しなければならない相違点がいくつかあります。 
---
= HA 構成の ONTAP Select 2 ノードクラスタ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HA を使用して 2 ノードクラスタを導入する場合は、他のクラスタノード構成と同じ計画と構成を使用します。ただし、 2 ノードクラスタを作成する場合に注意しなければならない相違点がいくつかあります。

.ターゲットとなる環境
2 ノードクラスタは 1 つの HA ペアで構成されており、リモートオフィス / ブランチオフィス環境向けに設計されています。


NOTE: 主にリモートオフィス / ブランチオフィス環境向けに設計されていますが、必要に応じてデータセンターに 2 ノードクラスタを導入することもできます。

.ライセンス
任意の VMware vSphere ライセンスを使用して、 2 ノードクラスタを導入できます。ただし、 VMware ROBO Standard と Advanced のライセンスはリモートオフィス / ブランチオフィス環境に適しています。

.メディエーターサービス
クラスタが 2 つのノードで構成されている場合は、ノードに障害が発生したり、通信が失われたりすると、必要なクォーラムを確保できません。このようなスプリットブレイン状態を解決するために、 ONTAP Select Deploy ユーティリティの各インスタンスにはメディエーターサービスが用意されています。このサービスは、アクティブな 2 ノードクラスタ内の各ノードに接続して HA ペアを監視し、障害の管理を支援します。メディエーターサービスは、各 2 ノードクラスタに関連付けられている専用の iSCSI ターゲットで HA の状態情報を管理します。


CAUTION: アクティブな 2 ノードクラスタが 1 つ以上ある場合は、クラスタを管理する ONTAP Select Deploy 仮想マシンが常時稼働している必要があります。Deploy 仮想マシンが停止するか、障害が発生すると、メディエーターサービスが使用できなくなり、 2 ノードクラスタの HA 機能が失われます。

.クラスタとメディエーターサービスの場所
通常、 2 ノードクラスタはリモートオフィスまたはブランチオフィスに導入されるため、企業データセンターおよび管理サポートを提供する Deploy ユーティリティから離れた場所に配置できます。この構成では、 Deploy ユーティリティとクラスタの間の管理トラフィックは WAN を経由します。制限事項と制限事項の詳細については、リリースノートを参照してください。

.Deployの設定データをバックアップする
Deploy の設定データは、クラスタの作成後も含めて定期的にバックアップすることを推奨します。バックアップにはメディエーターの設定データが含まれるため、 2 ノードクラスタではバックアップが特に重要です。

.Deploy に割り当てられた静的 IP アドレス
Deploy 管理ユーティリティに静的 IP アドレスを割り当てる必要があります。この要件は、 1 つ以上の ONTAP Select 2 ノードクラスタを管理する環境 All Deploy インスタンスです。
