---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 現在のリリースには、ONTAP Selectに固有のいくつかの新機能や改善点が含まれています。 
---
= ONTAP Selectの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サポート対象バージョンのONTAP Selectの新機能と機能拡張について説明します。



== ONTAP Select9.18.1

クラスタの拡張と縮小のサポート強化:: ONTAP Select 9.18.1 以降では、ESXi および KVM ハイパーバイザ ホスト上の 4 ノードと 12 ノードのONTAP Selectクラスタ間でのクラスタの拡張と縮小がサポートされます。
+
--
--
ESXi または KVM ホスト上の既存のクラスタのサイズを、次の増分単位で増やすことができます。

* 4ノードから6、8、10、12ノードまで
* 6ノードから8、10、12ノードへ
* 8ノードから10または12ノードへ
* 10から12ノード


ESXi または KVM ホスト上の既存のクラスタのサイズを、次の増分単位で減らすことができます。

* 12ノードから10、8、6、または4ノードへ
* 10ノードから8、6、または4ノードへ
* 8ノードから6ノードまたは4ノードへ
* 6ノードから4ノードへ


--
link:task_cluster_expansion_contraction.html["クラスタの拡張と縮小、およびサポートされている KVM と ESXi ハイパーバイザーのバージョンについて学習します。"] 。

--




== ONTAP Select9.17.1

KVMホスト上のローカル接続NVMeディスクに対するソフトウェアRAIDサポート:: ONTAP Select 9.17.1 では、カーネルベースの仮想マシン (KVM) ハイパーバイザー ホスト上のONTAP Selectローカル接続された NVMe ディスクに対するソフトウェア RAID サポートが導入されています。
+
--
ローカル接続されたNVMeディスクにソフトウェアRAIDを使用するには、 link:kvm-host-configuration-and-preparation-checklist.html["PCI パススルー (DirectPath IO) を構成する"] KVMホストを準備する際に使用します。これにより、KVMホストがローカルに接続されたNVMeディスクに直接アクセスできるようになります。これは以下のタスクに必要です。

* NVMeドライブを使用するためのKVMホストの構成
* クラスターを展開した後のソフトウェアRAIDの使用


link:concept_stor_swraid_local.html["ローカル接続ストレージのソフトウェア RAID 構成サービスについて学習します"] 。

--
KVMホスト上のクラスタ拡張と縮小のサポート:: ONTAP Select 9.17.1以降では、クラスタの拡張と縮小機能がカーネルベース仮想マシン（KVM）ホストとESXiハイパーバイザーホストの両方でサポートされます。ONTAPONTAP Select 9.16.1および9.15.1では、クラスタの拡張と縮小はESXiハイパーバイザーホストでのみサポートされます。
+
--
既存のONTAP Selectクラスタのクラスタ拡張および縮小機能を使用して、6 ノード クラスタから 8 ノード クラスタにサイズを拡大したり、8 ノード クラスタから 6 ノード クラスタにサイズを縮小したりできます。

link:task_cluster_expansion_contraction.html["クラスタの拡張と縮小、およびサポートされている KVM と ESXi ハイパーバイザーのバージョンについて学習します。"] 。

--
ESXiホスト上のクラスタ拡張と縮小のサポート強化:: ONTAP Select 9.17.1 以降では、ESXi ホスト上の 6 ノード クラスタと 12 ノード クラスタ間でのクラスタの拡張と縮小がサポートされます。
+
--
--
既存の ESXi クラスタのクラスタ サイズを次の増分単位で増やすことができます。

* 6ノードから8、10、12ノードへ
* 8ノードから10または12ノードへ
* 10から12ノード


既存の ESXi クラスタのクラスタ サイズを次の増分単位で減らすことができます。

* 12ノードから10、8、または6ノードへ
* 10ノードから8または6ノードへ
* 8ノードから6ノードへ


--
link:task_cluster_expansion_contraction.html["クラスタの拡張と縮小、およびサポートされている KVM と ESXi ハイパーバイザーのバージョンについて学習します。"] 。

--
SnapMirrorクラウドのサポート:: ONTAP Select 9.17.1 以降、 SnapMirrorクラウドがONTAP Selectでサポートされます。SnapMirrorSnapMirrorは、 ONTAP Select 9.17.1 クラスタを導入するか、既存のONTAP Selectクラスタをバージョン 9.17.1 にアップグレードすると、デフォルトで有効になるライセンス対象のONTAP機能です。
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["オブジェクトストレージへのSnapMirrorクラウドバックアップについて学ぶ"^] 。

--
SnapLock Select Enterprise のサポート:: ONTAP Select 9.17.1 以降、新しい導入ではSnapLock Select Enterprise（改ざん防止スナップショット ロックを含む）のライセンスが自動的に付与されます。  ONTAP Select 9.16.1以前からのアップグレードの場合は、 SnapLock Selectライセンスをlink:https://mysupport.netapp.com/site/["NetApp Support Site"^]手動で適用します。
マルチノードクラスタでの vSAN ESA のサポート:: ONTAP Select 9.17.1 以降では、vSAN Express Storage Architecture (ESA) のサポートが拡張され、マルチノード クラスタを展開できるようになりました。この機能強化により、vSAN ESA 構成をデプロイできるようになります。
+
--
vSAN ESA は ESX 固有の構成であり、vSphere 8 で導入された VMware vSAN の新しいアーキテクチャです。vSAN ESA は、特に NVMe ベースの TLC フラッシュ デバイスを使用する場合に、強化された効率、スケーラビリティ、およびパフォーマンスを提供するように設計されています。

ONTAP Select Deploy およびONTAP Select for ESX は、ストレージ プールに vSAN または外部アレイ タイプのデータストアを使用して、 ONTAP Selectシングルノードおよびマルチノード クラスタの構成をサポートします。

[NOTE]
====
コンテンツ ライブラリの操作を実行するには、追加の権限レベルにアクセスする必要があります。制限されたロールで作業している場合、vSAN ESA の展開にはこれが必要です。

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["コンテンツライブラリ操作のアクセス権限レベルについて学習します"^] 。

====
--
NDAドライバーのサポートを更新:: ONTAP Select 9.17.1以降、NVD（NVMe Expressディスクドライバ）に代わってFreeBSD NDA（NVMe Direct Access）デバイスドライバが導入されました。FreeBSDドライバは、NVMeコマンドプロトコルを実装することで、ダイレクトアクセスデバイスのサポートを提供します。ONTAPONTAP Select 9.17.1クラスタを導入する場合、または既存のONTAP Selectクラスタをバージョン9.17.1にアップグレードする場合、NVMeデバイスの設定時にFreeBSDドライバがデフォルトで起動されます。
+
--
ONTAP Select 9.16.1 以前では、NVD は引き続きONTAP Select展開内の NVMe デバイスのサポートを提供します。

--
KVMハイパーバイザーのサポートの更新:: ONTAP Select 9.17.1 以降、KVM ハイパーバイザーは Red Hat Enterprise Linux (RHEL) 9.6 および Rocky Linux 9.6 でサポートされます。
VMware ESXiのサポートを強化:: ONTAP Select 9.17.1 には、VMware ESXi 9.0 のサポートが含まれています。




== ONTAP Select 9.16.1

NetAppライセンスファイルのサポートの更新:: ONTAP Select 9.16.1以降では、NetAppライセンスファイル（NLF）のサポートが更新されています。新しいNLF形式には、ARP、ONTAP S3、およびS3 SnapMirror機能のライセンスが含まれています。link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["詳細はこちら。"]です。
+
--
新しいONTAP Select 9.16.1 Deployでは、新しいNLF形式が自動的に適用されます。既存のONTAP Select Deployを9.16.1にアップグレードすると、新しいNLF形式は適用されません。ARP、ONTAP S3、およびS3 SnapMirror機能のライセンスを取得するには、アップグレード後に更新されたNLFをダウンロードする必要があります。ONTAP Select 9.15.1以前にリバートする場合は、アップグレード前に使用していた機能ライセンスを再インストールする必要があります。

--
自律型ランサムウェア対策のサポート:: ONTAP Select 9.16.1では、自律型ランサムウェア対策（ARP）がサポートされるようになりました。ONTAP Select 9.16.1はARPの手動更新のみをサポートし、自動更新はサポートされません。ARP機能ライセンスは、ONTAP Select 9.16.1のNLFに含まれています。link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["詳細はこちら。"]です。
VMware ESXiのサポートを強化:: ONTAP Select 9.16.1では、VMware ESXi 8.0 U3がサポートされています。
KVMハイパーバイザーのサポートの更新:: ONTAP Select 9.16.1 以降、KVM ハイパーバイザーは RHEL 9.5 および Rocky Linux 9.5 でサポートされます。




== ONTAP Select 9.15.1

KVMハイパーバイザーのサポートの更新:: ONTAP Select 9.15.1以降では、カーネルベースの仮想マシン（KVM）ハイパーバイザーがRHEL 9.4およびRocky Linux 9.4でサポートされます。
クラスタの拡張と縮小のサポート:: ONTAP Select 9.15.1以降では、クラスタの拡張と縮小がサポートされます。
+
--
* 6ノオトクラスタカラ8ノオトクラスタヘノクラスタノカクチヨウ
+
クラスタ拡張機能を使用して、クラスタサイズを6ノードクラスタから8ノードクラスタに拡張できます。1ノード、2ノード、または4ノードのクラスタから6ノードまたは8ノードのクラスタへのクラスタの拡張は、現在サポートされていません。link:task_cluster_expansion_contraction.html#expand-the-cluster["詳細はこちら。"]です。

* 8ノードから6ノードへのクラスタの縮小
+
クラスタ収縮機能を使用して、クラスタサイズを8ノードクラスタから6ノードクラスタに縮小できます。6ノードまたは8ノードのクラスタから1ノード、2ノード、または4ノードのクラスタへのクラスタ収縮は現在サポートされていません。link:task_cluster_expansion_contraction.html#contract-the-cluster["詳細はこちら。"]です。



--



NOTE: クラスタの拡張と縮小はESXクラスタのみでサポートされます。



== ONTAP Select 9.14.1

KVMハイパーバイザーのサポート:: ONTAP Select 9.14.1以降では、KVMハイパーバイザーのサポートが再開されました。これまでのONTAP Select 9.10.1では、KVMハイパーバイザーへの新しいクラスタの導入がサポートされなくなり、ONTAP Select 9.11.1では、オフラインへの切り替えや削除を除く既存のKVMクラスタとホストの管理がサポートされなくなりました。
VMware vCenterプラグインの導入のサポート終了:: ONTAP Select 9.14.1以降では、Deploy VMware vCenterプラグインはサポートされなくなりました。
ONTAP Select Deployサポートの更新:: Deploy 9.14.1P2よりも前のバージョンのONTAP Select Deploy 9.14.1を実行している場合は、できるだけ早くONTAP Select Deploy 9.14.1P2にアップグレードする必要があります。詳細については、を参照してください link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1リリースノート"^]。
VMware ESXiのサポートを強化:: ONTAP Select 9.14.1では、VMware ESXi 8.0 U2がサポートされています。




== ONTAP Select 9.13.1

NVMe over TCPのサポート:: ONTAP Select 9.13.1にアップグレードする場合は、NVMe over TCPをサポートする新しいライセンスが必要です。このライセンスは、バージョン9.13.1からONTAP Selectを初めて導入するときに自動的に含まれます。
VMware ESXiのサポートを更新:: VMware.13.1以降では、ONTAP 9 8.0.1 GA（ビルド20513097）がハードウェアバージョン4以降でサポートされます。
ONTAP Select Deployサポートの更新:: 2024年4月以降、ONTAP Select Deploy 9.13.1はNetApp Support Siteで利用できなくなりました。ONTAP Select Deploy 9.13.1を実行している場合は、できるだけ早くONTAP Select Deploy 9.14.1P2にアップグレードする必要があります。詳細については、を参照してください link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1リリースノート"^]。




== ONTAP Select 9.12.1

ONTAP Select 9.12.1は、現在のコアONTAP 製品のリリースに新しく開発されたほとんどの機能を活用しています。ONTAP Select 固有の新機能や機能強化は含まれていません。

2024年4月以降、ONTAP Select Deploy 9.12.1はNetApp Support Siteで利用できなくなりました。ONTAP Select Deploy 9.12.1を実行している場合は、できるだけ早くONTAP Select Deploy 9.14.1P2にアップグレードする必要があります。詳細については、を参照してください link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1リリースノート"^]。



== ONTAP Select 9.11.1

VMware ESXiのサポートを強化:: ONTAP Select 9.11.1では、VMware ESXi 7.0 U3Cがサポートされています。
VMware NSX のサポート:: ONTAP Select 9.10.1以降のリリースは、VMware NSX -Tバージョン3.1.2に対応しています。OVAファイルとONTAP Select Deploy管理ユーティリティを使用して導入されたONTAP Select シングルノードクラスタでNSXとTを使用しても、機能の問題や不具合は発生しません。ただし、ONTAP Select マルチノードクラスタでNSXとTを使用する場合は、ONTAP Select 9.11.1で次の制限事項に注意する必要があります。
+
--
* ネットワーク接続チェッカー
+
NSX ベースのネットワークに対して実行されると、 Deploy CLI で使用可能なネットワーク接続チェッカーが失敗します。



--
KVM ハイパーバイザーのサポートが廃止されました::
+
--
* ONTAP Select 9.10.1以降、KVMハイパーバイザーに新しいクラスタを導入することはできなくなりました。
* ONTAP Select 9.11.1以降では、既存のKVMクラスタおよびホストですべての管理機能を使用できなくなりました。ただし、Take offline機能とdelete機能は除きます。
+
ネットアップでは、ONTAP Select for KVMからONTAP Select for ESXiを含む他のONTAP プラットフォームへの完全なデータ移行を計画し、実行することを強く推奨します。詳細については、を参照してください https://mysupport.netapp.com/info/communications/ECMLP2877451.html["販売終了通知"^]



--




== ONTAP Select 9.10.1

VMware NSX のサポート:: ONTAP Select 9.10.1 は VMware NSX -T バージョン 3.1.2 に対応しています。OVAファイルとONTAP Select Deploy管理ユーティリティを使用して導入されたONTAP Select シングルノードクラスタでNSXとTを使用しても、機能の問題や不具合は発生しません。ただし、 NSX と ONTAP Select マルチノードクラスタを併用する場合は、次の要件および制限事項に注意してください。
+
--
* クラスタ MTU
+
追加のオーバーヘッドを考慮してクラスタを導入する前に、クラスタの MTU サイズを 8800 に手動で調整する必要があります。VMware のガイダンスでは、 NSX を使用する場合に 200 バイトのバッファを使用できるようにする方法を説明しています

* ネットワーク 4x10Gb 構成
+
4 つの NIC が設定された VMware ESXi ホストに ONTAP Select を導入する場合、 Deploy ユーティリティから、 2 つの異なるポートグループに内部トラフィックを分割し、 2 つの異なるポートグループに外部トラフィックを分けるというベストプラクティスに従うように求められます。ただし、オーバーレイネットワークを使用する場合、この設定は機能しないため、推奨事項は無視してください。この場合は、内部ポートグループを 1 つと外部ポートグループを 1 つだけ使用してください。

* ネットワーク接続チェッカー
+
NSX ベースのネットワークに対して実行されると、 Deploy CLI で使用可能なネットワーク接続チェッカーが失敗します。



--
KVM ハイパーバイザーのサポートが廃止されました:: ONTAP Select 9.10.1 以降、 KVM ハイパーバイザーに新しいクラスタを導入することはできなくなりました。ただし、クラスタを以前のリリースから 9.10.1 にアップグレードしても、 Deploy ユーティリティを使用してクラスタを管理できます。




== ONTAP Select 9.9.1

プロセッサー・ファミリーのサポート:: ONTAP Select 9.9.1以降では、インテルXeon Sandy Bridge以降のCPUモデルのみがONTAP Selectでサポートされます。
VMware ESXiのサポートを更新:: VMware ESXiのサポートは、ONTAP Select 9.9..1で強化されました。次のリリースがサポートされるようになりました。
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

高速インターフェイス:: 高速インターフェイス機能は、25G（25GbE）と40G（40GbE）の両方にオプションを提供することで、ネットワーク接続を強化します。この速度を高速で使用する場合のパフォーマンスを最大限に高めるには、ONTAP Select のドキュメントに従ってポートマッピング設定のベストプラクティスに従う必要があります。
VMware ESXiのサポートを更新:: ONTAP Select 9.8については、VMware ESXiのサポートに関して2つの変更があります。
+
--
* ESXi 7.0がサポートされる（GAビルド15849807以降）
* ESXi 6.0はサポートされなくなりました


--

