---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: VMware 環境に関連するハードウェア要件と計画の問題がいくつかあります。 
---
= ONTAP SelectのVMwareハイパーバイザーとハードウェアに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware 環境に関連するハードウェア要件と計画の問題がいくつかあります。



== ハイパーバイザーの要件

ONTAP Select を実行するハイパーバイザーに関連する要件がいくつかあります。


NOTE: 確認すべきはlink:reference_release_notes.html["ONTAP Select リリースノート"]追加の既知の制限事項や制約事項については、こちらをご覧ください。



=== VMware ライセンス

ONTAP Select クラスタを導入するには、 ONTAP Select を実行するハイパーバイザーホストの有効な VMware vSphere ライセンスが必要です。導入に適したライセンスを使用してください。



=== ソフトウェアの互換性

ONTAP Select は、 KVM および ESXi ハイパーバイザーに導入できます。

[role="tabbed-block"]
====
.KVM の略
--
ONTAP Select は、次の KVM ハイパーバイザー バージョンをサポートしています。

* Red Hat Enterprise Linux（RHEL）10.1、10.0、9.7、9.6、9.5、9.4、9.2、9.1、9.0、8.8、8.7、および8.6上のKVM
* Rocky Linux 10.0、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7、および 8.6 上の KVM


[NOTE]
====
RHEL 10.1、10.0、およびRocky Linux 10.0ホスト上のKVMハイパーバイザーには、ソフトウェアRAIDワークフローの制限があります。詳細については、以下のナレッジベースの記事をご覧ください：

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: RHEL 10 および ROCKY 10 を使用してクラスタ HWR を作成中に警告メッセージが表示される"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: RHEL10/Rocky 10 を搭載したホスト上のクラスタ作成ページで、SWR のストレージ プールとストレージ ディスクが表示されない"^]


====
--
.ESXi
--
ONTAP Select は、次の ESXi ハイパーバイザー バージョンをサポートしています。

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1（ビルド21495797）
* VMware ESXi 8.0 GA（ビルド20513097）



NOTE: VMware でも同じバージョンがサポートされていれば、特定されたバージョンの ESXi で ONTAP Select がサポートされます。


NOTE: ESXi 7.0 GA は、提供終了ステータスに達しました。このバージョンのONTAP Selectクラスタを使用している場合は、 https://mysupport.netapp.com/matrix["Interoperability Matrix Tool （ IMT ）"^] 。

--
====


=== VMware vCenter およびスタンドアロンの ESXi ホスト

ESXi ハイパーバイザーホストが vCenter サーバで管理されている場合は、 vCenter のクレデンシャルを使用して、ホストを Deploy 管理ユーティリティに登録する必要があります。ESXi のクレデンシャルを使用してホストをスタンドアロンホストとして登録することはできません。



== コアハードウェアの要件

ONTAP Select を導入する物理ハイパーバイザーホストが、いくつかのハードウェア要件を満たしている必要があります。ハードウェアの最小要件を満たしていれば、ハイパーバイザーホストに対して任意のプラットフォームを選択できます。サポートされているハードウェアプラットフォームは、 Cisco 、 Dell 、 HP 、富士通、 Lenovo 、 と Supermicro です。


NOTE: ONTAP Select 9.9.1 以降では、Intel Xeon Sandy Bridge 以降に基づく CPU モデルのみがサポートされます。

詳細については、を参照して https://mysupport.netapp.com/matrix["Interoperability Matrix Tool、window=_blank"]ください。



=== 基本的なハードウェア要件

ノードインスタンスのタイプやライセンスサービスに関係なく、すべてのプラットフォームに適用される共通のハードウェア要件がいくつかあります。

.プロセッサ
サポートされているマイクロプロセッサには、サーバー向けIntel Xeonプロセッサが含まれます。 link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["インテル Xeon プロセッサー、ウィンドウ = _ ブランク"]詳細についてはこちらをご覧ください。


NOTE: Advanced Micro Devices (AMD)プロセッサはONTAP Selectではサポートされていません。

.イーサネット構成
クラスタのサイズに基づいて、サポートされるイーサネット構成がいくつかあります。

[cols="2,3,3"]
|===
| クラスタサイズ | 最小要件 | スイシヨウヨウケン 


| シングルノードクラスタ | 1GbE×2 | 10GbE × 2 


| 2ノードクラスタまたはMetroCluster SDS | 1GbE×4または10GbE×1 | 10GbE × 2 


| 4、6、8、10、または12ノードのクラスタ | 10GbE × 2 | 10GbE×4、または25/40GbE×2 
|===


=== インスタンスタイプに基づいた追加のハードウェア要件

ノードインスタンスのタイプに基づいて、ハードウェアに関する追加の要件がいくつかあります。

を参照してください link:concept_lic_platforms.html["プラットフォームのライセンス製品を理解する"] を参照してください。

[cols="a1,a2,a2,a2"]
|===
| ノードサイズ | CPUコア | メモリ | 必要なプラットフォームライセンスの提供 


| 小規模 | 6 個以上の物理コア（うち 4 個はONTAP Select用に予約） | 24GB以上、16GBはONTAP Select用に予約済み | スタンダード、プレミアム、プレミアムXL 


| 中 | 10 個以上の物理コア（うち 8 個はONTAP Select用に予約） | 72GB以上、64GBはONTAP Select用に予約済み | プレミアムまたはプレミアムXL 


| 大規模 | 18 個以上の物理コア（うち 16 個はONTAP Select用に予約） | 136GB以上、128GBはONTAP Select用に予約済み | Premium XL 
|===

NOTE: プラットフォームライセンスに基づいて追加のディスクが必要になります。を参照してください link:reference_plan_ots_storage.html["ストレージと RAID"] を参照してください。
