---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: ONTAP Select に関するよくある質問とその回答をご確認ください。 
---
= よくある質問
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select に関するよくある質問とその回答を確認できます。


NOTE: ONTAP Select 9.10.1以降では、新しいクラスタの作成時にKVMハイパーバイザーがサポートされなくなりました。また、9.11.1以降では、KVM上の既存のONTAP Select クラスタを管理できなくなりました。KVMに関する質問は、KVMをサポートする以前のリリースにのみ該当します。



== 全般

一般的な質問と回答がいくつかあります。

ONTAP Deploy は、 ONTAP Select クラスタの作成に使用するユーティリティです。現時点では、本番環境クラスタの作成に使用できるのは ONTAP Deploy のみです。また、 ONTAP Deploy を使用して評価用の Select クラスタを作成し、クライアントが本番環境の実際の手順をテストして文書化できるようにすることもできます。また、 ONTAP Deploy は、評価時に消費されるスペースに十分な容量を持つ適切な大容量階層ライセンスを使用して、評価用クラスタを本番環境のクラスタに変換することもできます。

ONTAP Deploy は、 ONTAP Select のイメージが格納された仮想マシンです。クラスタのインストール時に、 ONTAP Deploy はいくつかのチェックを実施して、 ONTAP Select の最小要件が満たされていることを確認します。ONTAP Deploy VM と Select クラスタは別々にアップグレードできます。

FAS の ONTAP と同様に、 Perfstat ユーティリティを使用してパフォーマンスデータを収集する必要があります。コマンドの例を次に示します。

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.ONTAP Deploy の Swagger API ページにアクセスする方法を教えてください。
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: API v3 リリースは、以前のバージョンの API と後方互換性がありません。新しい API ガイドはにあります https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["Field Portal"]。

いいえONTAP Select VM は、 VMware ベースの Snapshot から除外される独立した永続的ドライブを使用します。ONTAP Select のバックアップ方法としてサポートされているのは、 SnapMirror 、 SnapVault 、または SVM DR （該当する場合）のみです。

連絡先 link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"]。



== ライセンス、インストール、アップグレード、およびリバート

ライセンス、インストール、アップグレード、および復元に関するいくつかの質問と回答があります。

はい。ONTAP Deploy ユーティリティは、 ONTAP Select クラスタとは別にアップグレードできます。同様に、 Select クラスタも ONTAP Deploy ユーティリティとは別にアップグレードできます。

はい。 Select クラスタのアップグレード手順 は FAS クラスタのアップグレードと同じですが、 ONTAP Select アップグレードバイナリは FAS のアップグレードバイナリの ONTAP とは別のダウンロードです。

はい、 ONTAP Select クラスタのリバート手順 は、 FAS クラスタのリバート手順 とほぼ同じです。ただし、いくつかの違いがあります。

* リバートできるのは、アップグレードされた ONTAP Select インスタンスのみで、元のインストールバージョンのみです。ONTAP Select が以前のリリースをサポートしていても、新しいインストールは古いコードリリースに戻すことはできません。
* ソフトウェア RAID を使用する ONTAP Select （ KVM ）および ONTAP Select （ ESX ）の場合、ソフトウェア RAID をサポートしていない以前のバージョンにリバートすることはできません。さらに、 ESX への ONTAP Select 9.5 以降の新規インストールでは、 VMXNET3 ネットワークドライバおよび可能な場合は vNMVE ドライバが使用されます。これらの新規インストールを以前のバージョンの ONTAP Select にリバートすることはできません。
* ONTAP Select VM も（ Premium XL ライセンスを使用して）大規模なインスタンスにアップグレードされた場合、以前のバージョンでは大規模なインスタンス機能は使用できないため、 9.6 より前のバージョンにリバートすることはできません。


はい。

ONTAP Deploy は、 GUI 、 CLI 、または REST API から実行できるクラスタ更新処理を使用して、次の ONTAP Select クラスタプロパティへの変更を認識します。

* ネットワークの設定（ IP アドレス、 DNS 、 NTP 、ネットマスク、ゲートウェイ）
* ONTAP Select クラスタ、ノード名、およびバージョン


次の ONTAP Select VM の変更も認識されます。

* ONTAP Select VM の名前と状態の変更（オンラインやオフラインなど）
* ホストのネットワーク名とストレージプール名が変更された



NOTE: ONTAP Deploy VM の IP アドレスの変更はサポートされていません。

ONTAP Deploy 2.6 にアップグレードすると、導入済みだが元の構成からは変更されていない ONTAP Select クラスタに対して、これらの変更をサポートできるようになります。つまり、上記の ONTAP Select クラスタプロパティが System Manager または vCenter を使用して変更された場合、 ONTAP Deploy 2.6 にアップグレードしても、これらの不整合は修正されません。ONTAP Deploy によって一意のメタデータが各 ONTAP Select VM に追加されるようにするには、 ONTAP Select プロパティの変更を最初にロールバックする必要があります。



== ストレージ

ストレージに関するいくつかの質問と回答があります。

はい。ONTAP Deploy は KVM または ESX にインストールできます。両方のインストール環境で、どちらのハイパーバイザーにも ONTAP Select クラスタを作成できます。

ESX ホストのライセンスが適切な場合は、 ESX ホストを vCenter Server で管理する必要はありません。ただし、ホストが vCenter サーバで管理されている場合は、その vCenter Server を使用するように ONTAP Deploy を設定する必要があります。つまり、 ESX ホストが vCenter Server によってアクティブに管理されている場合、 ONTAP Deploy で ESX ホストをスタンドアロンとして設定することはできません。ONTAP Deploy VM は、 vMotion または VMware の HA イベントが原因で、 vCenter に依存して ESXi ホスト間のすべての ONTAP Select VM 移行を追跡します。

ONTAP Select では、ハードウェアRAIDコントローラなしでサーバを使用できます。この場合、RAID機能はソフトウェアで実装されます。ソフトウェアRAIDを使用する場合は、SSDとNVMeの両方のドライブがサポートされます。ONTAP Select ブートディスクおよびコアディスクは、引き続き仮想化されたパーティション（ストレージプールまたはデータストア）内に配置する必要があります。ONTAP Select は、 RD2 （ルート / データ / データパーティショニング）を使用して SSD をパーティショニングします。したがって、 ONTAP Select ルートパーティションは、データアグリゲートに使用される物理スピンドルと同じ上にあります。ただし、ルートアグリゲートおよびブートディスクとコア仮想ディスクは容量ライセンスには含まれません。

AFF / FAS で使用できるすべての RAID 方式を ONTAP Select でも使用できます。これには、 RAID 4 、 RAID DP 、および RAID-TEC が含まれます。SSD の最小数は、選択した RAID 構成のタイプによって異なります。ベストプラクティスとして、少なくとも 1 つのスペアが必要です。スペアディスクとパリティディスクは容量ライセンスには含まれません。

ソフトウェア RAID は、 ONTAP ソフトウェアスタックのレイヤです。ソフトウェア RAID では、物理ドライブが ONTAP Select VM 内でパーティショニングされ、 raw ディスクとして使用できるため、管理性が向上します。一方、ハードウェア RAID では、通常は 1 つの大きな LUN を使用でき、その LUN を ONTAP Select で使用して VMDISK を作成できます。ソフトウェア RAID はオプションとして使用でき、ハードウェア RAID の代わりに使用できます。

ソフトウェア RAID の要件には、次のものがあります。

* ESXとKVMでサポート（ONTAP Select 9.10.1より前）
* サポートされる物理ディスクのサイズ： 200GB~32TB
* DAS 構成でのみサポートされます
* SSDまたはNVMeでサポートされます
* Premium または Premium XL ONTAP Select ライセンスが必要です
* ハードウェア RAID コントローラがないか無効になっているか、 SAS HBA モードで動作している必要があります
* システムディスクのコアダンプ、ブート / NVRAM 、メディエーターなどに、専用の LUN に基づく LVM ストレージプールまたはデータストアを使用する必要があります。


KVM にインストールするときは、単一のボンドと単一のブリッジを使用する必要があります。物理ポートが 2 つまたは 4 つあるホストでは、すべてのポートを同じボンドに含める必要があります。

ハードウェア RAID コントローラを使用する場合、 ONTAP Select は、基盤となるサーバの問題をほとんど認識しません。ベストプラクティスに従ってサーバを設定する場合は、ある程度の冗長性が必要です。ドライブ障害に備えて RAID 5/6 を使用することを推奨します。ソフトウェア RAID 構成の場合、 ONTAP はディスク障害に関するアラートを発行し、スペアドライブがある場合は、ドライブのリビルドを開始します。

ネットワークレイヤでの単一点障害を回避するために、 2 つ以上の物理 NIC を使用する必要があります。ネットアップでは、データポートグループ、管理ポートグループには NIC チーミングとボンディングを設定し、チームまたはボンドに 2 つ以上のアップリンクを使用することを推奨します。このような構成により、アップリンクに障害が発生した場合に、仮想スイッチは、障害が発生したアップリンクから NIC チーム内の正常なアップリンクにトラフィックを移動します。推奨されるネットワーク構成の詳細については、を参照してください link:ct_nw_supported_configuraitons.html#network-configuration-best-practices["ネットワーク構成のベストプラクティス"]。

2 ノードクラスタまたは 4 ノードクラスタの場合、それ以外のエラーはすべて ONTAP HA で処理されます。ハイパーバイザーサーバを交換する必要があり、 ONTAP Select クラスタを新しいサーバで構成する必要がある場合は、ネットアップテクニカルサポートにお問い合わせください。

VSAN を含むすべての構成で、 ONTAP Select ノードあたり 400TB のストレージがサポートされます。

サポートされる最大サイズを超えるデータストアにインストールする場合は、製品のセットアップ時に容量の上限を使用する必要があります。

ONTAP Deploy には、 ONTAP Select ノードでの容量拡張処理をサポートするストレージ追加ワークフローが含まれています。管理下でストレージを拡張するには、同じデータストアのスペースを使用するか（使用可能なスペースが残っている場合）、別のデータストアのスペースを追加します。ローカルデータストアとリモートデータストアを同じアグリゲートに混在させることはできません。

ストレージの追加はソフトウェア RAID もサポートします。ただし、ソフトウェア RAID の場合は、 ONTAP Select VM に物理ドライブを追加する必要があります。この場合のストレージ追加は、 FAS または AFF アレイの管理と似ています。ソフトウェア RAID を使用して ONTAP Select ノードにストレージを追加する場合は、 RAID グループのサイズとドライブサイズを考慮する必要があります。

ONTAP Deploy および ONTAP Select for ESX では、 VSAN または外付けアレイタイプのデータストアをストレージプールに使用する ONTAP Select シングルノードクラスタの構成をサポートしています。

ONTAP Deploy および ONTAP Select for KVM では、外部アレイで共有論理ストレージプールタイプを使用する ONTAP Select シングルノードクラスタの設定がサポートされます。ストレージプールのベースには iSCSI と FC / FCoE があります。それ以外のタイプのストレージプールはサポートされません。

共有ストレージ上のマルチノード HA クラスタがサポートされます。

外付けストレージ（マルチノード VNAS ）を使用するマルチノードクラスタは、 ESX と KVM の両方でサポートされます。同じクラスタ内にハイパーバイザーを混在させることはサポートされていません。共有ストレージ上の HA アーキテクチャは、 HA ペア内の各ノードにパートナーデータのミラーコピーがあることを意味します。ただし、マルチノードクラスタを使用すると、 ONTAP HA または KVM Live Motion を使用するシングルノードクラスタに比べて、のノンストップオペレーションのメリットが得られます。

ONTAP Deploy は同じホスト上の複数の ONTAP Select VM のサポートを追加しますが、クラスタの作成時にこれらのインスタンスを同じ ONTAP Select クラスタに含めることはできません。ESX 環境については、 VMware HA が同じ ONTAP Select クラスタから 1 つの ESX ホストに複数の ONTAP Select VM を移行しないように、 VM の非アフィニティルールを作成することを推奨します。さらに、 ONTAP Deploy は、管理（ユーザが開始） vMotion または ONTAP Select VM のライブマイグレーションが検出された場合、 2 つの ONTAP Select ノードが同じ物理ホストで終了するなどのネットアップのベストプラクティスに違反したとみなされます。 ONTAP Deploy は、 Deploy の GUI およびログにアラートを送信します。ONTAP Deploy が ONTAP Select VM の場所を認識する唯一の方法は、クラスタ更新処理によってです。これは、 ONTAP Deploy 管理者が手動で実行する必要がある処理です。プロアクティブな監視を可能にする ONTAP Deploy には機能がなく、 Deploy の GUI またはログにのみアラートが表示されます。つまり、このアラートを集中型の監視インフラストラクチャに転送することはできません。

NSX と V の VXLAN ポートグループがサポートされます。マルチノード HA （ ONTAP MetroCluster SDS を含む）の場合は、 VXLAN のオーバーヘッドに対応するために、内部ネットワーク MTU を（ 9000 ではなく） 7500 ～ 8900 の範囲で設定する必要があります。内部ネットワーク MTU は、クラスタの導入時に ONTAP Deploy で設定できます。

外部アレイストレージプールで実行される ONTAP Select VM は、 virsh ライブマイグレーションをサポートします。

いいえ。外付けアレイ構成と VSAN 構成のどちらがオールフラッシュであるかに関係なく、すべてのバージョンがサポートされます。

Select VM は VSAN データストアのストレージポリシーを継承し、 FTT / FTM の設定に制限はありません。ただし、 FTT / FTM の設定によっては、 ONTAP Select VM のサイズがセットアップ時に設定した容量よりも大幅に大きくなる可能性があることに注意してください。ONTAP Select は、セットアップ時に作成される eager-zeroed-thick VMDK を使用します。同じ共有データストアを使用する他の VM への影響を回避するためには、 Select の容量と FTT / FTM の設定から導き出された実際の Select VM のサイズに対応できる十分な空き容量をデータストアに確保することが重要です。

vNAS 構成では、同じホスト上の複数の ONTAP Select ノードを vNAS 構成でのみ設定できます。ただし、それらのノードが同じ ONTAP Select クラスタに含まれていない必要があります。この方法は DAS 構成ではサポートされていません。同じ物理ホスト上の複数の ONTAP Select ノードが RAID コントローラへのアクセスで競合するためです。

1 つの 10GE ポートを使用して外部ネットワークに接続できます。ただし、この方法は、制約のあるスモールフォームファクタ環境でのみ使用することを推奨します。これは ESX と KVM の両方でサポートされます。

CLVM および Pacemaker （ PC ）コンポーネントは、ライブマイグレーションに参加する各ホストにインストールして実行する必要があります。これは、各ホストで同じボリュームグループにアクセスするために必要です。



== vCenter

VMware vCenterに関するいくつかの質問と回答があります。

ONTAP Deploy は、 VMware VIX API を使用して vCenter や ESX ホストと通信します。VMware のドキュメントでは、 vCenter Server または ESX ホストへの初期接続には、 TCP ポート 443 上の HTTPS/SOAP を使用します。これは、 TLS / SSL を介したセキュア HTTP のポートです。次に、 ESX ホストへの接続が TCP ポート 902 のソケットで開かれます。この接続を経由するデータは SSL で暗号化されます。また、 ONTAP Deploy は ping コマンドを発行して、指定した IP アドレスで応答する ESX ホストがあることを確認します。

ONTAP Deploy は、次のように ONTAP Select ノードおよびクラスタ管理 IP アドレスと通信できる必要もあります。

* Ping
* SSH （ポート 22 ）
* SSL （ポート 443 ）


2 ノードクラスタの場合、 ONTAP Deploy はクラスタのメールボックスをホストします。各 ONTAP Select ノードは、 iSCSI （ポート 3260 ）を使用して ONTAP Deploy にアクセスできる必要があります。

マルチノードクラスタの場合、内部ネットワークを完全に開く必要があります（ NAT やファイアウォールは使用しない）。

必要な vCenter 権限の一覧については、以下を参照してください。 link:reference_plan_ots_vcenter.html["VMware vCenter サーバ"]。

vCenter Server の ONTAP Deploy 機能を ONTAP Deploy プラグインと統合することができます。このプラグインは、 ONTAP Deploy に代わるものではありません。代わりに、 ONTAP Deploy はバックグラウンドで動作します。 vCenter 管理者は、 ONTAP Deploy のほとんどの機能をプラグインで呼び出すことができます。一部の ONTAP Deploy 処理は CLI でのみ実行できます。

特定の vCenter サーバにプラグインを登録できる ONTAP Deploy VM は 1 台だけです。

vCenter の管理者および IT ジェネラリストは、 vCenter HTML5 GUI を使用して ONTAP Select クラスタを作成できます。Flash vCenter GUI はサポートされていません。

また、 ONTAP Deploy が vCenter RBAC を認証に使用できるようにします。ONTAP Deploy プラグインを使用するための vCenter 権限が付与されたユーザには、そのユーザの vCenter アカウントが ONTAP Deploy 管理ユーザにマッピングされている。ONTAP Deploy はすべての処理のユーザ ID をログに記録し、次のファイルを基本的な監査ログとして使用できます。

[listing]
----
nginx_access.log
----


== HA およびクラスタ

HAペアとクラスタに関するいくつかの質問と回答があります。

ONTAP Deploy VM が主にクラスタの作成に使用される 4 ノード、 6 ノード、および 8 ノードクラスタとは異なり、 2 ノードクラスタは、 HA クォーラム用に ONTAP Deploy VM を継続的に利用します。ONTAP Deploy VM が使用できない場合、フェイルオーバーサービスは無効になります。

MetroCluster SDS は、ネットアップの MetroCluster ビジネス継続性ソリューションのカテゴリに分類される、低コストの同期レプリケーションオプションです。FAS ハイブリッドフラッシュ、 AFF 、クラウド向け NetApp Private Storage 、および NetApp FlexArray ® テクノロジで利用できる NetApp MetroCluster とは異なり、 ONTAP Select でのみ利用できます。

MetroCluster SDS は、同期レプリケーション解決策 を提供し、ネットアップの MetroCluster ソリューションに該当します。ただし、主な違いは、サポートされる距離（約 10km と 300km ）と接続タイプ（ FC と IP ではなく IP ネットワークのみがサポート）です。

2 ノードクラスタとは、同じデータセンター内にある 2 つのノードが相互に 300m 以内の範囲にあるクラスタです。一般に、両方のノードには、スイッチ間リンクで接続された同じネットワークスイッチまたは一連のネットワークスイッチへのアップリンクがあります。

2 ノード MetroCluster SDS は、ノードが物理的に分離され（異なる部屋、異なる建物、または異なるデータセンター）、各ノードのアップリンク接続が別々のネットワークスイッチに接続されているクラスタとして定義されます。MetroCluster SDS には専用のハードウェアは必要ありませんが、環境ではレイテンシ（ 5 ミリ秒 RTT と 5 ミリ秒ジッター）と物理距離（ 10km ）の観点から一連の最小要件をサポートする必要があります。

MetroCluster SDS はプレミアム機能であり、 Premium または Premium XL ライセンスが必要です。Premium ライセンスは、中小規模の VM のほか、 HDD および SSD メディアの作成をサポートします。これらの構成はすべてサポートされます。

ONTAP MetroCluster SDS は、あらゆるタイプのストレージ構成（ DAS と vNAS ）をサポートします。

はい。ソフトウェア RAID は、 KVM と ESX の両方の SSD メディアでサポートされています。

はい。 Premium ライセンスが必要ですが、このライセンスでは、中小規模の VM 、 SSD と回転式メディアの両方がサポートされます。

いいえ。メディエーターを持つ 2 ノードクラスタのみを MetroCluster SDS として設定できます。

要件は次のとおりです。

* 3 つのデータセンター（ ONTAP Deploy メディエーター用に 1 つ、ノードごとに 1 つ）。
* 5 ミリ秒 RTT と 5 ミリ秒ジッタ。 ONTAP Select ノード間の最大合計 10 ミリ秒と最大物理距離 10 ミリ秒です。
* ONTAP Deploy メディエーターと各 ONTAP Select ノードの間で 125 ミリ秒 RTT 、最小帯域幅 5Mbps
* Premium または Premium XL ライセンス。


VSAN データストアまたは外付けアレイデータストア（ vNAS 環境）上で実行される ONTAP Select VM は、 vMotion 、 DRS 、 VMware HA 機能をサポートします。

Storage vMotion は、シングルノードおよびマルチノードの ONTAP Select クラスタと ONTAP Deploy VM を含むすべての構成でサポートされます。Storage vMotion を使用して、 ONTAP Select または ONTAP Deploy VM を異なる VMFS バージョン（ VMFS 5 から VMFS 6 など）間で移行できますが、このユースケースに限定されません。Storage vMotion 処理を開始する前に VM をシャットダウンすることを推奨します。ONTAP Deploy は、 Storage vMotion 処理の完了後に次の処理を問題 する必要があります。

[listing]
----
cluster refresh
----
異なるタイプのデータストア間での Storage vMotion 処理はサポートされていないことに注意してください。つまり、 NFS タイプのデータストアと VMFS データストア間の Storage vMotion 処理はサポートされません。一般に、外付けデータストアと DAS データストア間の Storage vMotion 処理はサポートされていません。

これらの構成はサポートされていません。ONTAP Select では、クライアントトラフィックを伝送する物理ネットワークアップリンクのステータスは確認できません。したがって、 ONTAP Select は、 HA ハートビートを使用して、 VM がクライアントとそのピアに対して同時にアクセス可能であることを確認します。物理的な接続が失われると、 HA ハートビートを受信できなくなると、もう一方のノードへの自動フェイルオーバーが実行されます。これは望ましい動作です。

HA トラフィックを別の物理インフラに分離することで、 Select VM はピアと通信できますが、クライアントとは通信できません。これにより、自動 HA プロセスが無効になるため、手動フェイルオーバーが開始されるまではデータを使用できなくなります。



== メディエーターサービス

メディエーターサービスに関するいくつかの質問と回答があります。

2 ノードクラスタでは、 ONTAP Deploy VM で HA クォーラムが継続的に利用されます。2 ノードの HA クォーラムネゴシエーションに参加する ONTAP Deploy VM には、メディエーター VM というラベルが付けられます。

はい。2 ノード HA ペアのメディエーターとして機能する ONTAP Deploy は、 500ms RTT の WAN レイテンシをサポートします。最小帯域幅は 5Mbps です。

メディエータートラフィックは iSCSI で、 ONTAP Select ノードの管理 IP アドレスから始まり、 ONTAP Deploy の IP アドレスで終端します。2 ノードクラスタを使用している場合、 ONTAP Select ノード管理 IP アドレスに IPv6 を使用することはできません。

はい。各 ONTAP Deploy VM は、最大 100 個の 2 ノード ONTAP Select クラスタの共通のメディエーターサービスとして機能できます。

はい。別の ONTAP Deploy VM を使用してメディエーターサービスをホストすることができます。

ストレッチ HA 導入モデルでは、メディエーターを備えた 2 ノードクラスタのみがサポートされます。
