---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
summary: 現在のリリースの ONTAP Select には、いくつかの新機能と変更された機能があります。 
---
= ONTAP Select 9.10.1 の新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
現在のリリースの ONTAP Select には、いくつかの新機能と変更された機能があります。



== VMware NSX のサポート

ONTAP Select 9.10.1 は VMware NSX -T バージョン 3.1.2 に対応しています。OVA ファイルと ONTAP Select Deploy 管理ユーティリティを使用して導入された ONTAP Select シングルノードクラスタで NSX と T を使用しても、機能の問題や不具合は発生しません。ただし、 NSX と ONTAP Select マルチノードクラスタを併用する場合は、次の要件および制限事項に注意してください。

クラスタ MTU:: 追加のオーバーヘッドを考慮してクラスタを導入する前に、クラスタの MTU サイズを 8800 に手動で調整する必要があります。VMware のガイダンスでは、 NSX を使用する場合に 200 バイトのバッファを使用できるようにする方法を説明しています
ネットワーク 4x10Gb 構成:: 4 つの NIC が設定された VMware ESXi ホストに ONTAP Select を導入する場合、 Deploy ユーティリティから、 2 つの異なるポートグループに内部トラフィックを分割し、 2 つの異なるポートグループに外部トラフィックを分けるというベストプラクティスに従うように求められます。ただし、オーバーレイネットワークを使用する場合、この設定は機能しないため、推奨事項は無視してください。この場合は、内部ポートグループを 1 つと外部ポートグループを 1 つだけ使用してください。
ネットワーク接続チェッカー:: NSX ベースのネットワークに対して実行されると、 Deploy CLI で使用可能なネットワーク接続チェッカーが失敗します。




== KVM ハイパーバイザーのサポートが廃止されました

ONTAP Select 9.10.1 以降、 KVM ハイパーバイザーに新しいクラスタを導入することはできなくなりました。ただし、クラスタを以前のリリースから 9.10.1 にアップグレードしても、 Deploy ユーティリティを使用してクラスタを管理できます。
