---
sidebar: sidebar 
permalink: reference_plan_ots_vnas.html 
keywords: plan, planning, vnas 
summary: ONTAP Select vNAS の使用に関連するいくつかの計画の問題について考慮する必要があります。 
---
= ONTAP Select vNAS の要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select vNAS は、 ONTAP Select データストアを、 ONTAP Select 仮想マシンを実行するハイパーバイザーホストの外部に配置するための解決策 です。これらのリモートデータストアには、 VMware vSAN または汎用の外付けストレージアレイを使用してアクセスできます。



== 基本的な要件と制限事項

ONTAP Select vNAS 解決策 は、サイズの異なる ONTAP Select クラスタで使用できます。

ハードウェア、ソフトウェア、機能の要件を含む、関連するすべてのストレージコンポーネントは、に記載されている要件に従う必要があります
link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。さらに、ONTAP Selectは、iSCSI、NAS（NFSv3）、ファイバチャネル、Fibre Channel over Ethernetなど、VMware Storage/SAN Compatibilityのドキュメントに記載されているすべての外付けストレージアレイをサポートしています。外付けアレイのサポートは、 ONTAP Select がサポートする ESXi のバージョンによって制限されます。

ONTAP Select vNAS を使用してクラスタを導入する場合は、 VMware の次の機能がサポートされます。

* vMotion
* 高可用性（ HA ）
* Distributed Resource Scheduler （ DRS ）



NOTE: これらの VMware の機能は、シングルノードおよびマルチノードの ONTAP Select クラスタでサポートされています。マルチノードクラスタを導入する場合は、同じクラスタの 2 つ以上のノードが同じハイパーバイザーホストで実行されていないことを確認する必要があります。

VMware の次の機能はサポートされません。

* フォールトトレランス（ FT ）
* 仮想データストア（ VVOL ）




== 設定要件

外付けストレージアレイ（ iSCSI 、ファイバチャネル、 Fibre Channel over Ethernet ）で VMFS データストアを使用する場合は、ストレージを使用するように ONTAP Select を設定する前に、 VMFS ストレージプールを作成しておく必要があります。NFS データストアを使用する場合は、個別の VMFS データストアを作成する必要はありません。すべての vSAN データストアを同じ ESXi クラスタ内で定義してください。


CAUTION: ホストの設定時やストレージの追加処理の実行時には、 VMware vSAN または外付けストレージアレイ上の各データストアの容量制限を指定する必要があります。外付けストレージで許可されるストレージの制限内の容量を指定してください。容量制限を指定しない場合や、ディスク作成処理の際に外付けストレージのスペースが不足している場合は、エラーが発生します。



== ベストプラクティス

利用可能な VMware のマニュアルを参照し、 ESXi ホストの該当するベストプラクティスに従ってください。さらに、次の機能もあり

* ONTAP Select ネットワークと外付けストレージ（ iSCSI または NFS を使用する場合は、 VMware vSAN と汎用のストレージアレイのトラフィック）に専用のネットワークポート、帯域幅、および vSwitch の構成を定義します。
* ストレージ利用率を制限するように容量オプションを設定します（ ONTAP Select では、外部 vNAS データストアの全容量は使用できません）。
* 可能な場合は、すべての汎用の外付けストレージアレイで、使用可能な冗長性機能と HA 機能を使用してください

