---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: ONTAP Select Deploy 管理ユーティリティのインストールを計画する際に考慮する必要のある一般的な要件がいくつかあります。 
---
= ONTAP Select Deploy の一般的な要件と計画
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 管理ユーティリティのインストールを計画する際に考慮する必要のある一般的な要件がいくつかあります。



== Deploy ユーティリティと ONTAP Select クラスタのペアリング

Deploy ユーティリティのインスタンスを ONTAP Select クラスタにペアリングする際に使用するいくつかのオプションがあります。


NOTE: すべての導入シナリオでは、単一の ONTAP Select クラスタとクラスタ内のノードを、 Deploy 管理ユーティリティの 1 つのインスタンスだけで管理できます。Deploy ユーティリティの 2 つ以上の異なるインスタンスによって 1 つのクラスタを管理することはできません。

.ONTAP Select クラスタごとにユーティリティの 1 つのインスタンス
Deploy ユーティリティの専用のインスタンスを使用して、各 ONTAP Select クラスタを導入および管理できます。この 1 対 1 の構成では、ユーティリティとクラスタの各ペアリングが明確に分離されます。この構成では、小規模な障害ドメインで高度な分離が実現されます。

.複数の ONTAP Select クラスタにユーティリティの 1 つのインスタンスを使用する
Deploy ユーティリティの単一インスタンスを使用して、複数の ONTAP Select クラスタを組織で導入および管理できます。この 1 対多の構成では、すべての処理データと設定データが Deploy ユーティリティの同じインスタンスによって管理されます。


NOTE: Deploy ユーティリティの 1 つのインスタンスで、最大 400 個の ONTAP Select ノードまたは 100 個のクラスタを管理できます。



== KVM環境に関連する要件

Deploy管理ユーティリティをKVMハイパーバイザー環境にインストールする前に、基本的な要件を確認し、導入の準備を行う必要があります。

.導入の要件と制限事項
ONTAP Select DeployユーティリティをKVM環境にインストールするときは、いくつかの要件と制限事項について考慮する必要があります。

.Linux KVMホストサーバハードウェアの要件
Linux KVMハイパーバイザーホストがいくつかのリソースの最小要件を満たしている必要があります。ONTAP Selectを導入するホストが次の基本的な要件を満たしていることを確認します。

* Linuxサーバ：
+
** ハードウェアとソフトウェアは64ビットである必要があります。
** サーバは、ONTAP Selectノードに対して定義されたものと同じサポートされているバージョンに準拠している必要があります。


* 仮想 CPU （ 2 ）
* 仮想メモリ（4GB）
* ストレージ（40GB）
* "Dynamic Host Configuration Protocol（DHCP；動的ホスト構成プロトコル）が有効になっています（静的IPアドレスを割り当てることもできます）。


.ネットワーク接続
Deploy仮想マシンのネットワークインターフェイスが設定され、管理するONTAP Selectホストに接続できることを確認します。

.IP バージョン 4 のサポート
ONTAP Select Deploy は、 IP バージョン 4 （ IPv4 ）のみをサポートします。IP バージョン 6 （ IPv6 ）はサポートされません。この制限は、次の点で ONTAP Select に影響します。

* Deploy VMの管理LIFにIPv4アドレスを割り当てる必要があります。
* ONTAP LIF で IPv6 を使用するように設定された ONTAP Select ノードを Deploy で作成することはできません。




== 必要な設定情報

導入計画の一環として、 ONTAP Select Deploy 管理ユーティリティをインストールする前に、必要な設定情報を特定しておく必要があります。

.Deploy VMの名前
VMに使用する名前。

.Linux KVMホストの名前
DeployユーティリティがインストールされているLinux KVMホスト。

.ストレージプールの名前
VMファイルを格納するストレージプール（約40GBが必要）。

.VMのネットワーク
Deploy VMが接続されているネットワーク。



== オプションのネットワーク構成情報

Deploy VMは、デフォルトでDHCPを使用して設定されます。ただし、必要に応じて、VMのネットワークインターフェイスを手動で設定できます。

.ホスト名
ホストの名前。

.ホストの IP アドレス
静的IPv4アドレス。

.サブネットマスク
サブネットワークマスク。VMが属するネットワークに基づいています。

.ゲートウェイ
デフォルトゲートウェイまたはルータ。

.プライマリ DNS サーバ
プライマリドメインネームサーバ。

.セカンダリ DNS サーバ
セカンダリドメインネームサーバ。

.検索ドメイン
使用する検索ドメイン。



== クレデンシャルストアを使用した認証

ONTAP Select Deployクレデンシャルストアは、アカウント情報を保持するデータベースです。Deploy は、クラスタの作成と管理の一環として、アカウントのクレデンシャルを使用してホスト認証を実行します。ONTAP Select の導入計画の一環として、クレデンシャルストアがどのように使用されるかを理解しておく必要があります。


NOTE: アカウント情報は、 AES 暗号化アルゴリズムと SHA-256 ハッシュアルゴリズムを使用し、データベースに安全に保存されます。

.クレデンシャルのタイプ
次のタイプのクレデンシャルがサポートされます。

* ONTAP Select ノードを VMware ESXi に直接導入する際にハイパーバイザーホストを認証するために使用するホスト
* ホストが VMware vCenter で管理されている場合、 ESXi への ONTAP Select ノードの導入時に vCenter サーバの認証に使用する vCenter


.にアクセスします
クレデンシャルストアは、ハイパーバイザーホストの追加など、 Deploy を使用する通常の管理タスクの実行時に内部的にアクセスされます。Deploy の Web ユーザインターフェイスと CLI を使用して、クレデンシャルストアを直接管理することもできます。
