---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: VMware 環境に固有の要件と制限事項がいくつかあります。これらは、 VMware 環境に ONTAP Select Deploy ユーティリティをインストールする前に検討する必要があります。 
---
= ONTAP Select Deployハイパーバイザーホストに関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ハイパーバイザーホストに関連するいくつかの計画の問題について考慮する必要があります。


CAUTION: ネットアップサポートからの指示がないかぎり、 ONTAP Select 仮想マシンの構成を直接変更しないでください。仮想マシンの設定と変更は、 Deploy 管理ユーティリティからのみ実行してください。ネットアップサポートの支援なしで Deploy ユーティリティ以外の ONTAP Select 仮想マシンに変更を加えると、原因 でその仮想マシンが失敗し、使用できなくなる可能性があります。



== ハイパーバイザーに依存しない

ONTAP SelectとONTAP Select Deploy管理ユーティリティはどちらもハイパーバイザーに依存しません。

次のハイパーバイザーは、ONTAP SelectとONTAP Select Deployの両方の管理でサポートされます。

* VMware ESXi
* Kernel-based Virtual Machine （ KVM ）



NOTE: サポートされているプラットフォームに関する追加の詳細については、ハイパーバイザー固有の計画情報およびlink:reference_release_notes.html["リリース ノート"]を参照してください。

.ONTAP Select ノードと管理ユーティリティ用のハイパーバイザー
Deploy管理ユーティリティとONTAP Selectノードは、どちらも仮想マシンとして実行されます。Deploy ユーティリティ用に選択したハイパーバイザーは、 ONTAP Select ノード用に選択したハイパーバイザーに依存しません。この 2 つをペアリングすると、完全な柔軟性が得られます。

* VMware ESXi 上で動作する Deploy ユーティリティは、VMware ESXi または KVM 上の ONTAP Select クラスタを作成および管理できます。
* KVM上で動作するDeployユーティリティは、VMware ESXiまたはKVM上のONTAP Selectクラスタを作成および管理できます。


.ホストごとに 1 つ以上の ONTAP Select ノードインスタンス
各 ONTAP Select ノードは専用の仮想マシンとして実行されます。同じハイパーバイザーホストに複数のノードを作成できますが、次の制限事項があります。

* 1 つの ONTAP Select クラスタの複数のノードを同じホストで実行することはできません。特定のホスト上のすべてのノードは、異なる ONTAP Select クラスタに属している必要があります。
* 外付けストレージを使用する必要があります。
* ソフトウェア RAID を使用する場合、ホストに導入できる ONTAP Select ノードは 1 つだけです。


.クラスタ内のノードに対するハイパーバイザーの整合性
ONTAP Select クラスタ内のすべてのホストが、同じバージョンおよびリリースのハイパーバイザーソフトウェアで実行されている必要があります。

.各ホストの物理ポートの数
各ホストで 1 つ、 2 つ、または 4 つの物理ポートを使用するように設定する必要があります。ネットワークポートを柔軟に設定することもできますが、可能な場合は次の推奨事項に従う必要があります。

* シングルノードクラスタのホストには 2 つの物理ポートが必要です。
* マルチノードクラスタの各ホストには 4 つの物理ポートが必要です


.ONTAP SelectとONTAPハードウェアベースのクラスタの統合
ONTAP Select ノードをハードウェアベースの ONTAP クラスタに直接追加することはできません。ただし、必要に応じて、 ONTAP Select クラスタとハードウェアベースの ONTAP クラスタの間にクラスタピア関係を確立できます。



== VMware ハイパーバイザー環境です

VMware 環境に固有の要件と制限事項がいくつかあります。これらは、 VMware 環境に ONTAP Select Deploy ユーティリティをインストールする前に検討する必要があります。

.ESXi ホストサーバハードウェアの要件
ESXiハイパーバイザーホストは、いくつかの最低限のリソース要件を満たす必要があります。ONTAP Select が導入されるホストが以下の基本要件を満たしていることを確認してください。

* ESXi サーバ：
+
** ハードウェアとソフトウェアは 64 ビットである必要があります
** ONTAP Select ノードに対して定義されたものと同じ、サポート対象のバージョンを使用している必要があります


* 仮想 CPU （ 2 ）
* 仮想メモリ（ 4GB ）
* ストレージ（ 40GB ）
* DHCP が有効（静的 IP アドレスを割り当てることも可能）


.ネットワーク接続
ONTAP Select Deploy 仮想マシンのネットワークインターフェイスが設定済みであり、単一の管理 IP アドレスを持っていることを確認してください。DHCP を使用して IP アドレスを動的に割り当てるか、静的 IP アドレスを手動で設定することができます。

導入する決定に応じて、 Deploy VM が管理する vCenter サーバ、 ESXi ハイパーバイザーホスト、および ONTAP Select ノードに接続できる必要があります。必要なトラフィックを許可するようにファイアウォールを設定する必要があります。

Deploy は VMware VIX API を使用して、vCenter サーバーおよび ESXi ホストと通信します。まず、TCP ポート 443 で SOAP over SSL を使用して接続を確立します。その後、ポート 902 で SSL を使用して接続が開かれます。さらに、Deploy は PING コマンドを発行して、指定した IP アドレスに ESXi ホストが存在することを確認します。

さらに、Deploy は、以下のプロトコルを使用して ONTAP Select ノードおよびクラスタ管理 IP アドレスと通信できる必要があります：

* ping コマンド（ ICMP ）
* SSH （ポート 22 ）
* SSL （ポート 443 ）


.IP バージョン 4 のサポート
ONTAP Select Deploy は、 IP バージョン 4 （ IPv4 ）のみをサポートします。IP バージョン 6 （ IPv6 ）はサポートされません。この制限は、次の点で ONTAP Select に影響します。

* Deploy 仮想マシンの管理 LIF に IPv4 アドレスを割り当てる必要があります。
* ONTAP LIF で IPv6 を使用するように設定された ONTAP Select ノードを Deploy で作成することはできません。




== VMware vCenter サーバーに関する考慮事項

.ESA の VMware vSphere 権限
vCenter で vSAN Express Storage Architecture （ESA） を作成および管理するには、次の vSphere コンテンツライブラリ権限が必要です：


NOTE: コンテンツライブラリの権限にアクセスするには、管理者が vCenter Server のグローバル権限へのアクセスを許可する必要があります。

* ライブラリアイテムを追加
* ローカルライブラリを作成する
* ライブラリアイテムを削除
* ローカルライブラリを削除する
* ファイルをダウンロードする
* ストレージの読み取り
* ファイルの更新
* ライブラリを更新
* ライブラリアイテムを更新
* ローカルライブラリを更新する
* 構成設定を表示する

