---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 現在のリリースには、ONTAP Select 固有の新機能や機能強化は含まれていません。 
---
= このリリースの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ネットアップでは、ONTAP Select を定期的に更新して、新機能と拡張機能を提供しています



== ONTAP Select 9.12.1

ONTAP Select 9.12.1は、現在のコアONTAP 製品のリリースに新しく開発されたほとんどの機能を活用しています。ONTAP Select 固有の新機能や機能強化は含まれていません。



== ONTAP Select 9.11.1

ONTAP Select 9.11.1では、いくつかの新機能と機能拡張が追加されています

VMware ESXiのサポートを強化:: ONTAP Select 9.11.1では、VMware ESXi 7.0 U3Cがサポートされています。
VMware NSX のサポート:: ONTAP Select 9.10.1以降のリリースは、VMware NSX -Tバージョン3.1.2に対応しています。OVAファイルとONTAP Select Deploy管理ユーティリティを使用して導入されたONTAP Select シングルノードクラスタでNSXとTを使用しても、機能の問題や不具合は発生しません。ただし、ONTAP Select マルチノードクラスタでNSXとTを使用する場合は、ONTAP Select 9.11.1で次の制限事項に注意する必要があります。
+
--
* ネットワーク接続チェッカー
+
NSX ベースのネットワークに対して実行されると、 Deploy CLI で使用可能なネットワーク接続チェッカーが失敗します。



--
KVM ハイパーバイザーのサポートが廃止されました::
+
--
ONTAP Select 9.10.1以降、KVMハイパーバイザーに新しいクラスタを導入することはできなくなりました。

ONTAP Select 9.11.1以降では、既存のKVMクラスタおよびホストですべての管理機能を使用できなくなりました。ただし、Take offline機能とdelete機能は除きます。

ネットアップでは、ONTAP Select for KVMからONTAP Select for ESXiを含む他のONTAP プラットフォームへの完全なデータ移行を計画し、実行することを強く推奨します。詳細については、を参照してください https://mysupport.netapp.com/info/communications/ECMLP2877451.html["販売終了通知"^]

--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1には、いくつかの新機能と機能強化が含まれています。

VMware NSX のサポート:: ONTAP Select 9.10.1 は VMware NSX -T バージョン 3.1.2 に対応しています。OVAファイルとONTAP Select Deploy管理ユーティリティを使用して導入されたONTAP Select シングルノードクラスタでNSXとTを使用しても、機能の問題や不具合は発生しません。ただし、 NSX と ONTAP Select マルチノードクラスタを併用する場合は、次の要件および制限事項に注意してください。
+
--
* クラスタ MTU
+
追加のオーバーヘッドを考慮してクラスタを導入する前に、クラスタの MTU サイズを 8800 に手動で調整する必要があります。VMware のガイダンスでは、 NSX を使用する場合に 200 バイトのバッファを使用できるようにする方法を説明しています

* ネットワーク 4x10Gb 構成
+
4 つの NIC が設定された VMware ESXi ホストに ONTAP Select を導入する場合、 Deploy ユーティリティから、 2 つの異なるポートグループに内部トラフィックを分割し、 2 つの異なるポートグループに外部トラフィックを分けるというベストプラクティスに従うように求められます。ただし、オーバーレイネットワークを使用する場合、この設定は機能しないため、推奨事項は無視してください。この場合は、内部ポートグループを 1 つと外部ポートグループを 1 つだけ使用してください。

* ネットワーク接続チェッカー
+
NSX ベースのネットワークに対して実行されると、 Deploy CLI で使用可能なネットワーク接続チェッカーが失敗します。



--
KVM ハイパーバイザーのサポートが廃止されました:: ONTAP Select 9.10.1 以降、 KVM ハイパーバイザーに新しいクラスタを導入することはできなくなりました。ただし、クラスタを以前のリリースから 9.10.1 にアップグレードしても、 Deploy ユーティリティを使用してクラスタを管理できます。




== ONTAP Select 9.9.1

ONTAP Select 9.9.1では、いくつかの新機能と機能拡張が実装されています

プロセッサー・ファミリーのサポート:: ONTAP Select 9.9.2.1以降では、ONTAP Select でサポートされるのは、インテルXeon Sandy Bridge以降のCPUモデルのみです。
VMware ESXiのサポートを更新:: VMware ESXiのサポートは、ONTAP Select 9.9..1で強化されました。次のリリースがサポートされるようになりました。
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8には、いくつかの新機能と変更された機能が含まれています。

高速インターフェイス:: 高速インターフェイス機能は、25G（25GbE）と40G（40GbE）の両方にオプションを提供することで、ネットワーク接続を強化します。この速度を高速で使用する場合のパフォーマンスを最大限に高めるには、ONTAP Select のドキュメントに従ってポートマッピング設定のベストプラクティスに従う必要があります。
VMware ESXiのサポートを更新:: ONTAP Select 9.8については、VMware ESXiのサポートに関して2つの変更があります。
+
--
* ESXi 7.0がサポートされる（GAビルド15849807以降）
* ESXi 6.0はサポートされなくなりました


--

