---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select は、ほとんどのONTAP 機能を完全にサポートしています。ONTAP の機能の多くには、クラスタの導入時に各ノードで自動的にライセンスが付与されます。ただし、一部の機能には個別のライセンスが必要です。 
---
= ONTAP SelectでのONTAP機能のサポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select はほとんどのONTAP機能をサポートしています。クラスタを導入すると、多くのONTAP機能のライセンスが各ノードに自動的に付与されます。ただし、一部の機能には別途ライセンスが必要です。


NOTE: ハードウェア固有の依存関係を持つONTAP 機能は、一般にONTAP Select ではサポートされていません。



== デフォルトでライセンスされるONTAP機能

ONTAP Selectでは、次のONTAP機能がサポートされており、デフォルトでライセンスが付与されています。

* Autonomous Ransomware Protection（ARP）（手動更新）
* CIFS
* 重複排除機能と圧縮機能
* Key Management Interoperability Protocol（KMIP）を使用した外部キー管理
+
外部キー管理は、ONTAP Select でサポートされている唯一のキー管理です。link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["外部キー管理の有効化と設定"^]について学習します。

* FlexCache
+
ONTAP Selectは、ライトバック機能付きFlexCacheキャッシュボリュームをサポートしています。ライトバック機能を持つFlexCacheオリジンボリュームはサポートされていません。

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["ONTAP SelectでのFlexCacheライトバックの詳細"]

* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption （規制対象外の国のみ）
* NFS
* NVMe over TCP
* ONTAP のマルチテナンシー機能
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock SelectはONTAP Select向けに設計されたONTAP SnapLockの実装であり、SnapLock Enterpriseが含まれています。SnapLock Complianceは含まれていません。

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLock"^]について学ぶ

* SnapMirror
* SnapRestore
* SnapVault
* Storage VMディザスタリカバリ（SVM DR）
+
ONTAP SelectはSVM DRをソースと宛先の両方としてサポートし、最大16件の関係を設定できます。SVM DRのサポートは、ソースONTAPバージョンからバージョン+2までの使用に限定されます。たとえば、ONTAP Select 9.16.1ソースは、宛先ONTAPバージョン9.16.1、9.17.1、または9.18.1に接続できます。





== 個別にライセンスされるONTAP の機能

デフォルトではライセンスされていないONTAP機能については、別途ライセンスを取得する必要があります。これには次のものが含まれます：

* FabricPool
+

NOTE: StorageGRIDを使用する場合は、FabricPoolライセンスは必要ありません。

* MetroCluster SDS （ ONTAP Select プレミアムライセンスサービス）
* SnapMirrorクラウド
+
link:https://mysupport.netapp.com/site/help["非技術的なサポートケースを開く"^]してSnapMirrorクラウドライセンスを取得する必要があります。

+
link:https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["オブジェクト ストレージへのSnapMirrorクラウドのバックアップ"^]について学ぶ



.関連情報
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["ONTAP SelectとONTAP 9の比較"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAP マスター ライセンス キーについて学ぶ"^]

