---
sidebar: sidebar 
permalink: sizing-capacity-pool-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: Capacity Tiers ライセンスは、各ノードが管理する基盤となるディスク容量に基づいており、ノード、HA ペア、またはクラスタの使用可能容量に基づいていません。各 Capacity Tiers ライセンスは、指定された容量の個々のノード シリアル番号に割り当てられ、付随するサポート契約が必要です。 
---
= ONTAP Select の容量プールライセンスサイズの決定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プールライセンスの認可容量は、テラバイト単位（TB）で、最小容量は2 TBです。ライセンス容量は、使用可能なスペースの量にオーバーヘッド係数を掛けることで計算します。オーバーヘッド係数は、使用可能なスペースから取得されるONTAP Selectソフトウェアオーバーヘッド容量を推定するものであり、NVMe、SSD、HDD、または仮想ドライブに対するONTAP Selectの容量の決定に適用されます。オーバーヘッド係数は、シングルノードクラスタとマルチノード（HAペアベース）クラスタで異なります：

* シングルノード クラスタのオーバーヘッド係数は1.13です
* マルチノード クラスタのオーバーヘッド係数は2.67です


導入に必要な容量を確保するためには、使用可能なスペースに基づいてライセンス容量を計算する必要があります。例えば、HAペア用に20 TBの使用可能容量（ノードあたり10 TB）が必要な場合：

* HAペアでは、冗長性を確保するためにデータが両方のノード間で複製されます。そのため、HAペアで20 TBの利用可能なデータを使用する場合、いずれかのノードがオフラインになった場合に備えて、ノードごとに20 TBの容量が必要になります。
* 2.67 という係数は各ノードの容量を 2 倍にし、ONTAP Select が機能するために必要なオーバーヘッド容量 （0.67） を追加します。
* ノードあたりのライセンス容量は27 TB（10 x 2.67 = 26.7）です。HAペアの場合、20 TBの使用可能容量を確保するには、27 TBのライセンスが2つ必要です。


[cols="25,30,45"]
|===
| 説明 | シングルノード | HAペアまたはHAペアと単一ノードの混合 


| 使用可能スペース | 20 TB | シングルノード クラスタあたり10TB、HAペアの場合は20TB 


| ライセンス スペース | 23 TB（20 x 1.13 = 22.6、次の完全な TB に切り上げ） | 54 TB（20 x 2.67 = 53.4、次の完全な TB に切り上げ） 


| ノードあたりの最大使用可能容量 *注*：ノードまたはHAペアあたりの最大管理容量は400 TBです | 353 TB（400／1.13）  a| 
クラスター内の単一ノードあたり：

149 TB（400／2.67）

クラスター内の HA ペアごとに：

298 TB（2 x 149）

|===
.次の手順
link:task_lic_acquire_cp.html["ONTAP Select の Capacity Pools ライセンスを取得する"]
