---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: Capacity Tiers ライセンスは、各ノードが管理する基盤となるディスク容量に基づいており、ノード、HA ペア、またはクラスタの使用可能容量に基づいていません。各 Capacity Tiers ライセンスは、指定された容量の個々のノード シリアル番号に割り当てられ、付随するサポート契約が必要です。 
---
= ONTAP Select の容量ティアライセンスサイズの決定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Capacity Tiersライセンスは、各ONTAP Selectノードによって管理される基盤となるディスク容量に基づいており、ノード、HAペア、またはクラスタの使用可能容量に基づいていません。各Capacity Tiersライセンスは、指定された容量の個々のノードシリアル番号に割り当てられ、付随するサポート契約が必要です。

容量ティアライセンスのライセンス容量は、1 TB単位で、最小容量は1 TBです。ライセンス容量は、使用可能なスペースの量にオーバーヘッド係数を掛けることで計算します。オーバーヘッド係数は、使用可能なスペースから取得されるONTAP Selectソフトウェアのオーバーヘッド容量を推定するものであり、NVMe、SSD、HDD、または仮想ドライブに対するONTAP Selectの容量の決定に適用されます。オーバーヘッド係数は、シングルノードクラスタとマルチノード（HAペアベース）クラスタで異なります。

* シングルノード クラスタのオーバーヘッド係数は1.13です
* マルチノード クラスタのオーバーヘッド係数は2.67です


導入に必要な容量を確保するためには、使用可能なスペースに基づいてライセンス容量を計算する必要があります。例えば、HAペア用に10 TBの使用可能容量（ノードあたり5 TB）が必要な場合：

* HAペアでは、冗長性を確保するためにデータが両方のノード間で複製されます。そのため、HAペアで10 TBの利用可能なデータを使用する場合、いずれかのノードがオフラインになった場合に備えて、ノードごとに10 TBの容量が必要になります。
* 2.67 という係数は各ノードの容量を 2 倍にし、ONTAP Select が機能するために必要なオーバーヘッド容量 （0.67） を追加します。
* ノードあたりのライセンス容量は14TB（5×2.67＝13.35）です。HA構成の場合、10TBの使用可能容量を確保するには、14TBのライセンスが2つ必要です。


[cols="25,30,45"]
|===
| 説明 | シングル ノード | HA ペア 


| 使用可能スペース | 10 TB | ノードあたり5 TB、HAペアの場合は10 TB 


| ライセンス スペース | 12 TB（10 x 1.13 = 11.3、次の完全な TB に切り上げ） | 14 TBライセンス2つ（5 x 2.67 = 13.35、次の完全なTBに切り上げ） 


| ノードあたりの最大使用可能容量 *注*：ノードまたはHAペアあたりの最大管理容量は400 TBです | 353 TB（400／1.13）  a| 
HAペアのノードごとに：

* 149 TB（400／2.67）


マルチノード クラスタ内の HA ペアごと：

* 2ノード：298 TB（2 x 149）
* 4ノード：596 TB（4 x 149）
* 6ノード：894 TB（6 x 149）
* 8ノード：1,192 TB（8 x 149）
* 10ノード：1,490 TB (10 x 149)
* 12ノード：1,788 TB（12 x 149）


|===
.次の手順
link:task_lic_acquire_ct.html["ONTAP Select の容量階層ライセンスを取得する"]
