---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: Capacity Tiers ライセンスは、各ノードが管理する基盤となるディスク容量に基づいており、ノード、HA ペア、またはクラスタの使用可能容量に基づいていません。各 Capacity Tiers ライセンスは、指定された容量の個々のノード シリアル番号に割り当てられ、付随するサポート契約が必要です。 
---
= ONTAP Select Capacity Tiersライセンスのサイズ設定に関する考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Capacity Tiersライセンスは、各ONTAP Selectノードによって管理される基盤となるディスク容量に基づいており、ノード、HAペア、またはクラスタの使用可能容量に基づいていません。各Capacity Tiersライセンスは、指定された容量の個々のノードシリアル番号に割り当てられ、付随するサポート契約が必要です。

Capacity Tiersライセンスのライセンス容量は、最小1 TiBのフルTiB単位で計算されます。ライセンス容量は、使用可能なスペース量にオーバーヘッド係数を掛けて算出します。オーバーヘッド係数は、シングルノード クラスタとマルチノード（HAペアベース）クラスタで異なります：

* シングルノード クラスタのオーバーヘッド係数は1.13です
* マルチノード クラスタのオーバーヘッド係数は2.67です


使用可能なスペースに基づいてライセンス容量を計算し、導入に十分な容量があることを確認します。

[cols="25,30,45"]
|===
| 説明 | シングル ノード | HA ペア 


| 使用可能スペース | 10 TiB | ノードあたり 5 TiB、HA ペアの場合は 10 TiB 


| ライセンス スペース | 12 TiB（10 x 1.13 = 11.3、次の完全な TiB に切り上げ） | 14 TiB ライセンス 2 つ（5 x 2.67 = 13.35、次の完全な TiB に切り上げ） 


| ノードあたりの最大使用可能スペース *注*：ノードまたはHAペアあたりの最大管理スペースは400 TiBです | 353 TiB（400／1.13）  a| 
HA ペアのノードごと：

* 74 TiB［（400 / 2）/ 2.67］


マルチノード クラスタ内の HA ペアごと：

* 2ノード：148 TiB（2 x 74）
* 4ノード：296 TiB（4 x 74）
* 6ノード：444 TiB（6 x 74）
* 8ノード：592 TiB（8 x 74）


|===
.次の手順
link:task_lic_acquire_ct.html["ONTAP Select の容量階層ライセンスを取得する"]
