---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: 容量階層のライセンスを使用している場合は、ONTAP Selectノードごとにライセンスファイルを取得する必要があります。ライセンスファイルではノードのストレージ容量を定義します。このファイルは、ネットアップが割り当てた一意の 9 桁のシリアル番号を使用してノードにロックされます。 
---
= ONTAP Selectの大容量階層ライセンスを取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量階層のライセンスを使用している場合は、ONTAP Selectノードごとにライセンスファイルを取得する必要があります。ライセンスファイルではノードのストレージ容量を定義します。このファイルは、ネットアップが割り当てた一意の 9 桁のシリアル番号を使用してノードにロックされます。

.作業を開始する前に
ネットアップがノードに割り当てた 9 桁のライセンスシリアル番号が必要です。ライセンスファイルを取得する前に、注文書の出荷日から少なくとも 24 時間待ってください。

.このタスクについて
このタスクは、大容量階層ライセンスが必要なONTAP Selectノードごとに実行する必要があります。

.手順
. Web ブラウザを使用して ONTAP Select ライセンスサイトにアクセスします。
+
https://register.netapp.com/register/getlicensefile`

. ネットアップアカウントのクレデンシャルを使用してサインインします。
. [*License Generator] ページで、ドロップダウン・ボックスから目的のライセンス製品を選択します。
. 同じページの残りのフィールドには、 ONTAP Select ノードのシリアル番号である * Product Serial # * を入力します。
. [Submit （送信） ] をクリックします。
. 要求の検証が完了したら、ライセンスの配信方法を選択します。
+
ライセンスのダウンロード * または電子メールライセンス * のいずれかをクリックできます。

. 選択した配信方法に基づいてライセンスファイルを受け取ったことを確認します。


.完了後
ライセンスファイルを ONTAP Select ノードに適用するには、 Deploy 管理ユーティリティにアップロードする必要があります。
