---
sidebar: sidebar 
permalink: task_vpi_manually_remove.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter, remove, removing, manually removing 
summary: vCenter Server から Deploy プラグインを手動で削除できます。 
---
= vCenter から Deploy プラグインを手動で削除します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter Server から Deploy プラグインを手動で削除できます。



== 作業を開始する前に

最初に、 VMware Managed Object Browser （ MOB ）を使用してプラグインを削除してから、 vCenter サーバ内の vSphere ディレクトリからプラグインを削除します。

プラグインを手動で削除する必要があるインスタンスは複数あります。

* Deploy ユーティリティの標準のユーザインターフェイスを使用してプラグインを削除しましたが、 vCenter サーバをリブートできませんでした。
* プラグインを削除せずに Deploy ユーティリティを運用停止した。




== VMware MOB を使用したプラグインの削除

MOB は、 VMware vCenter サーバ上のオブジェクトの表示と管理を可能にする VMware アプリケーションです。MOB を使用して Deploy vCenter プラグインを削除できます。

.手順
. ブラウザを使用して vCenter Server で MOB にアクセスし、サインインします。
+
https://<FQDN_or_IP-address>/mob` にアクセスします

. [*content*] をクリックし、 [*ExtensionManager*] をクリックします。
. 削除する拡張子がフルネームであることを確認します。
+
com.netapp.selectdeploy`

. [UnregisterExtension] をクリックします。
. 拡張子の名前を入力し、 *InvokeMethod* をクリックします。


拡張子のリストからプラグインが削除されます。



== vSphere UI フォルダからプラグインを削除しています

vCenter サーバで vSphere UI ディレクトリを調べて、 Deploy プラグインが見つかった場合は削除します。

vCenter Server での root アカウントのパスワードが必要です。vSphere MOB を使用してプラグインを削除する必要があります。

.手順
. SSH を使用して vCenter Server にアクセスし、サインインします。
+
ssh root@<fqdn_or_IP-address>

. 「 * shell * 」と入力し、 Enter キーを押して Bash シェルを起動します。
. vsphere-client-serenity ディレクトリに移動します。
+
「 cd /etc/vmware/vsphere-clientui/vc-packages/vsphere-client-serenity 」と入力します

. 削除する必要があるディレクトリが com.netapp.selectdeploy` の形式になっているかどうかを確認します
+
「 ls -al 」と入力します

. HTML5 vSphere UI Web クライアントを停止します。
+
「 service-control 」 -- 「 vsphere-ui 」を停止します

. UI 拡張機能が含まれているディレクトリを削除します。
+
rm -rf com.netapp.selectdeploy-1.0.0`

. HTML5 vSphere UI Web Client を再起動します。
+
「 service-control -- start vsphere-ui 」を参照してください



Deploy プラグインが再起動して使用可能になるまでに数分かかることがあります。



== vSphere Client フォルダからプラグインを削除します

vCenter Server の vSphere Client ディレクトリを調べて、見つかった場合は Deploy プラグインを削除します。Deploy プラグインは Flash を使用しませんが、プラグインの削除手順 の一部としてこのディレクトリを検証することを推奨します。

vCenter Server での root アカウントのパスワードが必要です。vSphere MOB を使用してプラグインを削除し、 vSphere UI ディレクトリからプラグインを削除する必要があります。

.手順
. SSH を使用して vCenter Server にアクセスし、サインインします。
+
ssh root@<fqdn_or_IP-address>

. 「 * shell * 」と入力し、 Enter キーを押して Bash シェルを起動します。
. vsphere-client-serenity ディレクトリに移動します。
+
cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity

. 削除する必要があるディレクトリが com.netapp.selectdeploy` の形式になっているかどうかを確認します
+
「 ls -al 」と入力します

. HTML5 vSphere UI Web クライアントを停止します。
+
「 service-control -- vsphere-stop vsphere-client 」と入力します

. クライアント拡張機能が含まれているディレクトリを削除します。
+
rm -rf com.netapp.selectdeploy-1.0.0`

. HTML5 vSphere UI Web Client を再起動します。
+
「 service-control -- start-vsphere-client 」と入力します



Deploy プラグインが再起動して使用可能になるまでに数分かかることがあります。
