---
sidebar: sidebar 
permalink: task_cli_deploy_cluster.html 
keywords: administer, administering, cli, create cluster, deploy cluster 
summary: ONTAP Select Deploy 管理ユーティリティに付属のコマンドラインインターフェイスを使用して、シングルノードまたはマルチノードの ONTAP Select クラスタを作成できます。 
---
= CLIを使用したONTAP Selectクラスタの導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 管理ユーティリティに付属のコマンドラインインターフェイスを使用して、シングルノードまたはマルチノードの ONTAP Select クラスタを作成できます。



== ステップ1: 展開の準備

ハイパーバイザーでONTAP Selectクラスタを作成する前に、必要な準備について理解しておく必要があります。

.手順
. ONTAP Selectノードにストレージを接続する準備
+
[role="tabbed-block"]
====
.ハードウェアRAID
--
ローカルハードウェアRAIDコントローラを使用する場合は、少なくとも1つのデータストア（ESX）または1つのlink:reference_chk_host_prep.html#create-storage-pool["ストレージプール（KVM）"]各ノードでは、システム データだけでなく、ルートとデータ集約も保存されます。ONTAP Select ノードの設定の一環として、ストレージプールを接続する必要があります。

--
.ソフトウェア RAID
--
ソフトウェアRAIDを使用する場合は、少なくとも1つのデータストア（ESX）または1つのlink:reference_chk_host_prep.html#create-storage-pool["ストレージプール（KVM）"]システム データ用であり、ルートおよびデータ アグリゲート用に SSD ドライブが使用可能であることを確認します。ONTAP Select ノードの設定の一環として、ストレージプールとディスクを接続する必要があります。

--
====
. 使用可能な ONTAP Select バージョン
+
Deploy 管理ユーティリティには、単一バージョンの ONTAP Select が含まれています。以前のバージョンのONTAP Selectを使用してクラスタを導入する場合は、まずlink:task_cli_deploy_image_add.html["ONTAP Selectイメージを追加する"]デプロイインスタンスに追加します。

. 本番環境用のライセンスONTAP Select
+
本番環境に ONTAP Select クラスタを導入する前に、ストレージ容量ライセンスを購入し、関連するライセンスファイルをダウンロードする必要があります。あなたはできるlink:concept_lic_production.html["各ノードのストレージにライセンスを付与する"] _Capacity Tiers_ モデルを使用するか、_Capacity Pools_ モデルを使用して共有プールのライセンスを取得します。





== ステップ2: ライセンスファイルをアップロードして登録する

ストレージ容量を含むライセンスファイルを取得したら、ライセンスを含むファイルを Deploy 仮想マシンにアップロードして登録する必要があります。


NOTE: クラスタを評価用に導入する場合は、この手順を省略できます。

.作業を開始する前に
admin ユーザアカウントのパスワードが必要です。

.手順
. ローカルワークステーション上のコマンドシェルで、 sftp ユーティリティを使用して、ライセンスファイルを Deploy 仮想マシンにアップロードします。
+
出力例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put NLF-320000nnn.txt
exit
....
. SSH を使用して、管理者アカウントで Deploy ユーティリティの CLI にサインインします。
. ライセンスを登録します。
+
[source, cli]
----
license add -file-name <file_name>
----
+
プロンプトが表示されたら、管理者アカウントのパスワードを入力します。

. システムのライセンスを表示して、ライセンスが正しく追加されたことを確認します。
+
[source, cli]
----
license show
----




== ステップ3: ハイパーバイザーホストを追加する

ONTAP Select ノードを実行する各ハイパーバイザーホストを登録する必要があります。

[role="tabbed-block"]
====
.KVM の略
--
ONTAP Selectノードを実行するハイパーバイザーホストを登録する必要があります。この一環として、Deploy管理ユーティリティはKVMホストに対して認証します。

.このタスクについて
複数のハイパーバイザー ホストが必要な場合は、この手順を使用して各ホストを追加します。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ホストを登録します。
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type KVM -username <KVM_username>
----
+
出力例

+
[listing]
----
host register -name 10.234.81.14 -hypervisor-type KVM -username root
----
+
プロンプトが表示されたら、ホストアカウントのパスワードを入力します。

. ホストの状態を表示し、認証されていることを確認します。
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
出力例

+
[listing]
----
host show -name 10.234.81.14 -detailed
----


--
.ESXi
--
この一部として、 Deploy 管理ユーティリティは、ホストを管理する vCenter Server への認証、または ESXi スタンドアロンホストへの直接の認証を行います。

.このタスクについて
vCenter で管理されているホストを登録する前に、 vCenter Server 用の管理サーバアカウントを追加する必要があります。ホストが vCenter で管理されていない場合は、ホストを登録する際にホストのクレデンシャルを指定できます。この手順 を使用して各ホストを追加します。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ホストが vCenter サーバで管理されている場合は、 vCenter アカウントのクレデンシャルを追加します。
+
[source, cli]
----
credential add -hostname <FQDN|IP> -type vcenter -username <vcenter_username>
----
+
出力例

+
....
credential add -hostname vc.select.company-demo.com -type vcenter -username administrator@vsphere.local
....
. ホストを登録します。
+
** vCenterで管理されていないスタンドアロンホストを登録します。
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -username <esx_username>
----
** vCenterで管理されているホストを登録します。
+
[source, cli]
----
host register -name <FQDN|IP> -hypervisor-type ESX -mgmt-server <FQDN|IP>
----
+
出力例

+
....
host register -name 10.234.81.14 -hypervisor-type ESX -mgmt-server vc.select.company-demo.com
....


. ホストの状態を表示し、認証されていることを確認します。
+
[source, cli]
----
host show -name <FQDN|IP> -detailed
----
+
出力例

+
....
host show -name 10.234.81.14 -detailed
....


--
====


== ステップ4: ONTAP Selectクラスタを作成して設定する

ONTAP Select クラスタを作成し、設定する必要があります。クラスタを設定したら、個々のノードを設定できます。

.作業を開始する前に
クラスターに含まれるノードの数を決定し、関連する構成情報を取得します。

.このタスクについて
ONTAP Select クラスタを作成すると、 Deploy ユーティリティは、指定したクラスタ名とノード数に基づいてノード名を自動的に生成します。Deploy は一意のノード識別子も生成します。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. クラスタを作成します。
+
[source, cli]
----
cluster create -name <cluster_name> -node-count <count>
----
+
出力例

+
....
cluster create -name test-cluster -node-count 1
....
. クラスタを設定します。
+
[source, cli]
----
cluster modify -name <cluster_name> -mgmt-ip <IP_address> -netmask <netmask> -gateway <IP_address> -dns-servers <FQDN|IP>_LIST -dns-domains <domain_list>
----
+
出力例

+
....
cluster modify -name test-cluster -mgmt-ip 10.234.81.20 -netmask 255.255.255.192
-gateway 10.234.81.1 -dns-servers 10.221.220.10 -dnsdomains select.company-demo.com
....
. クラスタの設定と状態を表示します。
+
[source, cli]
----
cluster show -name <cluster_name> -detailed
----




== ステップ5: ONTAP Selectノードを構成する

ONTAP Select クラスタ内の各ノードを設定する必要があります。

.作業を開始する前に
* ノードの構成情報があることを確認します。
* 容量層または容量プールのライセンス ファイルが、展開ユーティリティでアップロードされ、インストールされていることを確認します。


.このタスクについて
この手順 を使用して各ノードを設定する必要があります。この例では、ノードに大容量階層ライセンスが適用されています。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. クラスタノードに割り当てられた名前を特定します。
+
[source, cli]
----
node show -cluster-name <cluster_name>
----
. ノードを選択し、基本的な設定を実行します。
+
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -host-name <FQDN|IP> -license-serial-number <number> -instance-type TYPE -passthrough-disks false
----
+
出力例

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -host-name 10.234.81.14
-license-serial-number 320000nnnn -instance-type small -passthrough-disks false
....
+
ノードの RAID 設定は、 _passthrough-pdisks_parameter で示されます。ローカルハードウェアRAIDコントローラを使用している場合、この値は「false」にする必要があります。ソフトウェアRAIDを使用している場合、この値は「true」にする必要があります。

+
ONTAP Selectノードには大容量階層ライセンスが使用されます。

. ホストで使用可能なネットワーク設定を表示します。
+
[source, cli]
----
host network show -host-name <FQDN|IP> -detailed
----
+
出力例

+
....
host network show -host-name 10.234.81.14 -detailed
....
. ノードのネットワーク設定を実行します。
+
[role="tabbed-block"]
====
.ESXiホスト
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-networks <network_name> -data-networks <network_name> -internal-network <network_name>
----
--
.KVMホスト
--
[source, cli]
----
node modify -name <node_name> -cluster-name <cluster_name> -mgmt-ip IP -management-vlans <vlan_id> -data-vlans <vlan_id> -internal-vlans <vlad_id>
----
--
====
+
単一ノード クラスターを展開する場合は、内部ネットワークは必要ないため、「-internal-network」を削除する必要があります。

+
出力例

+
....
node modify -name test-cluster-01 -cluster-name test-cluster -mgmt-ip 10.234.81.21
-management-networks sDOT_Network -data-networks sDOT_Network
....
. ノードの設定を表示します。
+
[source, cli]
----
node show -name <node_name> -cluster-name <cluster_name> -detailed
----
+
出力例

+
....
node show -name test-cluster-01 -cluster-name test-cluster -detailed
....




== ステップ6: ONTAP Selectノードにストレージを接続する

ONTAP Selectクラスタ内の各ノードで使用されるストレージを設定します。すべてのノードには、必ず少なくとも1つのストレージプールを割り当てる必要があります。ソフトウェアRAIDを使用する場合は、各ノードに少なくとも1本のディスクドライブを割り当てる必要があります。

.作業を開始する前に
VMware vSphere を使用してストレージ プールを作成します。ソフトウェアRAIDを使用する場合は、使用可能なディスクドライブが少なくとも1本必要です。

.このタスクについて
ローカルハードウェアRAIDコントローラを使用する場合は、手順1~4を実行する必要があります。ソフトウェアRAIDを使用する場合は、手順1~6を実行する必要があります。

.手順
. 管理者アカウントのクレデンシャルを使用して、SSHを使用してDeployユーティリティのCLIにサインインします。
. ホストで使用可能なストレージプールを表示します。
+
[source, cli]
----
host storage pool show -host-name <FQDN|IP>
----
+
出力例

+
[listing]
----
host storage pool show -host-name 10.234.81.14
----
+
VMware vSphere から使用可能なストレージプールを取得することもできます。

. 使用可能なストレージプールを ONTAP Select ノードに接続します。
+
[source, cli]
----
node storage pool attach -name <pool_name> -cluster-name <cluster_name> -node-name <node_name> -capacity-limit <limit>
----
+
「-capacity-limit」パラメータを含める場合は、値を GB または TB で指定します。

+
出力例

+
[listing]
----
node storage pool attach -name sDOT-02 -cluster-name test-cluster -
node-name test-cluster-01 -capacity-limit 500GB
----
. ノードに接続されているストレージプールを表示します。
+
[source, cli]
----
node storage pool show -cluster-name <cluster_name> -node-name <node_name>
----
+
出力例

+
[listing]
----
node storage pool show -cluster-name test-cluster -node-name testcluster-01
----
. ソフトウェアRAIDを使用している場合は、使用可能なドライブを接続します。
+
[source, cli]
----
node storage disk attach -node-name <node_name> -cluster-name <cluster_name> -disks <list_of_drives>
----
+
出力例

+
[listing]
----
node storage disk attach -node-name NVME_SN-01 -cluster-name NVME_SN -disks 0000:66:00.0 0000:67:00.0 0000:68:00.0
----
. ソフトウェアRAIDを使用している場合は、ノードに接続されているディスクを表示します。
+
[source, cli]
----
node storage disk show -node-name <node_name> -cluster-name <cluster_name>`
----
+
出力例

+
[listing]
----
node storage disk show -node-name sdot-smicro-009a -cluster-name NVME
----




== ステップ7: ONTAP Selectクラスタを導入する

クラスタとノードを設定したら、クラスタを導入できます。

.作業を開始する前に
ネットワーク接続チェッカーを実行するには、 link:task_adm_connectivity.html["ウェブUI"]またはlink:task_cli_connectivity.html["CLI"]内部ネットワーク上のクラスターノード間の接続を確認します。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ONTAP Select クラスタを導入します。
+
[source, cli]
----
cluster deploy -name <cluster_name>
----
+
出力例

+
[listing]
----
cluster deploy -name test-cluster
----
+
プロンプトが表示されたら、 ONTAP 管理者アカウントに使用するパスワードを指定します。

. クラスタのステータスを表示して、導入が正常に完了したことを確認します。
+
[source, cli]
----
cluster show -name <cluster_name>
----


.次の手順
link:task_cli_clusters.html["ONTAP Select Deploy 構成データをバックアップします"]。
