---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: ONTAP Select Deploy 管理ユーティリティをインストールし、ユーティリティを使用して ONTAP Select クラスタを作成する必要があります。 
---
= ONTAP Select Deploy をインストールする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 管理ユーティリティをインストールし、ユーティリティを使用して ONTAP Select クラスタを作成する必要があります。



== 仮想マシンイメージのダウンロード

ONTAP Select パッケージは、ネットアップサポートサイトからダウンロードできます。

.このタスクについて
ONTAP Select Deploy管理ユーティリティは、Open Virtualization Format（OVF）標準に基づく仮想マシン（VM）としてパッケージ化されています。単一の圧縮ファイルのサフィックス `ova`。VMは、ONTAP SelectノードのDeployサーバとインストールイメージを提供します。

.手順
. にアクセスします link:https://mysupport.netapp.com/site/["NetApp Support Site"^] Webブラウザを使用してサインインします。
. メニューから* Downloads *を選択し、ドロップダウンメニューから* Downloads *を選択します。
. [Downloads]ページの[All Products A-Z]で、文字「* O *」を選択します。
. 下にスクロールして* ONTAP Select *を選択します。
. パッケージのリリースを選択します。
. エンドユーザライセンス契約（EULA）を確認し、*同意して続行*を選択します。
. 適切なパッケージを選択してダウンロードし、必要に応じてすべてのプロンプトに応答します。




== ONTAP Select Deploy OVAシグネチャの確認

インストールパッケージをインストールする前に、ONTAP Selectオープン仮想化アプライアンス（OVA）の署名を確認する必要があります。

.作業を開始する前に
システムが次の要件を満たしていることを確認します。

* OpenSSLバージョン1.0.2～3.0（基本検証用）
* Online Certificate Status Protocol（OCSP）検証用のパブリックインターネットアクセス


.手順
. NetApp Support Siteの製品ダウンロードページから次のファイルを入手します。
+
[cols="2*"]
|===
| ファイル。 | 説明 


| `ONTAP-Select-Deploy-Production.pub` | 署名の検証に使用する公開鍵。 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | Public Certification Authority（CA;パブリック認証局）の信頼チェーン。 


| `csc-prod-ONTAP-Select-Deploy.pem` | キーの生成に使用する証明書。 


| `ONTAPdeploy.ova` | ONTAP Select用の製品インストール実行可能ファイル。 


| `ONTAPdeploy.ova.sig` | SHA-256アルゴリズムはハッシュ化され、Remote Support Agent（RSA）によって `csc-prod` インストーラのキーと署名。 
|===
. を確認します `ONTAPdeploy.ova.sig` ファイルで関連する証明書と検証コマンドが使用されています。
. 次のコマンドを使用して署名を確認します。
+
[listing]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== 仮想マシンの導入

OVF VMイメージを使用して、ONTAP Select Deploy VMをインストールして起動する必要があります。インストールプロセスの一環として、DHCPまたは静的IP設定を使用するようにネットワークインターフェイスを設定します。

.作業を開始する前に
ESXiハイパーバイザーの場合は、ONTAP Select Deploy VMの導入を準備する必要があります。

* VMware クライアント統合プラグインのインストールまたは同様の設定を必要に応じて実行し、 OVF 機能を有効にします
* Deploy VMにIPアドレスを動的に割り当てる場合は、VMware環境でDHCPを有効にします。


ESXiハイパーバイザーとKVMハイパーバイザーの場合は、VMの作成時に使用する設定情報（VMの名前、外部ネットワーク、ホスト名など）が必要です。静的なネットワーク設定を定義する場合は、次の追加情報 が必要です。

* Deploy VMのIPアドレス
* ネットマスク
* ゲートウェイ（ルータ）の IP アドレス
* プライマリ DNS サーバの IP アドレス
* 2 番目の DNS サーバの IP アドレス
* DNS 検索ドメイン


.このタスクについて
vSphere を使用する場合は、 Deploy OVF テンプレートウィザードのフォームを使用して、ネットワーク設定を含むすべての Deploy 設定情報を指定します。ただし、このフォームを使用しない場合は、Deploy VMのコンソールを使用してネットワークを設定できます。

.手順
実行する手順は、ESXiハイパーバイザーとKVMハイパーバイザーのどちらを使用しているかによって異なります。

[role="tabbed-block"]
====
.ESXi
--
. vSphere Client にアクセスしてサインインします。
. 階層内の適切な場所に移動し、 [Deploy OVF Template* （ OVF テンプレートの展開） ] を選択します。
. OVA ファイルを選択し、 Deploy OVF Template ウィザードを実行して、環境に適したオプションを選択します。
+
管理者アカウントのパスワードを定義する必要があります。Deploy ユーティリティへのサインインの際に、このパスワードを指定する必要があります。

. 導入ウィザードで入力した内容に基づいて、VMの導入後に新しいVMを選択して電源をオンにします（まだオンになっていない場合）。
. 必要に応じて、VMコンソールを使用してDeployネットワークを設定できます。
+
.. コンソール * タブをクリックして ESXi ホストのセットアップ・シェルにアクセスし、電源投入プロセスを監視します。
.. 次のプロンプトが表示されるまで待ちます。
+
ホスト名：

.. ホスト名を入力し、 *Enter* キーを押します。
.. 次のプロンプトが表示されるまで待ちます。
+
admin ユーザのパスワードを指定します。

.. パスワードを入力し、 *Enter* キーを押します。
.. 次のプロンプトが表示されるまで待ちます。
+
DHCP を使用してネットワーク情報を設定しますか？[n] ：

.. 静的IP設定を定義する場合は「n *」、DHCPを使用する場合は「* y *」と入力し、* Enter *を選択します。
.. 静的な設定を選択した場合は、必要に応じてすべてのネットワーク設定情報を指定します。




--
.KVM の略
--
. LinuxサーバでCLIにサインインします。
+
[listing]
----
ssh root@<ip_address>
----
. 新しいディレクトリを作成し、raw VMイメージを展開します。
+
[listing]
----
mkdir /home/select_deploy25
cd /home/select_deploy25
mv /root/<file_name> .
tar -xzvf <file_name>
----
. Deploy管理ユーティリティを実行するKVM VMを作成して起動します。
+
[listing]
----
virt-install --name=select-deploy --vcpus=2 --ram=4096 --os-variant=debian10 --controller=scsi,model=virtio-scsi --disk path=/home/deploy/ONTAPdeploy.raw,device=disk,bus=scsi,format=raw --network "type=bridge,source=ontap-br,model=virtio,virtualport_type=openvswitch" --console=pty --import --noautoconsole
----
. 必要に応じて、VMコンソールを使用してDeployネットワークを設定できます。
+
.. VMコンソールに接続します。
+
[listing]
----
virsh console <vm_name>
----
.. 次のプロンプトが表示されるまで待ちます。
+
[listing]
----
Host name :
----
.. ホスト名を入力し、* Enter *を選択します。
.. 次のプロンプトが表示されるまで待ちます。
+
[listing]
----
Use DHCP to set networking information? [n]:
----
.. 静的IP設定を定義する場合は「n *」、DHCPを使用する場合は「* y *」と入力し、* Enter *を選択します。
.. 静的な設定を選択した場合は、必要に応じてすべてのネットワーク設定情報を指定します。




--
====


== DeployのWebインターフェイスへのサインイン

Web ユーザインターフェイスにサインインして、 Deploy ユーティリティが使用可能であることを確認し、初期設定を実行する必要があります。

.手順
. ブラウザで IP アドレスまたはドメイン名を使用して、 Deploy ユーティリティにアクセスします。
+
https://<ip_address>/` にアクセスします

. 管理者（ admin ）アカウント名とパスワードを入力し、サインインします。
. * Welcome to ONTAP Select *ポップアップウィンドウが表示されたら、前提条件を確認し、* OK *を選択して続行します。
. 初めてサインインしたときに、 vCenter で使用できるウィザードを使用して Deploy をインストールしなかった場合は、プロンプトが表示されたら次の設定情報を入力します。
+
** 管理者アカウントの新しいパスワード（必須）
** AutoSupport （オプション）
** アカウントのクレデンシャルを使用する vCenter Server （オプション）




.関連情報
* link:task_cli_signing_in.html["SSHを使用したDeployへのサインイン"]
* link:deploy-evaluation-ontap-select-ovf-template.html["ONTAP Selectクラスタの90日間の評価用インスタンスを導入"]

