---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: Deploy vCenter プラグインは、 vSphere Web ユーザインターフェイスを使用して ONTAP Select クラスタを導入できます。 
---
= ONTAP Select クラスタの導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy vCenter プラグインは、 vSphere Web ユーザインターフェイスを使用して ONTAP Select クラスタを導入できます。



== 作業を開始する前に

ONTAP Select クラスタを導入する前に、 Deploy vCenter プラグインを使用する準備をしておく必要があります。



=== すべてのサイズのクラスタに共通の準備作業

クラスタのサイズに関係なく、いくつかの手順を実行する必要があります。

* Deploy vCenter プラグインの詳細については、 _ Getting started _ セクションを参照してください。
* ONTAP Select Deploy 管理ユーティリティがインストールされて実行されていることを確認します。
* Deploy vCenter プラグインをインストールする。
* ONTAP Select クラスタを実行するハイパーバイザーホストを準備します。
* クラスタ内のノードに必要なストレージライセンスファイルを取得します。
* 次のアカウントのクレデンシャルを取得します。
+
** 管理者アカウントを導入
** プラグインへのアクセス権を持つ vCenter アカウント


* 必要に応じて、 Deploy SSL 証明書を「信頼されたルート認証局」として Windows 証明書マネージャにインストールします。
* Deploy ユーティリティが、 vCenter サーバでポート 443 へのネットワークアクセスを許可していることを確認してください。




=== マルチノードクラスタ向けの追加の準備

一般的な準備作業に加えて、マルチノードクラスタを導入する前に、 Deploy ネットワークチェッカーに関する知識が必要です。



== ハイパーバイザーホストの追加

クラスタを導入する前に、 ONTAP Select ノードを実行する Deploy ユーティリティにハイパーバイザーホストを追加できます。必要に応じて、クラスタ作成ダイアログの一部としてホストを追加することもできます。

.作業を開始する前に
「 ONTAP Select クラスタの導入の準備」を参照してください。

.このタスクについて
クラスタのサイズに基づいて、 1 つ以上のホストを追加できます。

.手順
. ブラウザを使用して、 vSphere HTML5 経由で vCenter Server にサインインします。
. ツールバーの * メニュー * をクリックし、 * グローバルインベントリリスト * をクリックします。
. 左側のペインで、 * ONTAP Select Deploy* をクリックし、 * Hosts * タブをクリックします。
. 右側の [ * 追加（ Add * ） ] をクリックします。
. ホストのホスト名または IP アドレスを入力して、 [ * 追加 * ] または [ * 追加 / 終了 * ] をクリックします。




== シングルノードクラスタを作成しています

vSphere Web Client を介して VMware vCenter プラグインを使用し、単一ノードで構成される ONTAP Select クラスタを導入できます。

.作業を開始する前に
ONTAP Select クラスタの導入とハイパーバイザーホストの追加の準備を確認しておく必要があります。クラスタを作成する前、またはシングルノードクラスタを作成する際に ONTAP Select ノードを実行するホストを追加できます。

.手順
. ブラウザを使用して、 vSphere HTML5 経由で vCenter Server にサインインします。
. 上部の [*Menu*]( メニュー ) をクリックし、 [*Global Inventory Lists*]( グローバルインベントリリスト ) をクリックします。
. 左側のペインで * ONTAP Select Cluster* をクリックし、 * New ONTAP Select * をクリックします。
+
SSL 証明書をまだ承認していない場合は、警告メッセージの IP リンクをクリックし、証明書を受け入れます。次に、 vCenter のページに戻り、警告メッセージのリンクをクリックしてページをリロードします。

. New ONTAP Select * ページで、クラスタの詳細を入力し、 * Done * をクリックします。
. [ ノードのセットアップ * （ * Node Setup * ） ] セクションで、設定を指定し、ライセンスを選択します。
+
必要に応じて、デフォルトのノード名を変更したり、新しいライセンスをアップロードしたりできます。

. [ ハイパーバイザーとネットワーク * ] セクションで、インスタンスタイプ、ホスト、およびネットワークを選択します。
+
必要に応じてホストを追加できます。ノードのライセンスがインスタンスタイプを満たしているか、超えている必要があります。

. [* ストレージ ] セクションで、ストレージ容量とストレージプールを選択します。
+
必要に応じて、 Premium ライセンスの使用時にソフトウェア RAID を有効にすることができます。

. Done をクリックし、クラスタの構成を確認します。
+
必要に応じて、各セクションの [Edit] をクリックすると、設定を変更できます。

. 「 * 次へ * 」をクリックします。
. ONTAP 管理者パスワードを入力し、 * クラスタの作成 * をクリックしてクラスタ作成プロセスを開始し、確認のポップアップウィンドウで * OK * をクリックします。
+
クラスタが作成されるまで、 30 分程度かかる場合があります。

. ページをリフレッシュして新しいクラスタを選択し、 * Summary * と * Details * をクリックして、複数ステップのクラスタ作成プロセスを監視します。
+

TIP: クラスタの作成処理が開始され、完了できなかった場合は、定義済みの ONTAP 管理パスワードが登録されません。この場合、「 admin 」アカウントを持つパスワード「 changeme123 」を使用して、 ONTAP Select クラスタの管理インターフェイスにアクセスできます。



.完了後
* ONTAP Select AutoSupport 機能が有効になっていることを確認します。
* ONTAP Select Deploy の設定データをバックアップします。




== マルチノードクラスタを作成する

vSphere Web Client を介して VMware vCenter プラグインを使用し、複数のノードで構成される ONTAP Select クラスタを導入できます。

.作業を開始する前に
ONTAP Select クラスタの導入とハイパーバイザーホストの追加の準備を確認しておく必要があります。クラスタを作成する前、またはマルチノードクラスタの作成時に ONTAP Select ノードを実行するホストを追加できます。

.このタスクについて
ONTAP Select マルチノードクラスタは偶数個のノードで構成されます。ノードは常に HA ペアとして参加します。

.手順
. ブラウザを使用して、 vSphere HTML5 経由で vCenter Server にサインインします。
. 上部の [*Menu*]( メニュー ) をクリックし、 [*Global Inventory Lists*]( グローバルインベントリリスト ) をクリックします。
. 左側のペインで * ONTAP Select Cluster* をクリックし、 * New ONTAP Select * をクリックします
+
SSL 証明書をまだ承認していない場合は、警告メッセージの IP リンクをクリックし、証明書を受け入れます。次に、 vCenter のページに戻り、警告メッセージのリンクをクリックしてページをリロードします。

. New ONTAP Select * ページで、クラスタの詳細を入力し、 * Done * をクリックします。
+
クラスタの MTU サイズを設定する理由がないかぎり、デフォルト値を受け入れ、 Deploy は必要に応じて調整を行う必要があります。

. ノードのセットアップ * セクションで、構成を指定し、 HA ペアの 2 つのノードのライセンスを選択します。
+
必要に応じて、デフォルトのノード名を変更したり、新しいライセンスをアップロードしたりできます。

. 「 * ハイパーバイザーとネットワーク * 」セクションで、各ノードのインスタンスタイプ、ホスト、およびネットワークを選択します。
+
必要に応じてホストを追加できます。3 つのネットワークを選択する必要があります。内部ネットワークを管理ネットワークまたはデータネットワークと同じにすることはできません。ノードのライセンスタイプがインスタンスタイプを満たしているか、それを超えている必要があります。

. [* ストレージ ] セクションで、ストレージ容量とストレージプールを選択します。
+
必要に応じて、 Premium ライセンスの使用時にソフトウェア RAID を有効にすることができます。

. クラスタのノード数が 4 つ以上の場合は、最初の HA ペアで使用した手順と同じ手順に従って、追加の HA ペアでノードを構成する必要があります。
. Done をクリックし、クラスタの構成を確認します。
+
必要に応じて、各セクションの * Edit * をクリックすると、設定を変更できます。

. 必要に応じて、ネットワーク接続チェッカーを実行して、内部クラスタネットワーク上のノード間の接続をテストします。
. 「 * 次へ * 」をクリックします。
. ONTAP 管理者パスワードを入力し、 * クラスタの作成 * をクリックしてクラスタ作成プロセスを開始し、確認のポップアップウィンドウで * OK * をクリックします。
+
クラスタが作成されるまで、 30 分程度かかる場合があります。

. ページをリフレッシュして新しいクラスタを選択し、 * Summary * と * Details * をクリックして、複数ステップのクラスタ作成プロセスを監視します。
+

TIP: クラスタの作成処理が開始され、完了できなかった場合は、定義済みの ONTAP 管理パスワードが登録されません。この場合、「 admin 」アカウントを持つパスワード「 changeme123 」を使用して、 ONTAP Select クラスタの管理インターフェイスにアクセスできます。



.完了後
* ONTAP Select AutoSupport 機能が有効になっていることを確認します。
* ONTAP Select Deploy の設定データをバックアップします。

