---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加できます。イメージをインストールしたら、 ONTAP Select クラスタを導入する際にそのイメージを使用できます。 
---
= ONTAP Select イメージを Deploy に追加しています
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select イメージを Deploy 管理ユーティリティのインスタンスに追加できます。イメージをインストールしたら、 ONTAP Select クラスタを導入する際にそのイメージを使用できます。



== 作業を開始する前に

ONTAP Select イメージを Deploy のインスタンスに追加するプロセスは、大きく分けて次の 4 つのステップで構成されます。

. インストールイメージをダウンロードしています
. Deploy 仮想マシンへのインストールイメージのアップロード
. インストールイメージを追加しています
. 使用可能なインストールイメージを表示します


新しい ONTAP Select イメージを Deploy に追加する前に、不要なイメージを削除する必要があります。


NOTE: ONTAP Select イメージは、 Deploy ユーティリティのインスタンスに含まれている元のバージョンよりも前のバージョンでのみ追加してください。ネットアップから提供される新しいバージョンの ONTAP Select は、サポートされていない構成では追加できません。



== インストールイメージをダウンロードしています

ONTAP Select イメージを Deploy ユーティリティのインスタンスに追加するプロセスを開始するには、ネットアップサポートサイトからインストールイメージをダウンロードする必要があります。ONTAP Select インストールイメージは、単一の圧縮ファイルとしてフォーマットされています。

.手順
. Web ブラウザからネットアップサポートサイトにアクセスし、「 * Support Quick Links * 」をクリックします。
. [* Top Tasks] の下の [* Download Software* ] をクリックして、サイトにサインインします。
. [ * 製品の検索 * ] をクリックします。
. 下にスクロールし、 * ONTAP Select * をクリックします。
. [* Other Available Select Software* （その他の利用可能な Select ソフトウェアの選択 * ） ] で、 [* Deploy Upgrade] 、 [Node Upgrade] 、 [Image Install* （イメージ
. アップグレードパッケージの目的のリリースを選択します。
. エンドユーザライセンス契約（ EULA ）を確認し、「 * 同意して続行」をクリックします。
. 適切なパッケージを選択してダウンロードし、環境に応じてすべてのプロンプトに応答します。




== Deploy へのインストールイメージのアップロード

ONTAP Select インストールイメージを取得したら、ファイルを Deploy 仮想マシンにアップロードする必要があります。

インストールイメージファイルをローカルワークステーションで使用できるようにしておく必要があります。また、 Deploy 管理者ユーザアカウントのパスワードが必要です。

このタスクは、ファイルを Deploy 仮想マシンにアップロードする方法の 1 つです。ご使用の環境に適したその他のオプションがある場合もあります。

.ステップ
. ローカルワークステーション上のコマンドシェルで、イメージファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


ノードインストールファイルは、管理者ユーザのホームディレクトリに格納されます。



== インストールイメージを追加しています

新しいクラスタの導入時に使用できるように、 ONTAP Select インストールイメージを Deploy images ディレクトリに追加できます。

Deploy ユーティリティの仮想マシンでインストールイメージファイルを配置したディレクトリを確認しておく必要があります。このファイルは、管理者のホームディレクトリにあると想定されます。

.手順
. 管理者（ admin ）アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. Bash シェルを起動します。
+
シェル bash

. インストールイメージファイルを images ディレクトリに配置します。
+
例： tar -xf image_v_93_install_esx.tgz -C/opt/NetApp/images/`





== 使用可能なインストールイメージを表示します

新しいクラスタの導入時に使用できる ONTAP Select イメージを表示できます。

.手順
. Deploy ユーティリティの仮想マシンのオンラインドキュメントの Web ページにアクセスし、管理者（ admin ）アカウントを使用してサインインします。
+
http://<FQDN|IP_ADDRESS>/api/ui` にアクセスします

+
Deploy 仮想マシンのドメイン名または IP アドレスを使用してください。

. ページの下部に移動し、 * Deploy * をクリックして、 * Get/images * をクリックします。
. [* 試してみましょう !* ] をクリックすると、使用可能な ONTAP Select イメージが表示されます。
. 目的のイメージが使用可能であることを確認します。

