---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: ONTAP Select Deploy ユーティリティに障害が発生した場合や、何らかの理由でユーティリティが使用できない場合は、 ONTAP Select のノードとクラスタを管理できなくなります。また、 Deploy に含まれるメディエーターサービスを使用できないため、すべての 2 ノードクラスタの HA 機能が失われます。リカバリ不能な障害が発生した場合は、 Deploy ユーティリティのインスタンスをリカバリして、管理と HA の機能をリストアする必要があります。 
---
= 2ノードクラスタのONTAP Select Deployユーティリティをリカバリする
:allow-uri-read: 
:firstname: :hardbreaks:reints
:author: :hardbreaks:reints
:authorinitials: :
:authors: :hardbreaks:reints
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy ユーティリティに障害が発生した場合や、何らかの理由でユーティリティが使用できない場合は、 ONTAP Select のノードとクラスタを管理できなくなります。また、 Deploy に含まれるメディエーターサービスを使用できないため、すべての 2 ノードクラスタの HA 機能が失われます。リカバリ不能な障害が発生した場合は、 Deploy ユーティリティのインスタンスをリカバリして、管理と HA の機能をリストアする必要があります。



== デプロイユーティリティの回復の準備

デプロイ ユーティリティのインスタンスの回復を確実に成功させるには、その前に準備を行う必要があります。いくつかの管理手順に精通し、必要な情報を把握している必要があります。

.手順
. ハイパーバイザー環境にONTAP Select Deploy ユーティリティの新しいインスタンスをインストールできることを確認します。
+
link:task_install_deploy.html["ONTAP Select Deployユーティリティのインストールについて学習します"]

. ONTAP Selectクラスタにログインし、 ONTAPクラスタ シェル (CLI) にアクセスできることを確認します。
. ONTAP Select 2 ノード クラスタを含む、障害が発生した Deploy ユーティリティ インスタンスからの構成データのバックアップがあるかどうかを確認します。クラスタが含まれていないバックアップがある可能性があります。
. 使用した回復手順に応じて、デプロイ構成データのバックアップを復元できることを確認します。
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["デプロイ構成データを新しい仮想マシンに復元する方法について説明します。"]

. 失敗した元の Deploy ユーティリティ仮想マシンの IP アドレスがわかります。
. 容量プールまたは容量階層ライセンスが使用されているかどうかを決定します。容量プールライセンスを使用する場合は、デプロイインスタンスを復旧またはリストアした後、各容量プールライセンスを再インストールする必要があります。
. ONTAP Select Deploy ユーティリティのインスタンスをリカバリするときに使用する手順を決定します。この決定は、 ONTAP Selectの2ノードクラスタを含む、障害が発生した元のDeployユーティリティの設定データのバックアップがあるかどうかに基づいて行われます。
+
[cols="35,65"]
|===
| 2 ノードクラスタを含む Deploy のバックアップがあるか | 回復手順を使用します... 


| はい。 | <<restore-deploy-backup,設定のバックアップを使用したDeployユーティリティのインスタンスのリストア>> 


| いいえ | <<restore-and-recover-deploy,Deployユーティリティのインスタンスを再設定してリカバリする>> 
|===




== 設定のバックアップを使用したDeployユーティリティのインスタンスのリストア

2 ノードクラスタを含む、障害が発生した Deploy ユーティリティのインスタンスのバックアップがある場合は、新しい Deploy 仮想マシンのインスタンスに設定データをリストアできます。次に、 ONTAP Select クラスタ内の 2 つのノードの追加設定を実行して、リカバリを完了する必要があります。

.作業を開始する前に
2 ノード クラスターを含む元の失敗したデプロイ仮想マシンから構成データをバックアップします。ノードクラスタのONTAP CLIにサインインでき、2つのノードのONTAP名を知っている必要があります。

.このタスクについて
リストアする設定のバックアップには 2 ノードクラスタが含まれているため、メディエーターの iSCSI ターゲットとメールボックスは、新しい Deploy ユーティリティの仮想マシンに再作成されます。

.手順
. ONTAP Select Deploy ユーティリティの新しいインスタンスを準備します。
+
.. 新しい Deploy ユーティリティの仮想マシンをインストールします。
.. Deploy の設定を以前のバックアップから新しい仮想マシンにリストアします。
+
インストールとリストアの手順の詳細については、関連するタスクを参照してください。



. ONTAP Select の 2 ノードクラスタの ONTAP コマンドラインインターフェイスにサインインします。
. advanced 権限モードに切り替えます。
+
[source, cli]
----
set adv
----
. 新しい Deploy 仮想マシンの IP アドレスが元の Deploy 仮想マシンと異なる場合は、古いメディエーター iSCSI ターゲットを削除し、新しいターゲットを追加します。
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
「 <IP_address> 」パラメータは、新しい Deploy 仮想マシンの IP アドレスです。

+
これらのコマンドを使用すると、新しい Deploy ユーティリティの仮想マシン上のメールボックスディスクを ONTAP Select ノードで検出できます。

. メディエーターディスクの名前を特定します。
+
[source, cli]
----
disk show -container-type mediator
----
. メールボックスディスクを 2 つのノードに割り当てます。
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. ストレージフェイルオーバーが有効になっていることを確認します。
+
[source, cli]
----
storage failover show
----


.完了後
容量プール ライセンスを使用する場合は、各容量プール ライセンスを再インストールします。見るlink:task_adm_licenses.html#reinstall-a-capacity-pool-license["容量プールライセンスの再インストール"]詳細については、こちらをご覧ください。



== Deployユーティリティのインスタンスを再設定してリカバリする

2 ノード クラスターを含む、障害が発生した Deploy ユーティリティ インスタンスのバックアップがない場合は、新しい Deploy 仮想マシンでメディエーター iSCSI ターゲットとメールボックスを構成します。次に、 ONTAP Selectクラスタ内の 2 つのノードの追加構成を実行して、リカバリを完了します。

.作業を開始する前に
新しいデプロイ ユーティリティ インスタンスのメディエーター ターゲットの名前があることを確認します。ノードクラスタのONTAP CLIにサインインでき、2つのノードのONTAP名を知っている必要があります。

.このタスクについて
必要に応じて、設定のバックアップを新しい Deploy 仮想マシンにリストアできます。 2 ノードクラスタがバックアップに含まれていなくてもリストアは可能です。リストアで 2 ノードクラスタが再作成されることはないため、 Deploy の ONTAP Select オンラインドキュメントの Web ページを使用して、メディエーターの iSCSI ターゲットとメールボックスを新しい Deploy ユーティリティのインスタンスに手動で追加する必要があります。2 ノードクラスタにサインインし、 2 つのノードの ONTAP 名を確認しておく必要があります。


NOTE: リカバリ手順 の目的は、 2 ノードクラスタを正常な状態にリストアして、通常の HA テイクオーバー処理とギブバック処理を実行できるようにすることです。

.手順
. ONTAP Select Deploy ユーティリティの新しいインスタンスを準備します。
+
.. 新しい Deploy ユーティリティの仮想マシンをインストールします。
.. 必要に応じて、 Deploy の設定を以前のバックアップから新しい仮想マシンにリストアします。
+
以前のバックアップをリストアする場合、新しい Deploy インスタンスには 2 ノードクラスタが含まれません。インストールとリストアの手順の詳細については、関連情報のセクションを参照してください。



. ONTAP Select の 2 ノードクラスタの ONTAP コマンドラインインターフェイスにサインインします。
. advanced 権限モードに切り替えます。
+
[source, cli]
----
set adv
----
. メディエーターの iSCSI ターゲット名を取得します。
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 新しい Deploy ユーティリティの仮想マシンのオンラインドキュメント Web ページにアクセスし、 admin アカウントを使用してサインインします。
+
http://<ip_address>/api/ui` にアクセスします

+
Deploy 仮想マシンの IP アドレスを使用する必要があります。

. *Mediator* を選択し、*GET /mediators* を選択します。
. *試してみる*を選択すると、Deploy によって管理されるメディエーターのリストが表示されます。
+
目的のメディエーターインスタンスの ID をメモします。

. *Mediator* を選択し、次に *POST* を選択します。
. mediator_id の値を指定します
. 横にある*モデル*を選択してください `iscsi_target`名前の値を完了します。
+
iqn 名前パラメータのターゲット名を使用します。

. *試してみる* を選択して、メディエーター iSCSI ターゲットを作成します。
+
要求が成功すると、 HTTP ステータスコード 200 が表示されます。

. 新しい Deploy 仮想マシンの IP アドレスが元の Deploy 仮想マシンと異なる場合は、 ONTAP の CLI を使用して、古いメディエーターの iSCSI ターゲットを削除し、新しいターゲットを追加する必要があります。
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
「 <IP_address> 」パラメータは、新しい Deploy 仮想マシンの IP アドレスです。

+
これらのコマンドを使用すると、新しい Deploy ユーティリティの仮想マシン上のメールボックスディスクを ONTAP Select ノードで検出できます。

. メディエーターディスクの名前を特定します。
+
[source, cli]
----
disk show -container-type mediator`
----
. メールボックスディスクを 2 つのノードに割り当てます。
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. ストレージフェイルオーバーが有効になっていることを確認します。
+
[source, cli]
----
storage failover show
----


.完了後
容量プール ライセンスを使用する場合は、各容量プール ライセンスを再インストールします。見るlink:task_adm_licenses.html#reinstall-a-capacity-pool-license["容量プールライセンスの再インストール"]詳細については、こちらをご覧ください。
