---
sidebar: sidebar 
permalink: task_vpi_adm_network.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, network, networking 
summary: ネットワークのいくつかの側面を探索して表示できます。 
---
= ネットワーク接続の確認
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ネットワークのいくつかの側面を探索して表示できます。



== ネットワーク接続の確認

内部クラスタネットワーク上にある 2 つ以上の ONTAP Select ノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタの導入前に実行して、原因 で処理が失敗する可能性のある問題を検出する必要があります。また、クラスタを導入してオンラインにしたあとに接続テストを実行することもできます。

.このタスクについて
テストを開始するたびに、新しいプロセスがバックグラウンドで作成され、一意の実行識別子が割り当てられます。一度にアクティブにできるランは 1 つだけです。

このテストは常にクイックモードで実行され、基本的な無停止テストが実行されます。ping テストが、ネットワークの MTU サイズと vSwitch のテストとともに実行されます。

.手順
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで、 [* ONTAP Select Deploy* （ * グローバルインベントリ導入 * ） ]
. [* 管理（ * Administration ） ] タブをクリックします。
. [ * ネットワーク * ] オプションを展開し、 [ * 接続性チェッカー * ] をクリックします。
. Run New * をクリックして、テストを開始します。
. 必要に応じて、 * Filtering * をクリックして、表示されるテストの詳細を制限するフィルタを作成します。




== メディエーターサービスのステータスを表示する

各 ONTAP Select 2 ノードクラスタはメディエーターサービスによって監視されます。このサービスは、ノードで共有する HA 機能の管理を支援します。Deploy 管理ユーティリティで定義されている各 2 ノードクラスタのメディエーターサービスのステータスを表示できます。

.このタスクについて
次のような各メディエーターの設定を表示できます。

* 現在のステータス
* ONTAP Select ノード × 2
* HA 制御情報を格納する iSCSI ターゲット


.手順
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで、 [* ONTAP Select Deploy* （ * グローバルインベントリ導入 * ） ]
. [* 管理（ * Administration ） ] タブをクリックします。
. [* Mediator* ] オプションを展開し、 [ * ステータス * ] をクリックします。
. 必要に応じて、 * Filtering * をクリックして、メディエーターサービスによって監視される 2 ノードクラスタの表示をカスタマイズするフィルタを作成します。

