---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: コマンドラインインターフェイスを使用して、 Deploy 管理ユーティリティの既存のインスタンスを新しい仮想マシンに移行できます。 
---
= 新しい仮想マシンへのDeployインスタンスの移行
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コマンドラインインターフェイスを使用して、 Deploy 管理ユーティリティの既存のインスタンスを新しい仮想マシンに移行できます。

この手順 は、元の仮想マシンの設定データを使用する新しい仮想マシンの作成に基づいています。新しい仮想マシンと元の仮想マシンで実行する Deploy ユーティリティのバージョンとリリースが同じである必要があります。バージョンとリリースが異なる Deploy ユーティリティに移行することはできません。



== Deployの設定データをバックアップする

仮想マシンの移行の一環として、 Deploy の設定データのバックアップを作成する必要があります。また、 ONTAP Select クラスタを導入したあとにバックアップを作成する必要があります。データは単一の暗号化ファイルに保存され、ローカルワークステーションにダウンロードできます。

.作業を開始する前に
* Deploy はバックアップ処理中に他のタスクを実行しないでください。
* 元のDeploy仮想マシンイメージを保存します。
+

CAUTION: Deployの設定データを元の仮想マシンから新しい仮想マシンにリストアする場合は、この手順の後半の工程で元のDeploy仮想マシンイメージが必要です。



.このタスクについて
作成するバックアップファイルには、仮想マシンのすべての設定データがキャプチャされます。このデータには、 ONTAP Select クラスタを含む導入環境の要素が説明されています。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. Deploy サーバの内部ディレクトリに格納されている Deploy の設定データのバックアップを作成します。
+
'deploy backup create

. プロンプトが表示されたら、バックアップのパスワードを入力します。
+
バックアップファイルは、パスワードに基づいて暗号化されます。

. システムで使用可能なバックアップを表示します。
+
'deploy backup show -detailed

. [ 作成日 ] フィールドの日付に基づいてバックアップファイルを選択し、 * ダウンロード URL * の値を記録します。
+
バックアップファイルには、 URL からアクセスできます。

. Curl などの Web ブラウザまたはユーティリティを使用して、 URL を指定してバックアップファイルをローカルワークステーションにダウンロードします。




== Deploy仮想マシンの新しいインスタンスをインストールする

Deploy 仮想マシンの新しいインスタンスを作成する必要があります。このインスタンスは、元の仮想マシンの設定データを使用して更新できます。

.作業を開始する前に
VMware 環境で ONTAP Select Deploy 仮想マシンのダウンロードと導入に使用する手順を理解しておく必要があります。

.このタスクについて
このタスクについては大まかに説明します。

.手順
. Deploy 仮想マシンの新しいインスタンスを作成します。
+
.. 仮想マシンイメージをダウンロードします。
.. 仮想マシンを導入し、ネットワークインターフェイスを設定します。
.. SSH を使用して Deploy ユーティリティにアクセスします。




.関連情報
link:task_install_deploy.html["ONTAP Select Deploy をインストールする"]



== 新しい仮想マシンへのDeployの設定データのリストア

元の Deploy ユーティリティの仮想マシンの設定データを新しい仮想マシンにリストアする必要があります。データは、ローカルワークステーションからアップロードする必要のある 1 つのファイルに格納されます。

.作業を開始する前に
以前のバックアップの設定データが必要です。データは 1 つのファイルに格納され、ローカルワークステーションで使用できる必要があります。

.手順
. ローカルワークステーション上のコマンドシェルで、 sftp ユーティリティを使用して、バックアップファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. 構成データをリストアします。
+
'deploy backup restore -path pathname - filename filename

+
例

+
'deploy backup restore-path/home/admin-filename deploy_20180601162151.tar.gz


