---
sidebar: sidebar 
permalink: task_vpi_adm_support.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, diagnostics, support 
summary: ONTAP Select の管理の一環として実行できる、関連する診断タスクとサポートタスクがいくつかあります。 
---
= 診断とサポート
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の管理の一環として実行できる、関連する診断タスクとサポートタスクがいくつかあります。



== システム設定の表示

vCenter プラグインを使用して、 Deploy 管理ユーティリティの基本設定を表示できます。

.手順
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで、 [* ONTAP Select Deploy* （ * グローバルインベントリ導入 * ） ]
. [* 管理（ * Administration ） ] タブをクリックします。
. [ * システム * ] オプションを展開し、 [ * 設定 * ] をクリックします。
. 必要に応じてシステム構成を更新し、 * 保存 * をクリックします。




== イベントメッセージの表示

Deploy 管理ユーティリティには、システムのアクティビティに関する情報を提供するイベントロギングファシリティが含まれています。問題をデバッグする場合やサポートから指示があった場合に、 Deploy プラグインを使用してイベントログの内容を表示できます。

次に示すいくつかの特性に基づいて、イベントメッセージのリストをフィルタできます。

* カテゴリ
* を入力します
* レベル
* インスタンス


.手順
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで、 [* ONTAP Select Deploy* （ * グローバルインベントリ導入 * ） ]
. [* 管理（ * Administration ） ] タブをクリックします。
. [* Events * （イベント * ） ] オプションを展開して、 [* Deploy * （展開） ] をクリック
. 必要に応じて、フィルタリングをクリックし、表示するイベントメッセージを制限するフィルタを作成します。




== AutoSupport を有効にします

AutoSupport は、ネットアップが ONTAP Select をサポートするために使用する主要なトラブルシューティングツールです。AutoSupport 機能は必要に応じて有効または無効にすることができます。

新しいクラスタの導入が完了したら、 AutoSupport が有効になっていることを確認する必要があります。AutoSupport は必要な場合にのみ無効にしてください。AutoSupport を無効にしてもデータは収集されますが、ネットアップには送信されません。

.手順
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで、 [* ONTAP Select Deploy* （ * グローバルインベントリ導入 * ） ]
. [* 管理（ * Administration ） ] タブをクリックします。
. * AutoSupport * オプションを展開し、 * Configure * をクリックします
. 必要に応じて AutoSupport を有効または無効にします。




== AutoSupport パッケージを生成しています

Deploy vCenter Plug-in では、 AutoSupport パッケージを生成できます。問題をデバッグする場合やサポートから指示があったときにパッケージを生成する必要があります。

次の AutoSupport パッケージを生成できます。

* ONTAP Select Deploy ユーティリティで作成されたログファイルの導入
* トラブルシューティングハイパーバイザーホストと ONTAP Select ノードに関するトラブルシューティング情報とデバッグ情報
* ハイパーバイザーホストと ONTAP Select ノードに関するパフォーマンスの情報です


.手順
. [* グローバルインベントリリスト * （ Global Inventory Lists * ） ] ペインで、 [* ONTAP Select Deploy* （ * グローバルインベントリ導入 * ） ]
. [* 管理（ * Administration ） ] タブをクリックします。
. [*Generate] AutoSupport オプションを展開し、 [*Generate] をクリックします。
. タイプを選択してパッケージの概要 を指定するか、ケース番号を入力して、「 AutoSupport を生成」をクリックします。
. 左側のペインで、 AutoSupport * の下の *History* をクリックし、パッケージを探します。
+
必要に応じて、 [* 更新（ Refresh ） ] をクリックできます。



AutoSupport パッケージは、標準の Deploy ユーティリティのユーザインターフェイスを使用してワークステーションにダウンロードできます。Deploy vCenter プラグインを使用してパッケージをダウンロードすることはできません。
