---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: 容量階層のライセンスを使用している場合は、ONTAP Selectノードごとにライセンスファイルを取得する必要があります。ライセンスファイルではノードのストレージ容量を定義します。このファイルは、ネットアップが割り当てた一意の 9 桁のシリアル番号を使用してノードにロックされます。 
---
= ONTAP Selectの大容量階層ライセンスを取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量階層のライセンスを使用している場合は、ONTAP Selectノードごとにライセンスファイルを取得する必要があります。ライセンスファイルではノードのストレージ容量を定義します。このファイルは、ネットアップが割り当てた一意の 9 桁のシリアル番号を使用してノードにロックされます。

.作業を開始する前に
* NetAppによってONTAP Selectノードに割り当てられた9桁のライセンス シリアル番号が必要です。
* ライセンス ファイルを取得する前に、注文書の発送日から少なくとも 24 時間待つ必要があります。
* link:sizing-capacity-tier-license.html["容量階層ライセンスのサイジングに関する考慮事項"]をレビューしました。


.このタスクについて
Capacity Tiers ライセンスを必要とする ONTAP Select ノードごとにこのタスクを実行する必要があります。

.手順
. link:https://register.netapp.com/register/getlicensefile["ONTAP Selectライセンスサイトにアクセスする"^].
. ネットアップアカウントのクレデンシャルを使用してサインインします。
. [*License Generator] ページで、ドロップダウン・ボックスから目的のライセンス製品を選択します。
. *製品シリアル番号*を含む、*ライセンス ジェネレーター* ページの残りのフィールドに入力します。
+
「製品シリアル番号」は、ONTAP Selectノードのシリアル番号です。

. *送信*を選択します。
. 要求の検証が完了したら、ライセンスの配信方法を選択します。
+
*ライセンスのダウンロード*または*ライセンスのメール送信*のいずれかを選択できます。

. 選択した配信方法に基づいてライセンスファイルを受け取ったことを確認します。


.完了後
ライセンスファイルを ONTAP Select ノードに適用するには、 Deploy 管理ユーティリティにアップロードする必要があります。
