---
sidebar: sidebar 
permalink: task_adm_resize.html 
keywords: administer, administering, web, resizing nodes, resizing 
summary: ONTAP Select クラスタを導入したら、 Deploy 管理ユーティリティを使用してノードのハイパーバイザーインスタンスタイプをアップグレードできます。 
---
= ONTAP Selectクラスタノードのサイズを変更する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select クラスタを導入したら、 Deploy 管理ユーティリティを使用してノードのハイパーバイザーインスタンスタイプをアップグレードできます。


NOTE: 容量階層ライセンスモデルと容量プールライセンスモデルを使用する場合は、クラスタノードのサイズ変更処理を実行できます。


NOTE: Largeインスタンスタイプへのサイズ変更は、ESXiでのみサポートされます。

.作業を開始する前に
クラスタはオンライン状態である必要があります。

.このタスクについて
このタスクでは、 Deploy の Web ユーザインターフェイスの使用方法について説明します。Deploy CLI を使用して、インスタンスのサイズを変更することもできます。どのインターフェイスを使用するかに関係なく、サイズ変更処理に要する時間はいくつかの要因によって大きく異なり、完了までに長い時間がかかることがあります。サイズを変更できるのは、ノードのサイズを大きくする場合だけです。

.手順
. 管理者アカウントを使用して、 Deploy ユーティリティの Web ユーザインターフェイスにサインインします。
. ページ上部の * Cluster * タブを選択し、リストから目的のクラスターを選択します。
. クラスターの詳細ページで、ページ右側の歯車アイコンを選択し、*インスタンスのサイズ変更*を選択します。
. *インスタンス タイプ*を選択して ONTAP クレデンシャルを指定し、*変更*を選択します。


.完了後
サイズ変更処理が完了するまで待つ必要があります。
