---
sidebar: sidebar 
permalink: task_cli_upgrade_esxi65.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 6.5 
summary: VMware ESXiでONTAP Selectを実行している場合は、ESXiソフトウェアを以前のサポート対象バージョンからESXi 7.0以降にアップグレードできます。アップグレードする前に、プロセスを理解し、適切なアップグレード手順 を選択する必要があります。 
---
= ONTAP Select VMware ESXiをバージョン7.0以降にアップグレードします。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware ESXiでONTAP Selectを実行している場合は、ESXiソフトウェアを以前のサポート対象バージョンからESXi 7.0以降にアップグレードできます。アップグレードする前に、プロセスを理解し、適切なアップグレード手順 を選択する必要があります。



== 作業を開始する前に

ONTAP Select クラスタをホストするハイパーバイザーで ESXi ソフトウェアをアップグレードする前に、環境に適したアップグレード手順 を準備して選択する必要があります。


CAUTION: VMware ESXi 6.5 にアップグレードする場合は、 ESXi U2 （ビルド 8294253 ）以降にアップグレードする必要があります。ESXi 6.5 U1 を使用すると、 VMware の既知のバグによって仮想マシンの障害にさらされる可能性があります。



=== VMware ESXiのアップグレード方法の理解

ESXi ソフトウェアのアップグレードは、 VMware で説明され、サポートされているプロセスです。ハイパーバイザーのアップグレードプロセスは、 ONTAP Select を使用する場合の大規模なアップグレード手順 の一部です。詳細については、VMwareのドキュメントを参照してください。



=== アップグレード手順を選択

いくつかのアップグレード手順があります。次の基準に基づいて、該当する手順 を選択する必要があります。

* ONTAP Select クラスタのサイズは、シングルノードクラスタとマルチノードクラスタのどちらでもサポートされます。
* ONTAP Select Deploy アップグレードは、 Deploy ユーティリティを使用する場合と使用しない場合の両方で使用できます。



TIP: Deploy 管理ユーティリティを使用するアップグレード手順 を選択する必要があります。

Deploy 管理ユーティリティを使用した ESXi のアップグレードは、より一般的で耐障害性に優れたオプションです。ただし、 Deploy を使用できない場合や使用できない場合があります。たとえば、以前のバージョンのONTAP SelectおよびDeploy管理ユーティリティでは、ESXi 7.0へのアップグレードはサポートされていません。

これらの旧バージョンを使用している場合にアップグレードを試行すると、 ONTAP Select 仮想マシンをブートできない状態のままにすることができます。この場合は、 Deploy を使用しないアップグレード手順 を選択する必要があります。を参照してください link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] を参照してください。



=== Deploy管理ユーティリティのアップグレード

Deploy ユーティリティを使用して手順 のアップグレードを実行する前に、 Deploy インスタンスのアップグレードが必要になることがあります。通常は、最新バージョンの Deploy にアップグレードする必要があります。Deploy ユーティリティで、使用する ONTAP Select のバージョンがサポートされている必要があります。詳細については、 ONTAP Select のリリースノートを参照してください。



=== 手順 の更新が完了したら

Deploy ユーティリティを使用するアップグレード手順 を選択する場合は、すべてのノードをアップグレードしたあとに、 Deploy を使用してクラスタの更新処理を実行する必要があります。詳細については、 Deploy クラスタ設定の更新を参照してください。



== Deployを使用したシングルノードクラスタのアップグレード

Deploy 管理ユーティリティは、手順 の一部として使用して、 ONTAP Select シングルノードクラスタをホストする VMware ESXi ハイパーバイザーをアップグレードできます。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ノードをオフライン状態にします。
+
例 : node stop --cluster-name<clustername> --node-name <nodename>

. VMwareが提供する手順を使用して、ONTAP Selectが実行されているハイパーバイザーホストをESXi 7.0以降にアップグレードします。
. ノードをオンライン状態に移行します。
+
例 : node start --cluster-name<clustername> --node-name <nodename>

. ノードが起動したら、クラスタが正常であることを確認します。
+
例

+
....
ESX-1N::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
....


.完了後
Deploy 管理ユーティリティを使用してクラスタの更新処理を実行する必要があります。



== Deployを使用したマルチノードクラスタのアップグレード

Deploy 管理ユーティリティは、手順 の一部として使用して、 ONTAP Select マルチノードクラスタをホストする VMware ESXi ハイパーバイザーをアップグレードできます。

.このタスクについて
このアップグレード手順 は、クラスタ内のノードごとに 1 つずつ実行する必要があります。クラスタに 4 つ以上のノードがある場合は、各 HA ペアのノードを次の HA ペアに進む前に順番にアップグレードしてください。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. ノードをオフライン状態にします。
+
例 : node stop --cluster-name<clustername> --node-name <nodename>

. VMwareが提供する手順を使用して、ONTAP Selectが実行されているハイパーバイザーホストをESXi 7.0以降にアップグレードします。
+
詳細については、「 VMware ESXi のアップグレードの準備」を参照してください。

. ノードをオンライン状態に移行します。
+
例 : node start --cluster-name<clustername> --node-name <nodename>

. ノードが起動したら、ストレージフェイルオーバーが有効になっていてクラスタが正常に動作していることを確認します。
+
例

+
....
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
....


.完了後
アップグレード手順 は、 ONTAP Select クラスタで使用するホストごとに実行する必要があります。すべての ESXi ホストをアップグレードしたら、 Deploy 管理ユーティリティを使用してクラスタの更新処理を実行する必要があります。



== Deployを使用しないシングルノードクラスタのアップグレード

ONTAP Select シングルノードクラスタをホストしている VMware ESXi ハイパーバイザーは、 Deploy 管理ユーティリティを使用せずにアップグレードできます。

.手順
. ONTAP のコマンドラインインターフェイスにサインインしてノードを停止します。
. VMware vSphere を使用して、 ONTAP Select 仮想マシンの電源がオフになっていることを確認します。
. VMwareが提供する手順を使用して、ONTAP Selectが実行されているハイパーバイザーホストをESXi 7.0以降にアップグレードします。
+
詳細については、「 VMware ESXi のアップグレードの準備」を参照してください。

. VMware vSphere を使用して vCenter にアクセスし、次の手順を実行します。
+
.. ONTAP Select 仮想マシンにフロッピードライブを追加します。
.. ONTAP Select 仮想マシンの電源をオンにします。
.. 管理者アカウントで SSH を使用して ONTAP CLI にサインインします。


. ノードが起動したら、クラスタが正常であることを確認します。
+
例



....
ESX-1N::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
....
.完了後
Deploy 管理ユーティリティを使用してクラスタの更新処理を実行する必要があります。



== Deployを使用しないマルチノードクラスタのアップグレード

ONTAP Select マルチノードクラスタをホストする VMware ESXi ハイパーバイザーは、 Deploy 管理ユーティリティを使用せずにアップグレードできます。

.このタスクについて
このアップグレード手順 は、クラスタ内のノードごとに 1 つずつ実行する必要があります。クラスタに 4 つ以上のノードがある場合は、各 HA ペアのノードを次の HA ペアに進む前に順番にアップグレードしてください。

.手順
. ONTAP のコマンドラインインターフェイスにサインインしてノードを停止します。
. VMware vSphere を使用して、 ONTAP Select 仮想マシンの電源がオフになっていることを確認します。
. VMwareが提供する手順を使用して、ONTAP Selectが実行されているハイパーバイザーホストをESXi 7.0以降にアップグレードします。
. VMware vSphere を使用して vCenter にアクセスし、次の手順を実行します。
+
.. ONTAP Select 仮想マシンにフロッピードライブを追加します。
.. ONTAP Select 仮想マシンの電源をオンにします。
.. 管理者アカウントで SSH を使用して ONTAP CLI にサインインします。


. ノードが起動したら、ストレージフェイルオーバーが有効になっていてクラスタが正常に動作していることを確認します。
+
例

+
....
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
....


.完了後
アップグレード手順 は、 ONTAP Select クラスタで使用するホストごとに実行する必要があります。
