---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。 
---
= ONTAP Select Deployインスタンスのアップグレード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。



== 作業を開始する前に

アップグレード中には、 Deploy を使用して他のタスクを実行しないでください。Deploy ユーティリティのアップグレードに関する情報と制限事項については、最新のリリースノートを参照してください。


NOTE: ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、現在のリリースにアップグレードする必要があります。ONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます。を参照してください link:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^] を参照してください。



== アップグレードパッケージをダウンロードする

アップグレードプロセスを開始するには、ネットアップサポートサイトから適切な Deploy 仮想マシンアップグレードファイルをダウンロードする必要があります。アップグレードパッケージは単一の圧縮ファイル形式です。

.手順
. にアクセスします link:https://mysupport.netapp.com/site/["NetApp Support Site"^] Webブラウザを使用して、[ダウンロード]メニューから*[ダウンロード]*を選択します。
. 下にスクロールして* ONTAP Select展開アップグレード*を選択します。
. アップグレードパッケージの目的のリリースを選択します。
. エンドユーザライセンス契約（EULA）を確認し、*同意して続行*を選択します。
. 適切なパッケージを選択してダウンロードし、環境に応じてすべてのプロンプトに応答します。




== Deploy仮想マシンにパッケージをアップロードする

アップグレードパッケージを取得したら、ファイルを Deploy 仮想マシンにアップロードする必要があります。

.作業を開始する前に
アップグレードファイルをローカルワークステーションで使用できるようにしておく必要があります。また、管理者ユーザアカウントのパスワードが必要です。

.このタスクについて
このタスクは、ファイルを Deploy 仮想マシンにアップロードする方法の 1 つです。ご使用の環境に適したその他のオプションがある場合もあります。

.手順
. ローカルワークステーション上のコマンドシェルで、scpユーティリティを使用してイメージファイルをDeploy仮想マシンにアップロードします。
+
例

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレードファイルは、 admin ユーザのホームディレクトリに格納されます。



== アップグレードパッケージを適用する

アップグレードファイルが Deploy 仮想マシンにアップロードされたら、アップグレードを適用できます。

.作業を開始する前に
Deploy ユーティリティの仮想マシンでアップグレードファイルを配置したディレクトリを把握しておく必要があります。また、アップグレードの実行中には、 Deploy を使用して他のタスクを実行しないでください。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. 適切なディレクトリパスとファイル名を使用してアップグレードを実行します。
+
「 deploy upgrade-package-path filepath 」と入力します

+
例

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完了後
手順のアップグレードが完了する前に、Deploy仮想マシン設定のバックアップを作成するように求められます。また、新しく作成されたDeployページを表示できるように、ブラウザキャッシュをクリアする必要があります。
