---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。 
---
= ONTAP Select Deployインスタンスのアップグレード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select ONTAP Select Select Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。

.作業を開始する前に
アップグレード中にONTAP Select Deploy を使用して他のタスクを実行しないようにしてください。  ONTAP Select Deploy ユーティリティのアップグレードに関する情報と制限については、最新のリリース ノートを参照してください。

[NOTE]
====
ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、現在のリリースにアップグレードする必要があります。ONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます。を参照してください link:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^] を参照してください。

ONTAP Select Deploy 9.16.1 または 9.15.1 からONTAP Select Deploy 9.17.1 に直接アップグレードできます。ONTAP Select Deploy 9.14.1 以前からアップグレードするには、 ONTAP Selectバージョンのリリース ノートを確認してください。

====


== ステップ1: パッケージをダウンロードする

アップグレードプロセスを開始するには、適切なONTAP Select Deploy仮想マシンアップグレードファイルをlink:https://mysupport.netapp.com/site/["NetApp Support Site"^]。アップグレード パッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. にアクセスします link:https://mysupport.netapp.com/site/["NetApp Support Site"^] Webブラウザを使用して、[ダウンロード]メニューから*[ダウンロード]*を選択します。
. 下にスクロールして* ONTAP Select展開アップグレード*を選択します。
. アップグレードパッケージの目的のリリースを選択します。
. エンドユーザライセンス契約（EULA）を確認し、*同意して続行*を選択します。
. 適切なパッケージを選択してダウンロードし、環境に応じてすべてのプロンプトに応答します。




== ステップ2: ONTAP Select Deploy仮想マシンにパッケージをアップロードする

パッケージをダウンロードしたら、そのファイルをONTAP Select Deploy 仮想マシンにアップロードする必要があります。

.このタスクについて
このタスクでは、ファイルをONTAP Select Deploy 仮想マシンにアップロードする 1 つの方法について説明します。ご使用の環境に適した他のオプションがある可能性があります。

.作業を開始する前に
* アップグレード ファイルがローカル ワークステーションで使用可能であることを確認します。
* 管理者ユーザー アカウントのパスワードがあることを確認します。


.手順
. ローカルワークステーションのコマンドシェルで、 `scp` (Secure Copy Protocol) ユーティリティを使用して、次の例に示すように、イメージ ファイルをONTAP Select Deploy 仮想マシンにアップロードします。
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレードファイルは、 admin ユーザのホームディレクトリに格納されます。



== ステップ3: アップグレードパッケージを適用する

アップグレード ファイルをONTAP Select Deploy 仮想マシンにアップロードしたら、アップグレードを適用できます。

.作業を開始する前に
* ONTAP Select Deploy ユーティリティ仮想マシンのどのディレクトリにアップグレード ファイルが配置されているかを確認します。
* アップグレードの実行中に、 ONTAP Select Deploy を使用して他のタスクが実行されていないことを確認します。


.手順
. 管理者アカウントで SSH を使用してONTAP Select Deploy ユーティリティ CLI にSign in。
. 適切なディレクトリパスとファイル名を使用してアップグレードを実行します。
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
コマンド例:

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完了後
アップグレード手順が完了する前に、 ONTAP Select Deploy 仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたONTAP Select Deploy ページを表示できるように、ブラウザのキャッシュをクリアする必要があります。
