---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: ONTAP Selectノードで使用される各容量プールのライセンスファイルを取得する必要があります。ライセンスファイルでは、プールのストレージ容量と有効期限が定義されます。このライセンスは、ネットアップが割り当てた一意のライセンスシリアル番号と、 Deploy インスタンスに関連付けられたライセンスロック ID を組み合わせて、 License Manager にロックされます。 
---
= ONTAP Select容量プールライセンスを取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectノードで使用される各容量プールのライセンスファイルを取得する必要があります。ライセンスファイルでは、プールのストレージ容量と有効期限が定義されます。このライセンスは、ネットアップが割り当てた一意のライセンスシリアル番号と、 Deploy インスタンスに関連付けられたライセンスロック ID を組み合わせて、 License Manager にロックされます。

.作業を開始する前に
NetAppによって容量プールに割り当てられた9桁のライセンスシリアル番号が必要です。ライセンスファイルを取得する前に、注文書の出荷日から少なくとも 24 時間待ってください。

.このタスクについて
このタスクは、ONTAP Selectノードで使用される容量プールごとに実行する必要があります。

.手順
. Web ブラウザを使用してネットアップサポートサイトにアクセスし、サインインします。
. 上部の [*Systems*]( システム ) をクリックし、 [*Software Licenses*]( ソフトウェアライセンス ) をクリックします。
. 容量プールのライセンスシリアル番号を入力し、*[Go！]*をクリックします。
. ライセンスの詳細ページで、 * 製品の詳細 * 列に移動します。
. 該当する行の * Get NetApp License File * をクリックします。
. ONTAP Select Deploy インスタンスのライセンスロック ID を入力し、 * Submit * をクリックします。
. 適切な配信方法を選択し、 * Submit * をクリックします。
. 配信確認ウィンドウで [OK] をクリックします。


.完了後
容量プールをONTAP Selectノードで使用するには、事前にライセンスファイルをDeploy管理ユーティリティにアップロードする必要があります。
