---
sidebar: sidebar 
permalink: task_adm_connectivity.html 
keywords: administer, administering, web, connectivity, network connectivity, network checker 
summary: 内部クラスタネットワーク上にある 2 つ以上の ONTAP Select ノード間のネットワーク接続をテストできます。通常は、マルチノードクラスタの導入前にこのテストを実行して、原因 で処理が失敗する可能性のある問題を検出します。 
---
= ONTAP Select ノード間の接続を確認します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
内部クラスタネットワーク上にある 2 つ以上の ONTAP Select ノード間のネットワーク接続をテストできます。通常は、マルチノードクラスタの導入前にこのテストを実行して、原因 で処理が失敗する可能性のある問題を検出します。

テストに含まれるすべての ONTAP Select ノードを設定し、電源をオンにする必要があります。

テストを開始するたびに、新しいプロセスがバックグラウンドで作成され、一意の実行識別子が割り当てられます。一度にアクティブにできるランは 1 つだけです。

テストには、次の 2 つのモードがあります。

* Quick このモードは、基本的な無停止テストを実行します。ping テストが、ネットワークの MTU サイズと vSwitch のテストとともに実行されます。
* Extended このモードでは、すべての冗長ネットワークパスでより包括的なテストが実行されます。アクティブな ONTAP Select クラスタでこのテストを実行すると、クラスタのパフォーマンスに影響する可能性があります。



NOTE: マルチノードクラスタを作成する前には、必ずクイックテストを実行することを推奨します。クイックテストが正常に完了したら、本番環境の要件に基づいて拡張テストを実行することもできます。

.手順
. 管理者アカウントを使用して、 Deploy ユーティリティの Web ユーザインターフェイスにサインインします。
. ページ上部の * 管理 * タブをクリックし、 * ネットワークチェッカー * をクリックします。
. Start New Run * をクリックして、 HA ペアのホストとネットワークを選択します
+
必要に応じて、 HA ペアを追加および設定できます。

. [ * スタート * ] をクリックして、ネットワーク接続テストを開始します。

