---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: ONTAP Selectノードで使用される各容量プールのライセンスファイルを取得する必要があります。ライセンスファイルでは、プールのストレージ容量と有効期限が定義されます。このライセンスは、ネットアップが割り当てた一意のライセンスシリアル番号と、 Deploy インスタンスに関連付けられたライセンスロック ID を組み合わせて、 License Manager にロックされます。 
---
= ONTAP Select容量プールライセンスを取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectノードで使用される各容量プールのライセンスファイルを取得する必要があります。ライセンスファイルでは、プールのストレージ容量と有効期限が定義されます。このライセンスは、ネットアップが割り当てた一意のライセンスシリアル番号と、 Deploy インスタンスに関連付けられたライセンスロック ID を組み合わせて、 License Manager にロックされます。

.作業を開始する前に
* NetAppによって容量プールに割り当てられた 9 桁のライセンス シリアル番号が必要です。
* ライセンス ファイルを取得する前に、注文書の発送日から少なくとも 24 時間待つ必要があります。
* link:sizing-capacity-pool-license.html["Capacity Poolsライセンスのサイズ設定に関する考慮事項"]をレビューしました。


.このタスクについて
このタスクは、ONTAP Selectノードで使用される容量プールごとに実行する必要があります。

.手順
. link:https://mysupport.netapp.com/site/["NetApp Support Site"^]にログインします。
. *Systems* > *Software Licenses* を選択します。
. 容量プールのライセンス シリアル番号を入力し、*Go!* を選択します。
. ライセンスの詳細ページで、 * 製品の詳細 * 列に移動します。
. 適切な行で *NetApp ライセンス ファイルの取得* を選択します。
. ONTAP Select Deploy インスタンスのライセンス ロック ID を入力し、*送信* を選択します。
. 適切な配信方法を選択し、* Submit * を選択します。
. 配信確認ウィンドウで *OK* を選択します。


.完了後
ONTAP Select ノードが容量プールを使用する前に、ライセンス ファイルを Deploy 管理ユーティリティにアップロードする必要があります。
