---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。 
---
= Deploy インスタンスをアップグレードする
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティの仮想マシンをインプレースアップグレードできます。



== 作業を開始する前に

アップグレード中には、 Deploy を使用して他のタスクを実行しないでください。Deploy ユーティリティのアップグレードに関する情報と制限事項については、最新のリリースノートを参照してください。



== アップグレードパッケージをダウンロードします

アップグレードプロセスを開始するには、ネットアップサポートサイトから適切な Deploy 仮想マシンアップグレードファイルをダウンロードする必要があります。アップグレードパッケージは単一の圧縮ファイル形式です。

.手順
. Web ブラウザからネットアップサポートサイトにアクセスし、「 * Support Quick Links * 」をクリックします。
. [* Top Tasks] の下の [* Download Software* ] をクリックし、サインインします。
. [ * 製品の検索 * ] をクリックします。
. 下にスクロールし、 * ONTAP Select Deploy アップグレード * をクリックします。
. アップグレードパッケージの目的のリリースを選択します。
. エンドユーザライセンス契約（ EULA ）を確認し、「 * 同意して続行」をクリックします。
. 適切なパッケージを選択してダウンロードし、環境に応じてすべてのプロンプトに応答します。


link:https://mysupport.netapp.com["ネットアップサポート"^]



== Deploy 仮想マシンにパッケージをアップロードしています

アップグレードパッケージを取得したら、ファイルを Deploy 仮想マシンにアップロードする必要があります。

アップグレードファイルをローカルワークステーションで使用できるようにしておく必要があります。また、管理者ユーザアカウントのパスワードが必要です。

このタスクは、ファイルを Deploy 仮想マシンにアップロードする方法の 1 つです。ご使用の環境に適したその他のオプションがある場合もあります。

.手順
. ローカルワークステーション上のコマンドシェルで、 sftp ユーティリティを使用して、イメージファイルを Deploy 仮想マシンにアップロードします。
+
例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put ONTAPdeploy2.12_upgrade.tar.gz
exit
....


アップグレードファイルは、 admin ユーザのホームディレクトリに格納されます。



== アップグレードパッケージを適用しています

アップグレードファイルが Deploy 仮想マシンにアップロードされたら、アップグレードを適用できます。

Deploy ユーティリティの仮想マシンでアップグレードファイルを配置したディレクトリを把握しておく必要があります。また、アップグレードの実行中には、 Deploy を使用して他のタスクを実行しないでください。

.手順
. 管理者アカウントで SSH を使用して、 Deploy ユーティリティの CLI にサインインします。
. 適切なディレクトリパスとファイル名を使用してアップグレードを実行します。
+
「 deploy upgrade-package-path filepath 」と入力します

+
例

+
....
deploy upgrade -package-path /home/admin/
ONTAPdeploy2.12_upgrade.tar.gz
....


アップグレード手順 が完了すると、 Deploy 仮想マシン設定のバックアップを作成するよう求められます。また、新しく作成した Deploy ページを表示するには、ブラウザキャッシュをクリアする必要があります。
